### ISSUE TITLE
Question: Way to ignore errors during job

### ISSUE THREAD

**Issue by JamesBarnes88** [hazelcast/hazelcast-jet#1023]
I'm not sure if this is the right place to ask this or not. I am looking for a way to ensure that if an error occurs during job execution that the job itself is not put into a FAILED state. 

I want to be able to hook into how errors are handled so that I can create a handler that I could configure so that it will only FAIL a job when N(some threshold) errors have occurred. That or ignore the errors while logging them. 

So is this something that Jet or IMDG should be aware of? If this is something that JET should be responsible for, is it on the roadmap for v1?

**Comment by viliam-durina** [comment]
What kind of errors do you have in mind? Stream sources and sinks generally handle errors internally: they do not fail, they attempt to re-connect and retry. Batch source are written to fail.

Programming errors in various lambdas you supply (key extractors, map functions...) typically fail the job. If you need safety, write them defensively: catch the exceptions, do null-checks.

Please add more information: what kind of errors do you have in mind?

**Comment by JamesBarnes88** [comment]
Hey @viliam-durina I think you have answered my question. For more context we are currently migrating from Spring Batch to JET. Spring batch has something called a skip limit: [Spring Batch Docs: Configuring Skip](https://docs.spring.io/spring-batch/trunk/reference/html/configureStep.html#configuringSkip). If a skip limit is set and the number of errors thrown exceeds this limit, the job fails. This is what I was referring to in the first post.

The type of errors we want to ignore are the ones coming from the "`various lambdas you supply (key extractors, map functions...)`". For example, I receive an error while parsing a `String` because the format was wrong for an element in a given row of a CSV. After experiencing this I was able to put a try catch around the logic. But then I will need to do this for all lambdas we create.

I was also thinking that we could wrap a lambda somehow with try/catch logic by using a Utility method but then we would need to use this Util method for all lambdas we create. I guess I am looking for a lower level implementation of configured error handling that would ignore specified Exceptions or allow a certain number of exceptions to occur like in Spring Batch.

I'm not sure how many other ppl may have this issue or if it even a concern. But I know it would help our team out. Let me know what you think.

**Comment by viliam-durina** [comment]
What about this:
```
p.drawFrom(...)
 .map(MyObject::parse)
 ...;
```
```
public class MyObject {
    private static final AtomicInteger errorCount = new AtomicInteger(0);
    private static final ILogger LOG = ...;
    private int number;
    public static MyObject parse(String stringNumber) {
        try {
            MyObject result = new MyObject();
            result.number = Integer.parseInt(stringNumber);
            return result;
        } catch (NumberFormatException e) {
            if (errorCount.incrementAndGet() == 10) {
                throw e;
            } else {
                LOG.warning(null, e);
                return null;
            }
        }
    }
}
```

It uses a static `AtomicInteger`, which can be used by multiple lambdas in the job. The 10th exception will be thrown, others will be logged and ignored (mapped to null, which means they will be filtered out).

There is no member-to-member communication, there's separate counter on each member - the 10 errors have to happen on single member. For next execution of the job the counter will be reset thanks to class unloading and re-loading. For it to work this way, the `MyObject` class must not be available in member's classpath, but should be submitted using `JobConfig.addJar`. If `MyObject` was on member's classpath, the counter will be shared for all jobs and all executions and won't be reset between executions. I didn't actually test this but I think it should work this way.
