### ISSUE TITLE
Confusing exception "ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field..."

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#1043]
If this code is on the server's classpath, the job executes successfully.

```
	public static DAG build() {
		DAG dag = new DAG();

        Vertex source = dag.newVertex("readMapP", readMapP("source"));
        // The "noop" vertex triggers the exception
        Vertex noop = dag.newVertex("mapP", mapP(entry -> entry));
        Vertex sink = dag.newVertex("writeLoggerP", writeLoggerP());

        dag.edge(Edge.between(source, noop));
        dag.edge(Edge.between(noop, sink));

		return dag;
	}
```

If the job is launched from the Java client, and the code is on the client side classpath but not the serverside, you get this exception:

```
Caused by: java.lang.ClassCastException: cannot assign instance of
java.lang.invoke.SerializedLambda to field 
com.hazelcast.jet.core.ProcessorMetaSupplier$1.val$addressToSupplier of type 
com.hazelcast.jet.function.DistributedFunction in instance of 
com.hazelcast.jet.core.ProcessorMetaSupplier$1
```

It's the middle vertex, _noop_, which causes the fault. Remove it and it's fine from client or server submission.

Tested on 0.5.1 and 0.7-SNAPSHOT (today, 2018-09-13).

**Comment by neilstevenson** [comment]
Problem located, I was missing JobConfig

```
        JobConfig jobConfig = new JobConfig();
        jobConfig.addClass(MyClientDagBuilder.class);
	Job job =
	    	this.jetInstance.newJob(MyClientDagBuilder.build(), jobConfig);
```

worked from the client side.

**Comment by neilstevenson** [comment]
Partly this is _user error_ (mine!).

However, the root cause is very difficult to trace from the exception. It confused me, it'll confuse someone else.

Is there a way for client side job submission to verify if the referenced classes are in the job config ?

**Comment by viliam-durina** [comment]
>Is there a way for client side job submission to verify if the referenced classes are in the job config?

No. Client doesn't know which of the classes won't be known to the member.
