### ISSUE TITLE
API Discoverability: What do with with inherited JavaDoc?

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet#1053]
![image](https://user-images.githubusercontent.com/158619/45754827-02b09300-bc1d-11e8-81ca-c2eae3e2e3fc.png)

**Comment by viliam-durina** [comment]
I'm against copying the javadoc. It will certainly get out of sync after a time. For example, overridden methods in JDK don't copy the javadoc, unless they change the behavior, in which case they often use `{@inheritDoc}`

**Comment by mtopolnik** [comment]
We already have quite a scary amount of duplication in our Javadoc due to many similar method overloads. I'm definitely against making this worse.
