### ISSUE TITLE
ProcessorTasklet/StoreSnapshotTasklet lambda allocation pressure

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast-jet#1106]
Hi Jet Team,
there is significant lambda memory allocation pressure inside `ProcessorTasklet` and `StoreSnapshotTasklet`. See attached OJMC screenshot.
![tlab](https://user-images.githubusercontent.com/6349334/46744246-0929ac00-ccab-11e8-9163-528d6db7e8fe.PNG)

**Comment by cangencer** [comment]
Which version is this happening on?

**Comment by lukasherman** [comment]
0.6.1
