### ISSUE TITLE
Snapshotted jobs should be suspended on failure

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#1126]
Currently they are cancelled and the state snapshot is deleted. The failure might be caused by NPE based on unexpected null in the input.

**Comment by viliam-durina** [comment]
We also need to find a way how to communicate to the client that the job got suspended and what was the cause.

**Comment by cangencer** [comment]
This needs to be an optional feature with an option to turn it on.

**Comment by mtopolnik** [comment]
Closed by #2411.
