### ISSUE TITLE
runTest excuted twice

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast-jet#1150]
https://github.com/hazelcast/hazelcast-jet/blob/deea9335a9d56c9cc2b03af6fad6a0d227c15f2d/hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestSupport.java#L335

runTest is executed twice when there is some input.
When Processor tested modifies some external state, then this it passes on the first runTest, but fails on second runTest introduced here due to modified external state. Is this an intended behavior?
The previous (0.6) version allowed us to test Processors only once, the current version does not allow that.

Regards
Lukas Herman

**Comment by viliam-durina** [comment]
Yes, the scenario was added to added another possible issue with cooperative emission that we had. You're right, there's no option that would run only one scenario if you have input.

One way to fix this might be to reset the external state in your supplier which you pass to `verifyProcessor`. We might also consider to disable the full-inbox scenario, but I don't think it's necessary. Let us know if you managed to workaround it.

**Comment by lukasherman** [comment]
OK, thanks for clarification. 
I have managed to workaround it setting the initial state inside `ProcessorSupplier.get`. It is not very elegant, but works well.
Regards
LH
