### ISSUE TITLE
java.lang.IllegalArgumentException: "connectionSupplier" must be serializable

### ISSUE THREAD

**Issue by ekremucar** [hazelcast/hazelcast-jet#1179]
Jdbc sink claims that java.sql.Connection instance should be serializable.

java.lang.IllegalArgumentException: "connectionSupplier" must be serializable

............
	@Autowired
	DataSource myDs;

............

	Pipeline xx= yy(myDs.getConnection());

............

	private static Pipeline yy(Connection connection) {
		Pipeline p = Pipeline.create();
		p.drawFrom(Sources.<MyClass> list(DISTRIBUTED_LIST)).filter(obj -> obj != null).drainTo(

				Sinks.jdbc(ps, () -> connection, (stmt, aaa) -> {
					stmt.setDate(1, aaa.getId());
					......
				}));
		return p;
	}

**Comment by viliam-durina** [comment]
The connection supplier must create the connection, not return a pre-created one. The supplier will be serialized and sent to remote a member, it should create the connection after deserialization on the remote member.

```
Sinks.jdbc(ps, 
      () -> /* create connection here */, 
      (stmt, aaa) -> {
          stmt.setDate(1, aaa.getId());
          ......
      }));
}
```
