### ISSUE TITLE
Csv/JsonToObject sources

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast-jet#1205]
It's an often seen pattern, that user reads CSV/JSON file and creates object from it. 

Currently Jet has no dedicated connectors. While Json parsing is easy to do, CSV files has different structure: header and then rows, so we have to omit the first line, as there is no data there, then parse rows using header's order. In FileSource we can't "save" the header, so parsing CSVs requires custom source, which in general wouldn't be bad, 

However, CSVs are very commonly used. Making CsvToObject source (and probably JsonToObject, as it would be even easier) will for sure increase Jet's ease of use.

**Comment by TomaszGaweda** [comment]
For the future: I recommend SimpleFlatMapper, it's veeeeeery fast. I've a draft version of just source, but it's, well, in draft stage :P If it's enough to start review, I can publish draft PR for this issue. @cangencer @viliam-durina WDYT?

**Comment by cangencer** [comment]
If you could put it in some repo we could have a look? I'm not sure if we would add it to the core repo or to the upcoming "jet-contrib" repo for custom sources/sinks.

**Comment by cangencer** [comment]
@TomaszGaweda you can send the draft version as a PR to https://github.com/hazelcast/hazelcast-jet-contrib
