### ISSUE TITLE
Named operations

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast-jet#1207]
Hi,

currently, if we want to have some nice names of DAG vertices, we have to write something like:

`pipeline
.drawFrom(...).setName("read from source a")
.filter(xyz).setName("filter out wrong records")`

It is possible to name vertices, but in larger pipelines it becomes messy, especially when IntelliJ adds type hints - which during development and debugging are very helpful, but when just reading they don't look ok with additional setName. Instead, I suggest adding overloaded methods like:
- `filter (String stepName, DistributedPredicate<T> filterFn)`
- `map (String stepName, DistributedFunction<? super T, ? extends R> mapFn)`

the code will be just easier to read.

**Comment by viliam-durina** [comment]
Overloads have disadvantage in the multiplication of the number of methods. Some stage operations already have overloads. Adding an optional `name` parameter would double them. There's also `localParallelism` - adding that would double the number of overloads again. We decided to add methods instead of overloads.

Try to use formatting to fix this issue:
```
pipeline
    .drawFrom(...)
        .setName("read from source a")
    .filter(xyz)
        .setName("filter out wrong records")
```

**Comment by TomaszGaweda** [comment]
@viliam-durina I have other idea, similar to .setName - this weird formatting comes from the fact, that setName has to be called after operator. How about such change:
```
pipeline
    .step("read from source a")
    .drawFrom(...)

   .step("filter out wrong records")
   .filter(...)
```

It's much easier to read, as you know the name before action (like humans typically reads) and formatting can be inlined or moved to previous line, which is such more readable. What do you think about it?
