### ISSUE TITLE
Metrics deleted even if retentionSeconds not reached

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast-jet#1210]
From `setRetentionSeconds` JavaDoc:

>Returns the number of seconds the metrics will be retained on the instance. By default metrics are retained for 5 seconds (that is for one snapshot of metrics values). More retention means more heap memory but allows for longer client hiccups without losing a value (for example to restart Management Center).

However in JmxPublisher where is a comment `// remove metrics that weren't present in current rendering`. So, even if retentionSeconds hasn't elapsed, metric is removed if it's not visible in current reading. This causes that after every collecting period old metrics won't be available, even if they should according  to retentionSeconds parameter.

**Comment by viliam-durina** [comment]
Metrics are taken at regular interval, set by `MetricsConfig.setCollectionIntervalSeconds()`. Every N seconds a process reads out all the metrics values and stores them for the management center to read. If `retentionSeconds` is configured to, say, 60 seconds, management center will be able to read 60/5=12 collections back.

`JmxPublisher` is different. It registers and unregisters MBeans that are available through standard java JMX interface. For example, when a job finishes, its metrics are removed: the code you referred to unregisters the respective MBeans. `retentionSeconds` are not applicable to JMX beans.

**Comment by TomaszGaweda** [comment]
@viliam-durina is there any reason to not keep MBeans longer for JMX? I don't see any strong reason. Of course the simplest fix is to correct the JavaDoc (it's just misleading now), but from user's perspective, this parameter has much sense and would be great if it will work.

**Comment by viliam-durina** [comment]
Why not keep MBeans around? They reflect the metrics state at the moment of collection. If we didn't remove them, they would have stale values.

I improved the javadoc a bit: 
````
    /**
     * Returns the number of seconds the metrics will be retained on the
     * instance. By default, metrics are retained for 5 seconds (that is for
     * one collection of metrics values, if default {@linkplain
     * #setCollectionIntervalSeconds(int) collection interval} is used). More
     * retention means more heap memory, but allows for longer client hiccups
     * without losing a value (for example to restart the Management Center).
     * <p>
     * This setting applies only to Jet Management Center metrics API. It
     * doesn't affect how metrics are exposed through JMX.
     */
    public MetricsConfig setRetentionSeconds(int retentionSeconds);
```

**Comment by viliam-durina** [comment]
But MC knows how stale they are, it keeps a history.

**Comment by TomaszGaweda** [comment]
JmxPublisher also can track them ;) Using the same ringbuffer

**Comment by viliam-durina** [comment]
JMX exposes only "current value". It doesn't expose history. Can you propose the MBeans API you think of?

**Comment by TomaszGaweda** [comment]
In JetMetricsService we have a `scheduleWithRepetition` call, which causes that metrics are refreshed by Publishers.

The Publisher for MC adds entry to metricsJournal and those metrics are kept as long as buffer is not full. On the other hand, JmxPublisher only publishes metrics and then instantly removes metrics not present in current rendering in whenComplete().

Jmx Publisher can also use an ringbuffer and render always all presented metrics. whenComplete() will then:
- remove all metrics
- add all metrics from ringbuffer

or, even better, just update metrics & delete those which are not present in ringbuffer

**Comment by viliam-durina** [comment]
But this is how JMX beans are designed. They provide current view. Otherwise they would have to provide a list of historical values or something. We don't plan to change the API. If you want updates, you should poll the beans.

**Comment by TomaszGaweda** [comment]
>  If you want updates, you should poll the beans.

Sometimes jobs are very, very short. So I should then read metrics each 10ms, for example? It's quite expensive.

>  Otherwise they would have to provide a list of historical values or something.

But those values are stored, on Jet side, in the ringbuffered used by MC. It's only an adjustment of how both ways to read metrics works.

**Comment by viliam-durina** [comment]
>Sometimes jobs are very, very short. So I should then read metrics each 10ms, for example? It's quite expensive.
For very short jobs even that won't help. The metrics are sampled every 5 seconds by default, short-lived job might be unnoticed anyway.

**Comment by viliam-durina** [comment]
JMX is not a live snapshot at the moment of reading the MBean attribute. It also returns the last collected value, which might be up to 5 seconds old.

**Comment by cangencer** [comment]
You may try dumping JMX to something like logstash, but yes metrics are collected every 5 seconds and JMX beans aren't polled in real-time, but they show the current snapshot. What kind of metrics are you interested in for short-running jobs?

**Comment by TomaszGaweda** [comment]
Just for the record: I didn't reply, because if telling that piece of code is necessary to change is not enough and having responses that functionalities will not be adjusted to work in the same way, it means that it's "no, because then MC's metrics are not so valuable as they are now"; I know your licensing model, I won't shout and continue to write if I have in mind, that for you it's a bad idea to enable the same functionality as in paid version).

And also just for the record: simple JMX checking via JVisualVM / JFR is impossible now, as some metrics are gone before UI is refreshed (!). OK, maybe just JFR's UI is noo slow. Also metric gathering - even via Jet - is not efficient if you have dozens of jobs running on many nodes with massive amount of data. I've used to use Apache Spark for such jobs, I've given Jet a chance, but from user perspective support for monitoring is really bad - in Spark you have all recorded metrics for all jobs. Without the need to write custom code to handle it.

*Just to help people who will found this thread via Google*: I've written my own service to collect metrics in the way I've described - just reusing the same ringbuffer and perform update on every "tick" of MC's MetricsPublisher service. Workaround mentioned above (which is quite hacky if sits outside Jet) is good enough to continue work and have metrics history. Description above was enough for co-worker to say what needs to be done.

BTW. For short collection period, but long retention period, metrics will be recorded, but unavailable in current approach - were we don't use values chaged for Mgmt Center, but always delete everything.

**Comment by cangencer** [comment]
Hi Thomasz,

The kind of metrics we currently have are mostly designed for monitoring streaming jobs, if you have a batch job that lasted 4 seconds, I'm not sure having access to a single data point from a random point in the job would be particularly useful? Maybe you're more interested seeing the final metrics right at the end of the job - in this case the main useful ones would be things like number of records processed and throughput. I was asking about what metrics you were specifically interested in. 

As Viliam described JMX is designed to give you a "snapshot" of the current state - so only currently running jobs are available there and not historical data.
