### ISSUE TITLE
Support for custom metrics

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast-jet#1211]
Hi,

typically, users want to see how system is working, especially in ETL scenarios. Jet provides few metrics to track, however sometimes users want more metrics.

Currently, the only way of reporting custom metrics is to inject manually metric registration into each possible processor, however it's not always possible and sometimes just makes a lot of noise in code.

It would be great to extend ProcessorTasklet to support also custom registrations. For example, user can register listener, which has 3 options: before, after or around invocation of processor `process`, like in AOP. Then a whole new set of metrics is possible: execution time, objects received by type, etc., etc.

**Comment by viliam-durina** [comment]
You're right, we currently only allow to register custom metrics in processors. To wrap any processor in the pipeline, you can do this:

```java
        DAG dag = p.toDag();
        for (Vertex vertex : dag) {
            vertex.updateMetaSupplier(ps -> new WrappingProcessorMetaSupplier(ps,
                    proc -> new ProcessorWrapper(proc) {
                        // override methods as needed and call the superclass's method
                    }));
        }
        instance.newJob(dag); // use the `dag` instead of `p`
```

Please note that `WrappingProcessorMetaSupplier` and `ProcessorWrapper` are internal classes. Also if the code is not in a static method, the anonymous class will capture `this` instance, which might fail to serialize. In that case, use a static inner class.

**Comment by TomaszGaweda** [comment]
@viliam-durina Thanks for the workaround! Looks very promising. In future it would be great to have some more "official" way, but for now it should be enough for me

**Comment by TomaszGaweda** [comment]
@viliam-durina I don't think that it should be closed. updating meta processors is a quite hacky way, would be great to have official API for this

**Comment by viliam-durina** [comment]
We do update the meta suppliers for other reasons too, for example `.peek()` is implemented this way. But I agree, I'll keep it open.

**Comment by TomaszGaweda** [comment]
@viliam-durina I've used your workaround, works great. Can `@Probe` become non-internal? It's quite useful to have unified way of marking files as metrics inside processors.

**Comment by cangencer** [comment]
@TomaszGaweda we'll eventually make it public, however there are still upcoming changes in this area, making it public would require compatibility guarantees between minor versions.

**Comment by cangencer** [comment]
See #1692
