### ISSUE TITLE
Version not available from API

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#1219]
IMDG has `hazelcastInstance.getCluster().getLocalMember().getVersion()` to determine the node's version.

Jet should have an equivalent method.

**Comment by eminn** [comment]
How about this `BuildInfoProvider.getBuildInfo().getJetBuildInfo().getVersion()` ?

**Comment by cangencer** [comment]
Techinically that only returns the version of Jet you are using, not the node's (when invoked from client)
