### ISSUE TITLE
WriteHdfsP ProcessorSupplier overwrites JobConf

### ISSUE THREAD

**Issue by flostadler** [hazelcast/hazelcast-jet#1309]
The ProcessorSupplier of WriteHdfsP overwrites the settings `mapred.task.id` and `mapred.task.partition` of the `JobConf` configuration object. The concerned method is `WriteHdfsP::Supplier::get`.

Leading to all local-parallel Processors commiting to the same directory, because of them sharing one `TaskAttemptId`.
This leads to problems when one of these processors finishes before the others and triggers the commit.

A viable fix would be to copy the JobConf for each Processor that gets created.

I would be glad to help fixing this!

**Comment by cangencer** [comment]
@flostadler , could you say which version you are using? I see that each Processor would have a unique task attempt id, created here: 

https://github.com/hazelcast/hazelcast-jet/blob/master/hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/WriteHdfsP.java#L170

Note the `i` parameter which corresponds to unique processor id.

**Comment by flostadler** [comment]
I'm using 0.7.2.

Yeah for each processor a unique `TaskAttemptId` is generated, but in each Iteration of that loop the id is set to the `JobConf` object overwriting the previous one.

The outputwriters get their output-path from the `JobConf` using this settings.

**Comment by cangencer** [comment]
Which OutputWriter are you using? I think the ones we tested with were already creating the path when you create the `RecordWriter`, so this wasn't an issue. It seems like a good idea though to take a copy of the JobConf instead before creating each writer instance.

**Comment by flostadler** [comment]
I'm using `TextOutputFormat` with its LineRecordWriter.
Indeed you are right, the `RecordWriter` instances are created by there corresponding `OutPutFormats`. But they get their path from `FileOutputFormat::getTaskOutputPath`, and this method relies on the setting `mapreduce.task.attempt.id` which corresponds to the deprecated setting `mapred.task.id`.
Afaik almost every RecordWriter gets their path this way.

(Migrating from the deprecated configuration properties to the new ones would also be quite helpful.
FYI: This is due to a Hadoop API change - all of the "mapred" package where moved to "mapreduce" in version 2.x)

**Comment by cangencer** [comment]
Thanks, which version of Hadoop are you using? I wonder if this is due to some recent change in Hadoop, as I remember this was the original reason we were setting task IDs in the first place and committing each task separately. I would like to test it with the version you are using.

**Comment by flostadler** [comment]
We are running on version `2.7.3`.

But this has nothing to do with the hadoop cluster that is used.
The configuration properties are parsed from the `JobConf` and are the only thing that is important for the `RecordWriters`.

Im using version 3.2.0 of the hadoop libraries if you want to test that.

Setting the TaskIDs separately is the correct way to do it. But you can't use the same `JobConf` object, because of the problem with overwriting said properties.

**Comment by flostadler** [comment]
Sorry I totally forgot to mention that my `TextOutputFormat` is wrapped in a `LazyOutputFormat`.
The `LazyOutputFormat` postpones the creation of the wrapped record writer to the moment the first write happens. (This way no empty files are created)

And at the moment the writer gets created, the `JobConf` has already been overwritten.

**Comment by flostadler** [comment]
#1313

**Comment by gurbuzali** [comment]
fixed by https://github.com/hazelcast/hazelcast-jet/pull/1313
