### ISSUE TITLE
Make API more extendable

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast-jet#1310]
Hi! 

I've tried to add some shortcuts for commonly used functions in Jet Pipelines, like saving to "temp tables" (temporary lists; we have one scheme of names of them), performing some i.e. map+filter in one step.  Can't say exact functionalities because of NDA, but code reduction was very significant.

My idea was to:
- add some wrapper of pipeline, which in `drawFrom` will create `new CustomBatchStage<>(pipeline.drawFrom(source))`
- add CustomBatchStage, a class that will have field `BatchStage<T> underlying` and will delegate "normal" invocations to real batch stage, each time it will wrap result BatchStage in new CustomBatchStage (to make new methods still visible).
- the same class will have additional methods to perform some commonly used transformations.

However it fails, because in few places Jet casts stage:
```java
public static Transform transformOf(GeneralStage stage) {
        return ((AbstractStage) stage).transform;
    }
```

Second try was to extend AbstractStage, here I've tried to:
- use BatchStageImpl created by Jet, 
- get transformation and pipelineImpl from it 
- in constructor call `super(transformation, pipelineImpl)` 

-> this fails, because AbstractStage's constructor always registers given transformation. There is no option (without reflection) to create AbstractStage without registering node for the second time.

It's more an enhancement, but extending current API is quite hard. Of course I could use customTransform, but 1) it does not support writing to sinks 2) it's way less readable and more complicated to do

**Comment by viliam-durina** [comment]
`customTransform` is for processors that have both input and output. For custom sources and sinks, use `SourceBuilder` and `SinkBuilder`. Those have limited functionality, most importantly, they don't support state saving. If you need all functionality, use `Sources.fromProcessor` and `Sinks.fromProcessor`.

**Comment by cangencer** [comment]
@TomaszGaweda would some API that allows to build composite transforms (based on the basics provided by pipeline API) work for you?

**Comment by viliam-durina** [comment]
>performing some i.e. map+filter in one step

In `.map()` stage you can also do filtering by returning `null` from the mapping function

**Comment by TomaszGaweda** [comment]
Yes, that is exactly what I'm trying to do :) I've got some
project-specific transforms, that can be easily built on Pipeline API.
However, those transforms are used so commonly, that it generates a lot of
code duplication. Some way of "plugging" substeps will increase a lot user
code readability. For now I'm just splitting pipiline into many variables,
but this also does not look good for pipiline with many transforms (var
names are quickly becoming not meaningful or veeeery long)

wt., 5 mar 2019, 09:10 użytkownik Can Gencer <notifications@github.com>
napisał:

**Comment by TomaszGaweda** [comment]
@cangencer I though about this today, and adding following function i.e. to BatchStage:
```java


    default <R> BatchStage<R> pipe(FunctionEx<GeneralStage<T>, BatchStage<R>> pipedTransformation) {
        return pipedTransformation.apply(this);
    }

```

would make a huge difference in chaining. For example, it would be easier to write/read:
``
pipeline.drawFrom(...)
.pipe(Ops::calculateFinancialValues)
.pipe(Ops::prepareForSink)
.drainTo(Sink)
``

instread of:
``
var withFinancialRisksCalculated = Ops.calculateFinancialValues(pipeline.drawFrom(...));
var preparedForSink = Ops.prepareForSink(withFinancialRisksCalculated)
preparedForSink.drainTo
```

Code is more formatted like a "pipe", instead of passing stages manually to functions to return other stages. IMHO it's more clear with this `pipe` function. What do you think? If it's ok, I will work on it as soon as my PR with joins got merged (I forgot to change branch then and have master blocked).
