### ISSUE TITLE
Add option to force global parallelism = 1 for sources

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1360]

**Comment by lukasherman** [comment]
Would be nice to introduce global parallelism = <constant> as a default 'localParallelism' value instead of calculated one. Our use case requires localParallelism = 1 set on all Vertices.

**Comment by mtopolnik** [comment]
Closing because:

1. A custom source created through the `SourceBuilder` is already total-parallelism-one by default.
2. A natively implemented source has a way to specify this at the Core API level.
