### ISSUE TITLE
More convenience for AggregateOperations.maxBy()/AggregateOperations.minBy()

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1362]
maxBy and minBy should have an overload which take `Comparable` instead of having to use `ComparatorEx.comparing`

**Comment by cangencer** [comment]
It's trivial enough to add a signature like:

```
    @Nonnull
    public static <T, C extends Comparable<? super C>> AggregateOperation1<T, MutableReference<T>, T> maxBy(
            @Nonnull FunctionEx<? super T, ? extends C> comparisonKeyFn
    ) {
        checkSerializable(comparisonKeyFn, "comparator");
        return maxBy(ComparatorEx.comparing(comparisonKeyFn));
    }
```

however this makes it too easy to do unnecessary boxing, instead of using ComparatorEx.comparingLong() directly. I don't think it's worthwhile to create 3 extra methods for Double/Long/Int variants either.

**Comment by mtopolnik** [comment]
Closing because:

1. The APIs already support `Comparator`
2. `Comparator` works for both reference-typed and primitive comparison keys.
3. In the proposed new API, primitive types would need additional overloads.
