### ISSUE TITLE
Classloading issue when using mapUsingImap(mapName, lookupKeyFn, mapFn)

### ISSUE THREAD

**Issue by rajivgandhi1** [hazelcast/hazelcast-jet#1393]
I have been debugging a class loading issue between Jet & hazelcast. Below is the setup:
1. Standalone jet/hazelcast cluster
2. Remote client (java webapp) submits 2 pipelines (adds all relevant classes and jars in classpath to jobconfig):
p1: load data from disk to an Imap which has an indexed field 
p2: data pipeline operation 

3. User Code deployment enable on both server and client.  Some classes (just the Map V classes) added on the client side for user code deployment

p1:
```java
BatchStage<ViewerVO> stage = pipeline
  .drawFrom(SourceBuilder
    .batch("file-source", c -> {
        log.info("No of Files:" + files.size());                                                                      
        log.info("Total parallelism:" + c.totalParallelism());
        log.info("Global Index parallelism:" + c.globalProcessorIndex());
        List<List<URI>> partitionedFiles =  DistributedUtils
                          .partition(files, c.totalParallelism());
        log.info("No of partitions:" + partitionedFiles.size());
        return FileUtils.concatStreams(c.globalProcessorIndex() < partitionedFiles.size() ?
                        partitionedFiles.get(c.globalProcessorIndex()) :
                        Collections.emptyList());
    }                         
    )
    .<String>fillBufferFn((in, buf) -> {
        String line = in.readLine();
        if (line == null) {
           buf.close();                
           return;
        }         
        buf.add(line);                             
    })
    .distributed(4)
    .build())    
  .map(l -> parseViewer(l));

stage
.<Entry<Object, Viewer>>map(vv -> Util.entry(vv.getId(), vv.getViewer()))
.drainTo(Sinks.map(DistributedCollectionUtils.getDefaultCollectionName(Viewer.class)));

stage
.<Entry<Object, ViewerSegments>>map(vv -> Util.entry(vv.getId(), vv.getViewerSegments()))
.drainTo(Sinks.map(DistributedCollectionUtils.getDefaultCollectionName(ViewerSegments.class)));
```

p2:
```java
DataPipeline pipeline = DataPipeline.create();	
final String resultId = pipeline.getResultId();
final Predicate<Object, ViewerSegments> predicate = predicate1;

pipeline
 .<Entry<Object, ViewerSegments>>drawFrom(Sources.map(IDistributedEntity.getDefaultCollectionName(ViewerSegments.class),
							predicate, 
							Projections.identity()))
 .<Object, Viewer, Viewer>mapUsingIMap(DistributedCollectionUtils.getDefaultCollectionName(Viewer.class), vs -> vs.getKey(), (e,viewer) -> viewer) 
 .groupingKey(viewer -> viewer.getDma())
 .aggregate(AggregateOperations.counting())
 .drainTo(Sinks.map(resultId));
```

Execution of p2 results in a class not found error:
```
2019-05-12 21:53:53.081 ERROR 23204 --- [.async.thread-2] com.hazelcast.jet.impl.MasterJobContext  : [127.0.0.1]:5701 [local] [3.0] Execution of job '8253-fb08-e162-69cf', execution b8f0-0a19-7b89-02f6 failed after 151,138 ms
Caused by: java.lang.ClassCastException: xxx.Viewer cannot be cast to xxx.Viewer
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:41) ~[hazelcast-jet-3.0.jar:3.0]
	at com.hazelcast.jet.pipeline.GeneralStage.lambda$null$0(GeneralStage.java:440) ~[hazelcast-jet-3.0.jar:3.0]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[na:1.8.0_121]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[na:1.8.0_121]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_121]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_121]
	at com.hazelcast.jet.Util$1.onResponse(Util.java:170) ~[hazelcast-jet-3.0.jar:3.0]
	at com.hazelcast.util.executor.DelegatingFuture$DelegatingExecutionCallback.onResponse(DelegatingFuture.java:177) ~[hazelcast-3.12.jar:3.12]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:256) ~[hazelcast-3.12.jar:3.12]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-3.12.jar:3.12]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-3.12.jar:3.12]
```

My own debugging reveals the following:
1. P1 was earlier failing if indexing was enabled (on ViewerSegments) and I did not add the Map V classes in userCodedeployment settings on client. After I added these classes, P1 started working. Ideally, I think I should not have to add classes to userCodedeployment. The JetClassLoader should be passed down to the partiton thread.

2. P2 still fails. Apparently, since the same class is being loaded by both JetClassLoader and UserCodeDeploymentClassLoader. 

Why is the JetClassLoader not visible to Partition threads to avoid the duplicate class loading?
Or, alternately, make the UserCodeDepoymentClassLoader parent to JetClassLoader.

Any suggestions?

thanks!!

**Comment by rajivgandhi1** [comment]
I ended up solving this problem by providing custom class loaders for both UserCodeDeployment and Jet with a shared parent class loader to load shared classes

**Comment by viliam-durina** [comment]
Looks like an issue on our side: when you use a predicate, the value is deserialized on the member that owns the partition and it's not re-serialized when the read request was executed on the same member. Your diagnosis was right, Jet doesn't share the class loader with imdg.

Can you please share how were you able to workaround it?

**Comment by rajivgandhi1** [comment]
I solved it by:
-  adding a class loader for hazelcast (singleton) & a class loader for jet (set in jobconfig). 
- The jet class loader's parent is set to the hazelcast classloader. The userCodedeployment classloader has its parent set to the class loader. 
- These class loaders basically use the same mechanism in the jet classloaders where classes are loaded to an Imap.
- the hazecast class loaders loads and stores all classes with a marker interface to a common shared key namespace
- the jet class loaders stores it to an application key namespace (it actually scans the full application class paths and uploads the whole app.

the good thing is that i was able to add caching to my jet class loader. so the cost of uploading the classes is incurred only the first time. Also, the whole f/w is seamless for application development where the application code does not have to enlist specific classes to load.

**Comment by cangencer** [comment]
It looks like the Jet CL 's parent is set to `null`, so it won't see UCD classes, it should be set `Node.getConfigClassLoader()` instead. Currently it looks like Jet CL doesn't search UCD because of this. Your solution/workaround seems fine for now.
