### ISSUE TITLE
withIngestionTimestamps() should accept allowedLag parameter

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet#1426]
Other timestamping strategies support it. 

Lag configuration with ingestion timestamps make sense with distributed sources: You want to compensate for clock diff between boxes.

**Comment by viliam-durina** [comment]
You don't need to compensate for clock diff between boxes, that's compensated automatically by watermark coalescing: the downstream processor will process the watermark only after it receives it from all upstream processors, that is from local and remote ones. With ingestion timestamp it's impossible to get late events (except for the case when you adjust the system clock backwards).

**Comment by jerrinot** [comment]
"the downstream processor will process the watermark only after it receives it from all upstream processors" <-- I didn't know that, thanks!
