### ISSUE TITLE
De-serialization exception for Object[] with remoteMap sink to pure IMDG cluster

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#1444]
See https://github.com/hazelcast/hazelcast/issues/15181 and https://github.com/hazelcast/hazelcast/issues/15179

IMDG only clusters and IMDG+JET clusters have a mismatching definition for certain object types.

For example, https://github.com/hazelcast/hazelcast-jet/blob/master/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/SerializerHookConstants.java#L32 defines -302 for `Object[]`

If a job uses `Object[]` in the output and remote map sink to an IMDG only cluster, the job works. However, the data record in the remote IMDG only cluster has type -302 which the IMDG only cluster cannot recognise.

This gives 
```
com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type -302. This exception is likely to be caused by differences in the serialization configuration between members or between clients and members.
```
when the remote IMDG only cluster attempts to deserialize the data record.

Remote source appears to be ok. Jet will receive the data record for `Object[]`. It won't be tagged with -302 and perhaps then gets picked up by default serialization handling from IMDG. Probably needs further investigation to be sure if remote source if ok in general.

**Comment by neilstevenson** [comment]
Tested on Jet 3.0 against IMDG 3.9 onwards

**Comment by cangencer** [comment]
See also: https://github.com/hazelcast/hazelcast/issues/15179

**Comment by cangencer** [comment]
This was fixed in https://github.com/hazelcast/hazelcast/pull/15506
