### ISSUE TITLE
Missing concise information about metrics

### ISSUE THREAD

**Issue by vladoschreiner** [hazelcast/hazelcast-jet#1464]
I wanted to learn about Jet's metrics system. The objective was to learn how Jet can interact with my monitoring software.

Issue 1 - metrics list is hidden in Expert Zone — The Core API. I can't see the link between Core API and Metrics as an user. Move metrics to chapter 3.8. Monitor Execution and Diagnose Problems.  Move Management center configuration (metrics enabled for MC) to both 3.10. Management Center and to the ref man of the IMDG.

Issue 2 - this is just Jet metrics. We expect people to know about the existence of IMDG (cluster!) metrics. This should be at least mentioned and linked in the refman.

Issue 3 - document the metrics system of Jet. How it works, how/if can it be extended.

**Comment by jbartok** [comment]
Status update: 
* issue 1 and 2 have been done since a long time now. See latest version of the manual
* issue 3 is not really doable until we figure out what we're going to do about user metrics (no good ideas yet)

**Comment by cangencer** [comment]
I see metrics are still listed under JMX beans

**Comment by jbartok** [comment]
Have updated job metrics section in the reference manual a bit (https://github.com/hazelcast/hazelcast-jet/pull/1589). Pls. let me know if this is enough or if you would like a more radical rewrite of the whole metrics section (ie. make it not so much JMX focused, even though that's still our generic way of looking at metrics).

**Comment by jbartok** [comment]
The metrics info in the refman have been updated. Anything else on this issue? Could we close it? I guess custom/user metrics will be a completely different story.

**Comment by cangencer** [comment]
Fixed in #1589
