### ISSUE TITLE
com.hazelcast.jet.core.ExecutionLifecycle_RestartableExceptionTest got stuck

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1470]
_master_ (commit 7709436728bfb05b914873b77b95e828bbd89a3a)

Failed on Sonar build: http://jenkins.hazelcast.com/view/Jet/job/jet-oss-master-sonar-nightly/166/

From test execution log http://jenkins.hazelcast.com/view/Jet/job/jet-oss-master-sonar-nightly/166/consoleFull it seems that there is one test - `com.hazelcast.jet.core.ExecutionLifecycle_RestartableExceptionTest` - which was running but which has not been finished. What is also weird is how it is possible that it got stuck infinitely and the test was not interrupted after some predefined limit (I think it is 5 minutes).

**Comment by viliam-durina** [comment]
The build was aborted, artifacts not uploaded to s3. Without the test logs it's hard to tell what happened.
The test uses `HazelcastSerialClassRunner`, which should fail the test after 5 minutes. Not sure why it didn't.

**Comment by olukas** [comment]
It happened again in http://jenkins.hazelcast.com/view/Jet/job/jet-oss-master-sonar-nightly/180/

**Comment by olukas** [comment]
The same happened also with Zulu JDK 11: http://jenkins.hazelcast.com/view/Jet/job/jet-oss-master-zulu-jdk11/70/
