### ISSUE TITLE
hazelcast jet Sources.files has some problem

### ISSUE THREAD

**Issue by ppsnumi** [hazelcast/hazelcast-jet#1484]
Hello Jet team.

I have some problem using hj(hazlecast jet)
that's is throw exception for web access log analysis using hz.

web access log file encoding is specified(euc-kr)  but user sending parameter value(utf-8) sometime out of range log file encoding.

I can't get line using Sources.fileBuilder(path).charset("EUC-KR").build()
and get exception  "UnmappableCharacterException: Input length = X"
(same error when change encoding to utf-8)

and this error same throw when only using JDK8's Files.readAllLines().
ex:
Files.readAllLines(Paths.get(path, filename), Charset.forName("EUC-KR"));

how to solve this problem????

thanks~

**Comment by cangencer** [comment]
Can you attach a sample file ?

**Comment by ppsnumi** [comment]
I'm sorry for not being able to attach a log file for security reasons.

At first, I thought the above was the cause of the error,
I've tracked JDK internal functions and found that they are not related to the characters in the file.

We have tested the logs of several systems and found that if the log file (euc-kr) exceeds 50Mb, the error probability is very high and it is not related to the characters in the file.
This seems to be a bug or problem in Java itself.

oracle java 1.8.0_202 64bit on windows 10
Checking the error line with the following logic and checking the line of the file resulted in an error in the line with only alphabet.


    	try {
    		int lineCount = 0;    		
    		 try (BufferedReader reader = Files.newBufferedReader(Paths.get(TARGET_FILE_PATH, "access_npiser_7"), Charset.forName("EUC-KR"))) {
    	            List<String> result = new ArrayList<>();
    	            for (;;) {
    	            	lineCount++;
    	            	System.out.println("line:"+lineCount);
    	                String line = reader.readLine();
    	                if (line == null)
    	                    break;
    	                result.add(line);
    	            }
    	            System.out.println(result);
    	        }    		
    	} catch(Exception ex) {
    		ex.printStackTrace();
    	}
    
The above logic reproduces the contents of the readAllLines of the Files object in Java.

As a result, the following error occurs.

java.nio.charset.UnmappableCharacterException: Input length = 2
	at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)


thanks...
