### ISSUE TITLE
Non-numerical metrics

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast-jet#1486]
Hi,

in ETL-like scenarios it's a common thing to track i.e. file names that were read by application. It's also quite common to i.e. move successfully read files to other directory.

Would be great if Jet's metrics system could be expanded to support non-numerical metrics. This will allow to start new task, to log read files as metrics.

Disclaimer: I know that metrics in general are more numeric-style measurements. However, in certain situation, such metadata of job is very needed. Instead of supporting non-numerical metrics, we can i.e. allow some metadata registration within the job.

**Comment by viliam-durina** [comment]
You mean that the metric would be a list of strings? If it's a part of the application logic, it would be better to store it to IList as a part of the job logic.

**Comment by cangencer** [comment]
You can maybe do this using a mapUsingContext operator? Save the name of the file to a ISet/IList upon receipt and then you can have listeners acting on updates to the list.

**Comment by TomaszGaweda** [comment]
Thanks @viliam-durina and @cangencer for the response! And sorry for the late response.

For the bigger picture: our customer have an ETL-style application. They want to see on node-level which files were read and, after successful processing, they want those files to be automatically moved to other directory. In case of failure - errored files have to be moved to errored directory. 

Non-numerical metrics would be helpful in the first requirement. File connectors can save which file they've read, queue-like sources would save from which topics they read the data. The key is, if there is an error during initial reading, no lines will be emmited - so there is no sense to provide this information as an output, because it will fail before output is created.

To be honest, this combined with second requirement (which came later) caused that I became to question sense of this ticket. If we want per-file resiliency, then there will be always one file, specified in file connector's glob (which will contain exact name of file). 

Still some users may want to see things like files read / topic read, as it's typical in ETL scenarios and you can do this in ESBs for example. Some kind of job state (where operators can write/read as side effects to provide context info) would be helpful, but only when all/most of the operators will support this. I leave it for your considerations, maybe this ticket may come back in other form later :)

**Comment by viliam-durina** [comment]
Seems like you need a custom file reader. The out-of-the-box reader doesn't give you a chance to emit an item or to execute an action when it completes a file.

**Comment by TomaszGaweda** [comment]
@viliam-durina Yes, this was an addition to make such things possible in all connectors. However, I see there is much more to think about, so I'll close this issue now and came back if I manage to build some concrete example
