### ISSUE TITLE
Snapshot artifacts not being published?

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet#1518]
I wanted to try the [MongoDB connector](https://github.com/hazelcast/hazelcast-jet-contrib/tree/master/mongodb), but apparently it's not published in the [snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/jet/contrib/)

The last update is from mid-July. 
![image](https://user-images.githubusercontent.com/158619/62471514-1a452b80-b79d-11e9-88c9-942c12ec7c0c.png)

The Redis connectors are missing too.

**Comment by eminn** [comment]
The build is not passing due to some test failures which signals some resource exhaustion. We'd have a fix for that in the PR builder, I am going to apply same fix and see if it fixes.

**Comment by eminn** [comment]
For the future reference: I've limited maximum number of gradle workers to 2. This way when the tests are running they don't create a lot of Docker containers in parallel, which in turn decreases the resources consumed by the build
