### ISSUE TITLE
Name of job displays only first 24 chars in jet.sh list-jobs command

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1520]
_master_ (commit 1aaf7f16a7fa771e8cd3070be1506a7afe566c45)

Only first 24 chars is displayed in `jet.sh list-jobs` command. It means that there is no difference in name output of jobs which have the same start of the name (and they differ in some suffix).

It can be reproduced by submitting two jobs with name `ThisIsJobWithVeryLongName_suffix1` and `ThisIsJobWithVeryLongName_suffix2`:
```
./jet.sh submit -n ThisIsJobWithVeryLongName_suffix1 $PATH_TO_REMOTE_JOB_JAR
./jet.sh submit -n ThisIsJobWithVeryLongName_suffix2 $PATH_TO_REMOTE_JOB_JAR
```
It will result to:
```
./jet.sh list-jobs
NAME                     ID                  STATUS             SUBMISSION TIME        
ThisIsJobWithVeryLongNam 02ed-aaad-7d00-0001 RUNNING            2019-08-06T08:48:02.895
ThisIsJobWithVeryLongNam 02ed-aaa3-a640-0001 RUNNING            2019-08-06T08:47:52.827
```

I would expect that this will occur also in similar commands (like `list-snapshots`).

**Comment by cangencer** [comment]
This was done on purpose to limit the length of a line, but maybe we can make the allowed length longer, or move the job name to the last column?

**Comment by olukas** [comment]
We can also have a default behavior as it is now and introduce some option for allow to show full job name on demand.
