### ISSUE TITLE
Duplicates for verbosity and version options in jet.sh

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1523]
_master_ (commit 1aaf7f1)

Both `verbosity` and `verbose` options can be defined whole global `jet.sh` command level and also on certain command level (e.g. in `submit` command). Since both of these options are global it makes sense to have them defined only on global level to have certain commands in `jet.sh` more clear.

**Comment by viliam-durina** [comment]
All (not some) commands have it. I think it's useful and not harmful to have it both global and per-command. Now both of these will work:
```shell
jet -v suspend <jobId>
jet suspend -v <jobId>
```
I'm against implementing this.

**Comment by olukas** [comment]
I'm ok with closing this one if this behavior is intended and if @vladoschreiner will agree that it is ok from UX point of view. It is definitely not an issue but maybe some possible enhancement. I've just decided to mention it since it can be confusing. @vladoschreiner WDYT?

**Comment by cangencer** [comment]
It's just convenience, you can specify verbosity either way. I think originally it was only on the global level, but we added the command level since someone asked for it. I think it was @jerrinot if I remember correctly. I think we can close this.

**Comment by olukas** [comment]
Ok, seems reasonable. I'm closing it.
