### ISSUE TITLE
Performance enhancements for job metrics

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#1531]
- the `RawJobMetrics` can use two equal-length arrays: `String[] names` and `long[] values` instead of `Map<String, Long>`. Will use much less memory. We never query by metric name, we only iterate the entries.
- we could store `RawJobMetrics` on master in `List<Entry<Address, RawJobMetrics>>` instead of merging the metrics. `RawJobMetrics` could also be sent to the client and only the client will convert it to `JobMetrics` for the ease of use. The aim is to reduce memory and do as little collection transformations as possible - for example merging re-creates the map for each member.

**Comment by jbartok** [comment]
These concerns are all obsolete after or are addressed by https://github.com/hazelcast/hazelcast-jet/pull/1561.
