### ISSUE TITLE
Inconsistent information about help option in different jet.sh commands

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1534]
Help information about some of commands includes option `help` (`-h, --help Show this help message and exit.`) but some of them don't. It should be unified.

Commands `help`, `submit`, `suspend` include this information.
Commands `cancel`, `cluster`, `delete-snapshot`, `list-jobs`, `list-snapshots`, `restart`, `resume`, `save-snapshot` do not include this information.

**Comment by viliam-durina** [comment]
I removed the option from all commands. It's not necessary and works without being printed. Now:
```shell
jet.sh help COMMAND
``` 
never prints the `-h` option, but this still works and is equivalent to the above command:
```shell 
jet.sh COMMAND -h
```
