### ISSUE TITLE
jet 3.1 incompatible with hazelcast imdg for newJetClient type of connections

### ISSUE THREAD

**Issue by yigitmultibankfx** [hazelcast/hazelcast-jet#1568]
When you try a simple pipeline join and run the word count example, after you create a connection to an already existing cluster member by using newJetClient, the hazelcast imdg cluster member gives the following error:
Exception in thread "main" java.lang.UnsupportedOperationException: Unrecognized client message received with type: 0x1a01
Even though I might be doing something wrong (which is possible cause I am quite new in the hazelcast sphere) it is a little bit discouraging to get such a generic error message at this level.

Another point, I would like to see at least one example in the repository which connects to an existing cluster member. I think it should be a very very common use case.

**Comment by cangencer** [comment]
There is no such example because you can't run Jet jobs on non-Jet members. You need to have a Jet cluster (started with Jet.newJetInstance()) to able to use jobs.

**Comment by viliam-durina** [comment]
The Message 0x1a01 is `submitJob`. You're trying to submit a Jet job to a non-Jet cluster.

Jet is built on top of hazelcast. Each Jet cluster _is_ also a Hazelcast IMDG cluster, but not vice versa. You have to download the [Jet package](https://jet.hazelcast.org/download/) and start the cluster from that. If starting from code, use `Jet.newJetInstance()`.

**Comment by yigitmultibankfx** [comment]
Thanks for the prompt reply. It worked like a charm. What bugged me in the first place was that I thought Jet is a library or framework that has to work with and on topf of an Hazelcast IMDG cluster, but now I understand that Jet is also a standalone platform on its own.
