### ISSUE TITLE
Sinks.remoteMap working, while Sinks.remoteMapWithUpdating is failing

### ISSUE THREAD

**Issue by aliman17** [hazelcast/hazelcast-jet#1582]
Hi, 

I have trouble using Sinks.remoteMapWithUpdating where I get 
`com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.example.package.MyPipelineGenerator`.

However, it works without problems when I use remoteMap. 

All I do in my update function in remoteMapWithUpdating is to return null on empty values to remove entry from my sink map. 

```
(oldSummary, newSummary) -> {
    if (newSummary != null && newSummary.getValue() != null) {
        return newSummary.getValue();
    }
    return null;
};
```

Does anyone has any idea, what I am missing to make remoteMapWithUpdating work?

**Comment by viliam-durina** [comment]
The remote server needs to know the class containing the lambdas you use to update the map, you have to use User Code Deployment to provide it. Providing your full code and full stack traces will help us be more specific.

**Comment by aliman17** [comment]
Ok, great. I think this explains my problem. 

I'm trying to push changes into remote hazelcast IMap and it definitely does not see my class containing lambda. 

Thanks, I'll update my code.
