### ISSUE TITLE
Stream + batch processing with same sink

### ISSUE THREAD

**Issue by alenbec** [hazelcast/hazelcast-jet#1590]
Hello everyone,

I would like to use Jet to do some enrichments and aggregation on current IMap data but would also like to continue to listen to changes on that IMap and process them while they occur.
So basically what I would need is an option to batch process existing data and continue with stream when done batch processing without loosing any events that occur while batch does its job.

If I first run batch and after it finishes run stream (START_FROM_OLDEST) I risk loosing events if event journal is not big enough.
If I run stream processing (START_FROM_CURRENT) to collect new data and right after that batch process all data in IMap I wouldn't loose any events, but there is a chance batch and stream would overwrite each other because they would point to same sink.

What would be the best approach to solve this issue? Is there any other alternative?

Thanks in advance,
Alen

**Comment by cangencer** [comment]
Currently there isn't a way to do this which will keep the data consistent and de-duplicated. The batch source can't be used while map is being mutated as it can read duplicates or missing entries. Reading the event journal is the only option for a map that's constantly changing.

**Comment by alenbec** [comment]
@cangencer thanx for information, appreciate it!
