### ISSUE TITLE
AssertionCompletedException not propagated from Sinks

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet#1609]
I am trying to use the assertion support in Jet 3.2, but it's not working as expected. I can see `com.hazelcast.jet.pipeline.test.AssertionCompletedException: Assertion passed successfully
` in a log, but the `AssertionCompletedException` is not propagated successfully. 

The reproduce bellow is expected to pass, but it fails inside the `assertInstanceOf` as the `actual` is set to `null`. 

```java
public class TestTest {
    @Test
    public void foo() {
        Pipeline pipeline = Pipeline.create();
        pipeline.drawFrom(TestSources.itemStream(1))
                .withIngestionTimestamps()
                .drainTo(AssertionSinks.assertCollectedEventually(60, e -> {} /*always accepted*/));

        JetInstance instance = Jet.newJetInstance();

        Job job = instance.newJob(pipeline);

        try {
            job.join();
        } catch (CompletionException e) {
            Throwable jetException = e.getCause();
            Throwable cause = jetException.getCause();
            assertInstanceOf(AssertionCompletedException.class, cause);
        }
    }

    private static <E> void assertInstanceOf(Class<E> expected, Object actual) {
        assertNotNull(actual);
        assertTrue(actual + " is not an instanceof " + expected.getName(), expected.isAssignableFrom(actual.getClass()));
    }
}
```

**Comment by jerrinot** [comment]
possible a regression caused by https://github.com/hazelcast/hazelcast-jet/issues/1598

**Comment by viliam-durina** [comment]
Yeah, you cannot assert the exact instance, I updated the refman too, see example here: https://docs.hazelcast.org/docs/jet/latest-dev/manual/#streaming-2

**Comment by jerrinot** [comment]
that does not sound good. assertion just on a exception text is fragile and does not feel good.

also I guess this does not affect only the assertion framework, right? so the original exception are not longer propagated to whoever is collecting a job result?

**Comment by viliam-durina** [comment]
Yes, that's the case. The reason is that the exception can be user-defined and require a job's classloader to deserialize. We store the exception as text for completed jobs and always report it restored from the text to the client.

Another approach could be to use the approach the client uses: to restore original exception if possible and use `UndefinedErrorCodeException` otherwise. For now we went the simplest way.

**Comment by jerrinot** [comment]
That's a good point about custom exceptions. While we could have a special treatment for always-known-to-be-available classes I feel it could actually add to the confusion: 2 different failure modes.

**Comment by viliam-durina** [comment]
IIRC we realized this with JDBC connector that threw custom exception of the JDBC driver. We're discussing possibility to save the stack trace also because that's lost too.

**Comment by jerrinot** [comment]
yeah, storing a stacktrace should be trivial and it would help a lot.
