### ISSUE TITLE
Remove key from StreamStageWithKey.filterUsingContext

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1643]
There is inconsistency between `filterUsingContext` and `filterStateful` in `StreamStageWithKey` - `filterUsingContext` takes key. However this is mostly for historical reasons. During Jet 4.0 we should make those two methods consistent by remove legacy key from `filterUsingContext`.

**Comment by cangencer** [comment]
We decided not to change this, as key can be used for lookup for filterUsingService.
