### ISSUE TITLE
Remote IMDG failure when using Kubernetes

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#1676]
This issue on IMDG https://github.com/hazelcast/hazelcast/issues/15671 affects Jet.

In `ImdgUtil.asXmlString(ClientConfig clientConfig)` attempting to sent the client config loses sections, such as Kubernetes discovery.

So a pipeline with a remote IMDG won't work with Kubernetes discovery.

This is not really a Jet bug, but perhaps should have a test for it.

**Comment by cangencer** [comment]
Fixed in 4.0 (see https://github.com/hazelcast/hazelcast/issues/15671)
