### ISSUE TITLE
Is it possible to force job execution on single instance in cluster? 

### ISSUE THREAD

**Issue by aliman17** [hazelcast/hazelcast-jet#1677]
I'm hitting a problem that we would like to deploy a temporary solution with a job that would run on a single instance. 

As I read in docs and also experienced by myself ... pipeline behaves differently when I'm executing it on a single instance or in a cluster due to consecutive processing, etc. 

Is it possible to set job config somehow to be run only on a single instance?

**Comment by viliam-durina** [comment]
Jet always executes the job on all members. You can only specify local parallelism for stages and it determines the parallelism on each member.

The difference between running on one and multiple members is that on one member nothing is serialized, the stream items are passed by reference.

**Comment by aliman17** [comment]
Thanks. Could you clarify also the following question ...

If I have 2 instances, then some events from my source map will go directly to one instance and some to another one. 

Is this correct? 

Problem is that I'm using group by, following by other operations afterward, and I'm seeing correct result on 1 instance and incorrect when using 2 or more.

**Comment by viliam-durina** [comment]
I guess you use `Sources.map`. For this source processors on each member read local data so yes, part of data will be handled by each member. 

When you use `groupingKey()`, you repartition the data using a new key. If you use the same key as the source map uses, nothing will actually be repartitioned and again, the members will process only local data.

In what way are your results incorrect? Could you share your pipeline code and actual and expected results?

**Comment by viliam-durina** [comment]
I don't see body or types of any of the functions (`updateStateFn`, ,`extractSummaryFn`...) or the window (`customWindow`), but your problem might be that you overwrite the keys over and over in the sink map. If you key in the sink isn't unique (for example if you ignore the `isEarly` flag on the `KeyedWindowResult`), then the values in the sink map will be overwritten.

The partitions of the stream are processed separately, one key is always processed on one member. I don't see any problem in the above code, but lot is missing there for a complete pipeline.

**Comment by aliman17** [comment]
Yes, that's exactly what's happening. I thought, group by would solve this. I'll rearrange my pipeline that I can use Sinks.mapWithEntryProcessor which I guess will solve my problem.
