### ISSUE TITLE
Metrics warnings

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#1699]
On 3.2, if `hazelcast.diagnostics.metric.distributed.datastructures` is set, the logs have
*WARN* messages from the MetricsRegistry of the form

```
Overwriting existing probe 'map[__jet.records].lockedEntryCount'
Overwriting existing probe 'map[__jet.records].dirtyEntryCount'
Overwriting existing probe 'map[__jet.records].backupCount'
```

**Comment by cangencer** [comment]
These are resolved with new metrics infrastructure in 4.0
