### ISSUE TITLE
Hadoop Packaging Issues

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast-jet#1707]
Hadoop has issues with broken backward compatibility within the 2.x minor version range. Therefore we declare our Hadoop dependencies as `provided`. 

Action items:

1. Document that it is not enough to use `hazelcast-jet-hadoop` dependency in your Maven project, list which other artifacts you have to explicitly name because Jet needs them.

2. On our website's download page, provide the fat JARs of `hazelcast-jet-hadoop` with each of the mutually incompatible Hadoop versions.

3. Explain how to use Hadoop with Jet's distribution ZIP in the ZIP's readme.

**Comment by cangencer** [comment]
The documentation of this was done in #1830. The bundle download part won't be done for 4.0 at this point.
