### ISSUE TITLE
jet.sh submit reports error messages as NULL

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1717]
In 3.2, jet.sh submit always reports error messages as null unless verbose mode is used when using JDK9+. There is a fix in 4.0, should be backported to 3.2.1 if needed.

**Comment by gurbuzali** [comment]
@cangencer shall we close this, since 3.2.1 is already released?

**Comment by cangencer** [comment]
This has been resolved in 4.0
