### ISSUE TITLE
[j.u.s] Provide a map name for DistributedCollectors.toIMap

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast-jet#174]
`DistributedCollectors.toIMap` dumps result to map with autogenerated name.
 which not very easy to reference. Of course one can `map.getName()` but in management center it's not very convenient.
Provide a method allows to specify map name.

**Comment by viliam-durina** [comment]
Will be fixed in 0.4, see #308

**Comment by gAmUssA** [comment]
@viliam-durina is it backward compatible? do we still support random names if name isn't specified?

**Comment by viliam-durina** [comment]
No, the user must provide a map name, which may be a random one. We decided this, so that it is more clear to the user that a new map/list is created in the cluster, that isn't garbage collected as the one created with `toList()`, which returns plain java collection.
