### ISSUE TITLE
Adjust default parallelism of map source and sink

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1750]
Currently map source and sink default to max parallelism because they're cooperative, but it's not clear if this is optimal for both source & sink. Especially in the sink case having too large parallelism can lead to less batching and more operations overall.

**Comment by gurbuzali** [comment]
@cangencer  should be closed by https://github.com/hazelcast/hazelcast-jet/pull/1774 ?

**Comment by cangencer** [comment]
Yes fixed by #1774
