### ISSUE TITLE
Expose readFileFn from SourcesProcessors

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast-jet#1772]
Hi,

While digging into S3 connector, I've found similar issue that appeared in text source - all of them just emits (entry, line) pairs, without any stateful mapping possible. Of course, next transformation can be `mapStateful` or `mapUsingContext`, but then we are not sure about line order. This becomes important with dealing with CSV / TSV Files.

What's good in this, is that ReadFilesP already have `readFileFn` parameter, however it's not exposed directly in the API of `SourceProcessors.readFilesP()`. Adding overload of this function will easily allow us to parse CSV / TSV, as mapper (eg SimpleFlatMapper) can be used inside this function.

Same thing can be done with S3 processor, which also lacks possibility of contextual reading.

**Comment by TomaszGaweda** [comment]
FYI, if there isn't any issue with idea, I will prepare PR shortly

**Comment by viliam-durina** [comment]
That function will have to be stateful to handle CSV. It means that you will have to clone it for each processor.

Btw we work on adding an ordering guarantee to jet. Though I'm not sure it will make it to the next version because the prototype we have right now harms throughput more than we like.

**Comment by TomaszGaweda** [comment]
@viliam-durina Why cloning for each processor? Isn't it always executed on one node, one thread?

**Comment by viliam-durina** [comment]
Not if local parallelism is > 1

**Comment by TomaszGaweda** [comment]
Yeah, true. Simplified version could just read the whole file, like current plain File Processor - even if local parallelism > 1, then all is read by each thread by invoking `Files.lines()`.

**Comment by TomaszGaweda** [comment]
@cangencer @viliam-durina I've started implementing this feature, but I have one question - should we have 2 overloaded methods readFilesP in SourceProcessors and change in FileSourceBuilder that uses sometimes first method, sometimes second, depending on the fact if user provided charset or readFileFn? Or maybe it would be enough to change function in SourceProcessors (for 4.x it's ok to break backward compatibility), but just make FileSourceBuilder more flexbile?

**Comment by cangencer** [comment]
@TomaszGaweda It's fine just to have one method in readFilesP, also for processors classes we don't have BW-compatibility guarantees between minor versions.
