### ISSUE TITLE
Ability to add custom MetricsPublishers

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast-jet#1773]
Hello there,

since Service API was hidden, user cannot add their own metrics publishers in any way. This becomes blocker issue for upgrade for some applications, as they depend on gathering metrics into custom systems (eg. graphana or other).

While it's understandable that custom metrics publishers won't have optimizations like Management Center Publisher, they still will be very helpful. Integration via JMX is not reliable, as it won't catch all the metrics (they are published only for the time of the job; we can use getJobMetrics() after execution, but it's desirable to have them also during the job execution) and it's quite complex.

The easiest way would be to expose MetricsPublisher interface and allow to add them in `MetricsConfig`

**Comment by TomaszGaweda** [comment]
Kindly asking for opinions from @jbartok (author of new and shiny user metrics) and @jerrinot  (we spoke about our way of gathering metrics on a call). Maybe there is some other solution we can use, but we don't know yet ;) I think exposing MetricsPublisher is the easiest and not OP way (you cannot optimize it well, but at least you have a chance to get them if it's necessary).

**Comment by cangencer** [comment]
@TomaszGaweda are you talking about 4.0 here or 3.2?

**Comment by cangencer** [comment]
In 4.0 you can do it like this:

```
ConfigAccessor.getServicesConfig(jetConfig.getHazelcastConfig())
                      .addServiceConfig(new ServiceConfig())
```
in the `init` method on your custom service:
```
MetricsService metricsService = nodeEngine.getService(MetricsService.SERVICE_NAME);
metricsService.registerPublisher(..)
```

For now this is internal API only, but there has been some talk of making it possible to add additional publishers.

**Comment by TomaszGaweda** [comment]
@cangencer Thank you for your response, it' very helpful! 

I'm talking about current 4.0-snapshot.  In 3.2 MetricsPublishers are part of "impl" package, yet still public and you can plug-in easily if you want.. a bit hacky, I can confirm. I should have raise this issue long time ago, when we started using Jet and saw this requirement ;)

`ConfigAccessor` is a `@PrivateApi`, so it's possible it will be changed in the future, but as a workaround it should work nicely (I will test today).

> there has been some talk of making it possible to add additional publishers.
Should I then close this issue or it would be used for tracking?

**Comment by cangencer** [comment]
I would suggest to open an issue in https://github.com/hazelcast/hazelcast as the metrics implementation has been moved there from Jet.
