### ISSUE TITLE
Remove references to Hazelcast MapReduce in manual

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1799]
Hazelcast MapReduce is being removed completely. All references in references manual and code should be removed.

**Comment by eminn** [comment]
Closing this since I couldn't be able find any occurrence which mentions the Hazelcast Map Reduce.

**Comment by Holmistr** [comment]
Reopening @eminn : https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#moving-mapreduce-tasks-to-hazelcast-jet

**Comment by eminn** [comment]
@Holmistr then it should be an issue on the IMDG reference manual repository,  not on the Jet repository. My comment is regarding to the Jet Reference Manual.

**Comment by Holmistr** [comment]
Ok, no problem for me. Created https://github.com/hazelcast/hazelcast-reference-manual/issues/794 
Closing.
