### ISSUE TITLE
need decoder configuration

### ISSUE THREAD

**Issue by ppsnumi** [hazelcast/hazelcast-jet#1808]
Hi~

I use Hazelcast jet but have some problem using file.

some error meet when analysis my web server log using jet that's "MallformedInputException".

hazelcast jet using java's "Files.lines" but Files.lines set default throw Exception for deencoding error.

stackoverflow context:
https://stackoverflow.com/questions/26064689/files-lines-to-skip-broken-lines-in-java8

'Pipeline p = Pipeline.create();
p.drawFrom(Sources.filesBuilder("some target path").build()) //<- here'

jet provide change to chance decoding override or self logic read line by line in file(does not using Java's Files.lines).

Large web log(500MB over) and large other log file must throw MallformedInputException in my environment.

**Comment by cangencer** [comment]
You can use `FileSourceBuilder.charset()` to set the encoding. Does that fix the issue? What's the malformed input?

**Comment by ppsnumi** [comment]
Sources.filesBuilder("PATH").charset(Charset.forName("EUC-KR")).build() or  Sources.filesBuilder("PATH").charset(Charset.forName("UTF-8")).build() throw same error.

this error throwing java's File.lines not hazelcast jet's FileSourceBuilder.

**Comment by cangencer** [comment]
Is there any chance you can cleanup the file before processing it? Other option is to write a custom source using SourceBuilder API. For 4.0, we're going expose readFileFn so you should be able to customize the read function. See also #1772.

**Comment by cangencer** [comment]
You can now supply your own readFileFn to work around this issue: https://github.com/hazelcast/hazelcast/issues/15671
