### ISSUE TITLE
com.hazelcast.jet.impl.connector.JmsIntegrationTest.stressTest_exactlyOnce_xa_forceful

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1844]
http://jenkins.hazelcast.com/job/jet-oss-pr-builder/1815/testReport/junit/com.hazelcast.jet.impl.connector/JmsIntegrationTest/stressTest_exactlyOnce_xa_forceful/

Stacktrace:
```
counts: {0=1, 1=1, 2=1, 3=1, 4=1, 5=1,...``

**Comment by viliam-durina** [comment]
According to the logs it seems that ActiveMQ delivered an acknowledged item again. I added more logging in #1848 to be sure should it happen another time. If we confirm it's ActiveMQ's issue, the only remedy probably is to use a mock JMS broker, one can be found added and removed in the commits of #1804.

**Comment by olukas** [comment]
Failed also in http://jenkins.hazelcast.com/job/jet-oss-master-ibm-jdk8/141/
