### ISSUE TITLE
Support from/to basedir for PythonServiceConfig

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#1899]
This code

```
new PythonServiceConfig().setBaseDir("/xxx")
```

requires the base directory to be the same on the source (Job submit) and target (Job execute) machines.

This can be difficult to achieve on containerised machines.

It would be useful to be able to specify different directories.

**Comment by mtopolnik** [comment]
I'm not 100% sure I understand the exact issue, but the directory you specify in `setBaseDir` is not supposed to exist anywhere but your local filesystem. It is copied from there to the Jet cluster when you run the job.

**Comment by neilstevenson** [comment]
_User error_ 

I didn't understand this, the sample code I was using had a hardcoded path
