### ISSUE TITLE
More Jet nodes started in daemon mode overwrite the same output file

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1964]
In case when more Jet nodes are started by `jet-start` in daemon mode then they overwrite the same log file. It means log is available only for one of those nodes.

We should allow to configure different name of log file for each node. It is currently impossible since `$JET_LOG` is rewritten even if it is configured outside of script.

**Comment by cangencer** [comment]
Do you mean in daemon mode for the .out files? Would attaching timestamp/date to the filename help?

**Comment by olukas** [comment]
Yes, I mean `hazelcast-jet.out`. I think that attaching timestamp will just reduce the probability of hitting the problem - in case if more nodes will start in the same time then they still use the same file.

When I think about it seems that it can be fixed by change `> "$JET_LOG"` to `>> "$JET_LOG"` in line https://github.com/hazelcast/hazelcast-jet/blob/eff5e7ed1f14d90ce3662ac1b60a8199d0d4ef8e/hazelcast-jet-distribution/src/bin-filemode-755/jet-start#L36
Then log should be appended by all nodes (the same as it currently behaves for non-daemon mode and logging to `hazelcast-jet.log`) and not rewritten as it is now. WDYT?

**Comment by cangencer** [comment]
That means the .out file will grow indefinitely and never deleted on a restart and it will be hard to find the logs for the latest start (for example, if the server failed to start for some reason..). I think that's the main use case for that file, otherwise you have the rolling file logs as well.

**Comment by olukas** [comment]
Ok, solution with `>>` is not appropriate. 

Why do we not allow to configure some log file name per node? e.g. by setting some option like `--daemon-file-name`? In case it will be used then its value can be used otherwise it can fallback to current `$JET_LOG`.

**Comment by cangencer** [comment]
It would mean additional parameter parsing. I think just adding timestamp to the end of the filename should be enough.

**Comment by olukas** [comment]
It is not completely correct fix - it only decreasing probability that this will happen. On the other hand, the chance that it will happen with timestamp is pretty low. It can be probably considered as sufficient solution.
