### ISSUE TITLE
When originally first Jet instance dies, client can no longer connect to the cluster

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast-jet#1984]
1. Start Jet with `bin/jet-star`
2. Start it again, they form a cluster
3. Kill the first Jet

Now using `jet submit` the client can no longer connect to the remaining 2nd Jet instance.

**Comment by cangencer** [comment]
https://github.com/hazelcast/hazelcast-jet/blob/master/hazelcast-jet-distribution/src/root/config/hazelcast-client.yaml needs updating
