### ISSUE TITLE
Provide clear information about requirements.txt for Python

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1990]
Provide clearer information in Reference Manual about content of `requirements.txt` file which is used by Python. We should describe:
* how to use it with more packages - what is delimiter for them (new line)
* how to specify particular version of package

Maybe we can provide 2 lines snippet of `requirements.txt` example.

**Comment by mtopolnik** [comment]
It is a standard and we don't interpret it but pass it directly to `pip`:

https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format

**Comment by olukas** [comment]
Thanks for clarification, closing.
