### ISSUE TITLE
Add jvm.options file to config

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#2054]
Add a `jvm.options` file to config folder which can be automatically read as JVM properties, so that you are not forced to rely on `JAVA_OPTS` env variable.

**Comment by inspire99** [comment]
@cangencer : I would like to work on this.

**Comment by cangencer** [comment]
@inspire99 feel free to go ahead. I was thinking something along the lines of what's provided by Elasticsearch: https://github.com/elastic/elasticsearch/blob/master/distribution/src/config/jvm.options

**Comment by Holmistr** [comment]
Hi @inspire99 , just checking in whether there's something we could do to help. Just to make sure to keep you going :)

**Comment by frant-hartm** [comment]
Implemented in #2349
