### ISSUE TITLE
JobConfig.addPackage should fail-fast for non-existing package

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2068]
In case when non-existing package (i.e. package which is not on classpath) is passed to `JobConfig.addPackage` then we should throw Exception rather than ignore. If user use this method then they probably set incorrect package by mistake. We should be proactive and do not send job like this to cluster.

**Comment by viliam-durina** [comment]
I don't agree. This would be an unintuitive special case. It's similar to `addAll(emptyList())` throwing or if `a + b` throwing if `b` is zero.

Consider also the case that the user somehow iterates the directories and adds them all, but some of the directories happens to be empty - with this change he would have to check for it or catch and ignore the exception.

**Comment by cangencer** [comment]
I agree with @viliam-durina here, I don't think it's needed. A package is like a wildcard, if it doesn't match anything then it won't.

**Comment by olukas** [comment]
I'm closing this since it is expected behavior. I added test for it in https://github.com/hazelcast/hazelcast-jet/pull/2069

**Comment by viliam-durina** [comment]
Btw, in unix shell, `ls *` fails if there's no file in the directory. But not on windows :).
