### ISSUE TITLE
add new azure plugin to Jet distribution

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#2074]
Add Hazelcast azure plugin to Jet distribution: https://github.com/hazelcast/hazelcast-azure/releases/tag/v2.0 (perhaps even shade it, if it's small enough)

**Comment by eminn** [comment]
@mesutcelik Do you have any plans to include azure plugin with the hazelcast distribution like AWS and GCP ?

**Comment by mesutcelik** [comment]
@alparslanavci would send a PR to hazelcast-all so it will be included

**Comment by eminn** [comment]
@mesutcelik never mind, I've just forgot that we are not depending on `hazelcast-all` so it makes sense to add it to our JAR independent from that.
