### ISSUE TITLE
Tumbling window gives unpredictable results

### ISSUE THREAD

**Issue by alenbec** [hazelcast/hazelcast-jet#2103]
Hello again,

I've come across this issue with Jet. Maybe my understanding of tumbling windows is not so good so please bear with me if I'm missing something.

I'm using `IMap` as a streaming source and I've defined tumbling window of 100ms. Streaming is set to `START_FROM_OLDEST` and TTL is set to infinite (0) so this should grab all items already in journal when pipeline starts, right?

In the examples below I'm inserting records in source map and printing source and sink sizes each second. Given that window size is 100ms, count of both maps should be equal or in the worst case sink should be only 1 item behind the source, right?

If I insert only one record using `insert(sourceMap, 1)` (with other inserts commented out), the item will never reach the end of the pipeline:

```
09:22:29 Source: 1	Sink: 0
09:22:30 Source: 1	Sink: 0
09:22:31 Source: 1	Sink: 0
09:22:32 Source: 1	Sink: 0
09:22:33 Source: 1	Sink: 0
09:22:34 Source: 1	Sink: 0
09:22:35 Source: 1	Sink: 0
09:22:36 Source: 1	Sink: 0
09:22:37 Source: 1	Sink: 0
09:22:38 Source: 1	Sink: 0
09:22:39 Source: 1	Sink: 0
09:22:40 Source: 1	Sink: 0
09:22:41 Source: 1	Sink: 0
09:22:42 Source: 1	Sink: 0
...
```

If I insert 20 records with `insert(sourceMap, 20)` (and other inserts commented out), there is huge delay in processing of events at the beginning and last two items will never reach the end of the pipeline so only 18 will be processed:

```
09:47:59 Source: 1	Sink: 0
09:48:00 Source: 2	Sink: 0
09:48:01 Source: 3	Sink: 0
09:48:02 Source: 4	Sink: 0
09:48:03 Source: 5	Sink: 0
09:48:04 Source: 6	Sink: 0
09:48:05 Source: 7	Sink: 5
09:48:06 Source: 8	Sink: 5
09:48:07 Source: 9	Sink: 5
09:48:08 Source: 10	Sink: 5
09:48:09 Source: 11	Sink: 5
09:48:10 Source: 12	Sink: 5
09:48:11 Source: 13	Sink: 11
09:48:12 Source: 14	Sink: 12
09:48:13 Source: 15	Sink: 13
09:48:14 Source: 16	Sink: 13
09:48:15 Source: 17	Sink: 15
09:48:16 Source: 18	Sink: 15
09:48:17 Source: 19	Sink: 17
09:48:18 Source: 20	Sink: 18
09:48:19 Source: 20	Sink: 18
09:48:20 Source: 20	Sink: 18
09:48:21 Source: 20	Sink: 18
09:48:22 Source: 20	Sink: 18
09:48:23 Source: 20	Sink: 18
...
```

If I run `insert(sourceMap, Integer.MAX_VALUE)` (with other inserts commented out), pipeline will be, as with the previous case, greatly behind the source at the beginnig. The difference between soruce and sink sizes eventually reduces but sink size count would never catch source size count:

```
09:29:42 Source: 1	Sink: 0
09:29:43 Source: 2	Sink: 0
09:29:44 Source: 3	Sink: 0
09:29:45 Source: 4	Sink: 0
09:29:46 Source: 5	Sink: 0
09:29:47 Source: 6	Sink: 0
09:29:48 Source: 7	Sink: 3
09:29:49 Source: 8	Sink: 5
09:29:50 Source: 9	Sink: 5
09:29:51 Source: 10	Sink: 5
09:29:52 Source: 11	Sink: 5
09:29:53 Source: 12	Sink: 5
09:29:54 Source: 13	Sink: 11
09:29:55 Source: 14	Sink: 12
09:29:56 Source: 15	Sink: 13
09:29:57 Source: 16	Sink: 13
09:29:58 Source: 17	Sink: 15
09:29:59 Source: 18	Sink: 15
09:30:00 Source: 19	Sink: 17
09:30:01 Source: 20	Sink: 18
09:30:02 Source: 21	Sink: 19
09:30:03 Source: 22	Sink: 19
09:30:04 Source: 23	Sink: 21
09:30:05 Source: 24	Sink: 22
...
09:37:18 Source: 457	Sink: 452
09:37:19 Source: 458	Sink: 456
09:37:20 Source: 459	Sink: 457
09:37:21 Source: 460	Sink: 457
09:37:22 Source: 461	Sink: 457
09:37:23 Source: 462	Sink: 457
...
```

Notice how in this and previous case sink starts getting items only after at least 7 records were put into source map.

What am I missing here?

Jet version: 3.2.2
Java 8
Windows 10 x64, 4 cores, 8 logical processor

```java
package org.example;

import com.hazelcast.config.EventJournalConfig;
import com.hazelcast.jet.Jet;
import com.hazelcast.jet.JetInstance;
import com.hazelcast.jet.function.PredicateEx;
import com.hazelcast.jet.pipeline.*;
import com.hazelcast.map.journal.EventJournalMapEvent;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import java.util.concurrent.Executors;

import static com.hazelcast.jet.aggregate.AggregateOperations.counting;
import static com.hazelcast.jet.function.FunctionEx.identity;
import static com.hazelcast.jet.pipeline.JournalInitialPosition.START_FROM_OLDEST;
import static java.lang.Thread.sleep;

public class Application {
    private static final DateFormat dtf = new SimpleDateFormat("HH:mm:ss");
    private static final String sourceMapName = "SOURCE_MAP";
    private static final String sinkMapName = "SINK_MAP";
    private static final int tumblingWindowSize = 100;

    public static void main(String[] args) throws Exception {

        JetInstance jet = Jet.newJetInstance();
        jet.getHazelcastInstance().getConfig().addEventJournalConfig(new EventJournalConfig()
                .setEnabled(true)
                .setMapName(sourceMapName)
                .setCapacity(1000)
                .setTimeToLiveSeconds(0));

        StreamSource<EventJournalMapEvent<Integer, String>> streamSource = Sources.mapJournal(
                sourceMapName,
                PredicateEx.alwaysTrue(),
                identity(),
                START_FROM_OLDEST);

        streamSource.setPartitionIdleTimeout(0);

        Pipeline p = Pipeline.create();
        p.drawFrom(streamSource)
                .withIngestionTimestamps()
                .groupingKey(EventJournalMapEvent::getKey)
                .window(WindowDefinition.tumbling(tumblingWindowSize))
                .aggregate(counting())
                .drainTo(Sinks.map(sinkMapName));

        Map<Integer, String> sourceMap = jet.getMap(sourceMapName);
        Map<Integer, Long> sinkMap = jet.getMap(sinkMapName);

        printSize(sourceMap, sinkMap);

        // one inserted record will never reach the end of pipeline
        //insert(sourceMap, 1);

        // inserting only 20 records...
        // huge difference between source and sink size can be seen at the beginning,
        // it will eventually reduce but sink will never catch up with source;
        // last 2 items will never reach the end of the pipeline
        //insert(sourceMap, 20);

        // "infinite" stream of records.. again similar result as with 20 items
        insert(sourceMap, Integer.MAX_VALUE);

        jet.newJob(p).join();
    }

    private static void insert(Map<Integer, String> sourceMap, final int count) throws Exception {
        Executors.newSingleThreadExecutor().submit(() -> {
            try {
                int i = 0;
                while (i++ < count) {
                    sourceMap.put(i, Integer.toString(i));
                    sleep(1000);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        });
    }

    public static void printSize(Map<Integer, String> sourceMap, Map<Integer, Long> sinkMap) {
        Executors.newSingleThreadExecutor().submit(() -> {
            try {
                while(true) {
                    print("Source: " + sourceMap.size() + "\tSink: " + sinkMap.size());
                    sleep(1000);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        });
    }

    private static void print(String output) {
        System.out.println(dtf.format(new Date()) + " " + output);
    }
}


```

**Comment by viliam-durina** [comment]
You've hit a second most common issue: sparse events: if the events stop, the time stops. If you have no event for 10 seconds and you have a 1-second window, the window will be only emitted after 10 seconds when the next event triggers the clock. And this has to happen in each partition: the partition with "sparsiest" events will determine the overall latency.

I recommend you to read this from our new site: https://jet-start.sh/docs/architecture/event-time-processing

In your example, the `mapJournal` source has local parallelism of 2. IMap has, by default, 271 partitions. You insert 1 item per second. Each of those items makes it into one of the 271 partitions. So on average, two items in each partition are 271 seconds apart. But the `mapJournal` source, exactly because of this issue, treats all its partitions as one partition, therefore it acts as if there were 2 partitions. If you add `peek()` after the `withIngestionTimestamps()`, you will see that each time the other processor emits a watermark, the number of items in the sink jumps up. This is because now watermarks from both local processors are coalesced into newer watermark.

For your test code, add `setLocalParallelism(1)` after the `withIngestionTimestamp()`. For production, ensure you have enough traffic in each partition. If you don't, you can add heartbeat events.

**Comment by alenbec** [comment]
How would one properly implement heartbeat logic?

I was testing a bit the following logic by calling `heartBeat(sourceMap, p, 1000);` and it seems it is working ok for this use case. 
I also added `.filter(e -> e.getKey() > 0)` to pipeline right after `.withIngestionTimestamps()` to avoid collecting heartbeat events.  

Is this OK or is there a better/more appropriate way of doing this?

```java
private static void heartBeat(final IMap<Integer, String> sourceMap, final Pipeline pipeline, final int interval) {
    Executors.newSingleThreadExecutor().submit(() -> {
        Vertex v = pipeline.toDag().getVertex("mapJournalSource(" + sourceMap.getName() + ")");

        if(v == null) {
            throw new RuntimeException("Vertex not found.");
        }

        int mapJournalLocalParallelism = v.getLocalParallelism();
        if(mapJournalLocalParallelism == Vertex.LOCAL_PARALLELISM_USE_DEFAULT) {
            mapJournalLocalParallelism = v.getMetaSupplier().preferredLocalParallelism();
        }

        if(mapJournalLocalParallelism < 0) {
            throw new RuntimeException("Unable to determine local parallelism of vertex.");
        }


        try {
            while (true) {
                for(int i=0; i<mapJournalLocalParallelism; i++) {
                    sourceMap.set(-i, "");
                }
                sleep(interval);
                for(int i=0; i<mapJournalLocalParallelism; i++) {
                    sourceMap.delete(-i);
                }
                sleep(interval);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    });
}
```

Also it would be great it Jet would provide a way to configure heartbeat out of the box so one would not have to write this (what I consider to be) workaround.

**Comment by viliam-durina** [comment]
A heartbeat has to be generated in each partition. Setting a key for `0..-n` where `n` is the local parallelism isn't enough, I guess it works in your case just by coincidence, with multiple members it will not work.

Here's the code. It first generates a set of partition keys, one for each partition. The keys are negative. The it uses `putAll` to insert them all. It's not needed to remove them, even if you overwrite with the same value, it will get added to the journal.

```java
Executors.newSingleThreadExecutor().submit(() -> {
    try {
        // find partition key for each partition
        PartitionService pService = instance.getHazelcastInstance().getPartitionService();
        int partitionCount = pService.getPartitions().size();
        Map<Integer, String> heartbeats = new HashMap<>(partitionCount);
        BitSet seenPartitions = new BitSet(partitionCount);
        for (int k = 0; heartbeats.size() < partitionCount; k--) {
            int partitionId = pService.getPartition(k).getPartitionId();
            if (!seenPartitions.get(partitionId)) {
                seenPartitions.set(partitionId);
                heartbeats.put(k, "");
            }
        }

        while (true) {
            sourceMap.putAll(heartbeats);
            Thread.sleep(interval);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
});
```

We consider adding a way to generate watermarks based on wall-clock time. With it the time will pass even when there are no events. However if your publishers lag or if your job is down for some time and then restarts, all events in the meantime will be dropped as late.

With custom heartbeat generator you can control where the heartbeat is gets generated. Ideally the same process that generates the actual events should also generate heartbeats. This way you can also minimize the latency and you don't have to rely on the _allowed lag_. However, if you have multiple generating processes, it won't work perfectly. The optimal solution depends very much on your architecture.

**Comment by alenbec** [comment]
Thanks, that’s exactly what I was trying to achieve!
