### ISSUE TITLE
Adding a JDK class to JobConfig causes NPE

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast-jet#2107]
This code

```java
public class JetTest {
    public static void main(String[] args) {
        Pipeline pipeline = Pipeline.create();

        pipeline.readFrom(TestSources.items(1))
                .writeTo(Sinks.logger());

        JetInstance jetInstance = Jet.bootstrappedInstance();
        JobConfig jobCfg = new JobConfig().addClass(Map.class);
        jetInstance.newJobIfAbsent(pipeline, jobCfg);
    }
}
```
fails with an NPE due to `Map.class.getClassLoader()` returning null. If the classloader is null, we should raise a custom exception telling the user not to add JDK classes to the job.

**Comment by nfrankel** [comment]
> If the classloader is null, we should raise a custom exception telling the user not to add JDK classes to the job.

Open question: is this assumption correct in the context of JPMS modules (Java 9+)?

**Comment by mtopolnik** [comment]
The Javadoc of `Class.getClassLoader()` states:

>Some implementations may use null to represent the bootstrap class loader. This method will return null in such implementations if this class was loaded by the bootstrap class loader.
