### ISSUE TITLE
Enhancement: add toString() to com.hazelcast.jet.config.JobConfig

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#2126]
On 4.0, the JobConfig class does not provide a `toString()`, so defaults to the useless object print.

It would be useful to be able to print the job config, rather than extract the individual field

**Comment by SapnaDerajeRadhakrishna** [comment]
I would like to take this issue @Holmistr

**Comment by Holmistr** [comment]
Hey @SapnaDerajeRadhakrishna , glad to see you here! :tada: I'm assigning you the issue. I guess you have all the information you need for starting working on it. Thank you very much for your effort and looking forward to your contribution! :)
