### ISSUE TITLE
Jet node configured programatically and Jet node configured by config file do not form cluster

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2181]
In case when some nodes are configured programatically and some other nodes are configured by config file passed through system property then they will not form cluster together. 2 clusters are created - one for programatically configured nodes and one for nodes configured by config file.

Similar configuration works correctly with IMDG.

**Reproducer**:
Following can be used for programatically confugured nodes:
```
JetConfig config = new JetConfig();
config.getHazelcastConfig().setClusterName("my-cluster");
Jet.newJetInstance(config);
```
Following can be used for nodes configured by system property:
```
System.setProperty("hazelcast.config", "/home/user/hz-jet.yaml");
Jet.newJetInstance();
```
where content of `/home/user/hz-jet.yaml` is:
```
hazelcast:
    cluster-name: my-cluster
```
If you start each of them twice you will see 2 clusters (with 2 nodes) with the same cluster name. I would expect they should form 1 cluster with 4 nodes.

**Comment by cangencer** [comment]
you need to set them to use the same multicast port as well, or use another discovery

**Comment by gurbuzali** [comment]
see https://github.com/hazelcast/hazelcast-jet/blob/master/hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfig.java#L54

**Comment by olukas** [comment]
Ok. It was little confusing since it worked for IMDG but I'm see it now. It's based on the fact that default values are not the same for them since one default value comes from Jet and another one from IMDG. 

Thanks for explanation. Closing.
