### ISSUE TITLE
Job stuck when going to passive state

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#2202]
Failed in soak test run. 
Relevant log files:
- 
[hazelcast-jet-108.log](https://github.com/hazelcast/hazelcast-jet/files/4504210/hazelcast-jet-108.log)
[hazelcast-jet-109.log](https://github.com/hazelcast/hazelcast-jet/files/4504213/hazelcast-jet-109.log)
[hazelcast-jet-110.log](https://github.com/hazelcast/hazelcast-jet/files/4504207/hazelcast-jet-110.log)
[hazelcast-jet-111.log](https://github.com/hazelcast/hazelcast-jet/files/4504214/hazelcast-jet-111.log)

There are 14 parallel jobs running. The tests were about to stop the cluster (using `sudo initctl stop hazelcast-jet-isolated`). This caused that terminal snpashot was enqueued. The master member (with logs in the 108 file) initiated all snapshots and terminated jobs that have no snapshotting enabled. All snapshots succeeded on all members, except for the job `Dynamic-StatefulMapTest` on the last member (with logs in file 111). For that job the snapshot should have the ID=2978.

Excerpts from master logs (file 108):
```
11:05:09,472 DEBUG || - [MasterSnapshotContext] hz.stoic_driscoll.cached.thread-11 - Starting snapshot 2978 for job 'Dynamic-StatefulMapTest', execution 0433-9ed9-c519-0006, flags: terminal=yes,export=no, writing to: null
```

On all members except the stuck member the snapshot phase 1 completed quickly (here the logs from the member 109):
```
11:05:09,526 DEBUG || - [SnapshotPhase1Operation] hz.goofy_aryabhata.jet.cooperative.thread-4 - Snapshot 2978 phase 1 for job 'Dynamic-StatefulMapTest', execution 0433-9ed9-c519-0006 finished successfully on member
```

However on member 111, it finished 30 seconds later:
```
11:05:39,478 DEBUG || - [SnapshotPhase1Operation] hz.competent_taussig.jet.cooperative.thread-5 - Snapshot 2978 phase 1 for job 'Dynamic-StatefulMapTest', execution 0433-9ed9-c519-0006 finished successfully on member
```

There is no event logged when the phase 1 starts on member. This led to all 4 members to wait for the outstanding members and all were prevented from shutting down (it was a graceful shutdown).

I reckon that the shutdown would be stuck forever, but 30 seconds is the sleep time in the `RemoteControllerClient`, [see here](https://github.com/hazelcast/hazelcast-jet-ansible-tests/blob/b2acbc7c0c76a3827e7ea0f69221040e0ed27200/remote-controller-client/src/main/java/com/hazelcast/jet/tests/remote/RemoteControllerClient.java#L98). After 30 seconds `sudo initctl start hazelcast-jet-isolated` is called for all members. This somehow _woke up_ the lagging snapshot on member 111 and that and all other members shut down.

I wasn't able to reproduce the issue nor find a root cause by analyzing the code. PR #2201 adds logging of phase 1 start on member, but I guess the member received and handled the `SnapshotPhase1Operation`. One suspicion is that on member 111, just 34 milliseconds before going to passive phase 2 of the previous snapshot for the `Dynamic-StatefulMapTest` completed on member. But the master successfully started the terminal snapshot for this job (because we know it succeeded on other members).

**Comment by cangencer** [comment]
Closing this as it wasn't reproducible.
