### ISSUE TITLE
Treat nulls as a valid value when doing grouping

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#2361]
When doing a grouping, `null` currently throws an exception as follows:

```
Caused by: com.hazelcast.jet.JetException: Null key from key extractor, 
edge: between("avroFilesSource(/Users/can/tmp/avro/*)", "group-and-aggregate-prepare").partitioned(?)
```

This is arbitrary and `null` should just treated as another value.

**Comment by mtopolnik** [comment]
I'm not so sure we should change this, it will probably open a rabbithole of cascading changes needed. Eventually nulls will break something, for example in sinks, and we'll need workarounds or we'll have an even worse situation where we'll have to document where nulls are or aren't allowed. I prefer the user defining an explicit null sentinel value.

**Comment by cangencer** [comment]
Regarding this, Spark is able to handle nulls without explicit mapping. I agree it may end up being a complex change though.
