### ISSUE TITLE
Postgres cdc connector is missing data inserted during job start

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2371]
When job with Postgres cdc connector is started and in the same time some data are inserted into Postgres then some of them are not observed by connector. It means we lost data.

Tested with postgres 11.

**Comment by jbartok** [comment]
Moving milestone to 4.3, we will be able to solve it only after Debezium side is fixed (https://issues.redhat.com/browse/DBZ-2288).

**Comment by jbartok** [comment]
This is solved, we are on fixed Debezium version of **1.2.1.Final**.
