### ISSUE TITLE
Update Hazelcast IMDG version to 4.0.2

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#2399]

**Comment by TomaszGaweda** [comment]
BTW. Would be great if Jet could allow such small version mismatch. We wanted to upgrade IMDG version because one of bugs where fixed in it, but cannot because Jet raises exception

**Comment by cangencer** [comment]
We used to allow this, but since Jet uses so many internal APIs of Hazelcast it was quite difficult, if not impossible t to ensure everything will work with every different Hazelcast version. Maybe the check could be disabled via a property. The check is in `Jet.assertHazelcastVersion()` class and could check a system property before running it.
