### ISSUE TITLE
Jet submit should log successful submission

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hazelcast-jet#2426]
It would be useful to print a confirmation of successful job submission (maybe with job id), especially for jobs which don't print anything to the user console.

Currently, a log is printed that the job is being submitted:

```
Submitting JAR '....' with arguments [...]
```

Then I need to check if the job is running by running `bin/jet list-jobs`

Possible output:
```
00:00:01.000 JobName id=... status=STARTING
00:00:02.000 JobName id=... status=STARTING
00:00:03.000 JobName id=... status=RUNNING
```

**Comment by viliam-durina** [comment]
Not sure we can do this. We don't submit a job, we execute a JAR and whichever code is in it. It might submit no job or it might submit multiple jobs. Maybe the bootstrapped instance can log every call to `newJob`, but i don't like the idea very much. The JAR should print it maybe..

**Comment by frant-hartm** [comment]
It is certainly possible to do something similar to the following in the main method

```
        while (job.getStatus() == JobStatus.NOT_RUNNING || job.getStatus() == JobStatus.STARTING) {
            log.info("PetClinicIndexJob status=" + job.getStatus());
            Thread.sleep(1000);
        }

        log.info("PetClinicIndexJob status=" + job.getStatus());
```
but I think this is so common that we should provide it by default.

I think we can do two things:

1. in JetCommandLine log a successful completion of JetBootstrap.executeJar (this would not contain a job id, but it would tell you that the main method finished with no issues.
2. Log `newJob` just before it returns to the main method - this can include job id.

**Comment by cangencer** [comment]
I also find this a bit awkward when demoing, you submit but then there is no output or indication that job started.

**Comment by mtopolnik** [comment]
Definitely don't print in a loop, this is where the user would be using the "Return results to caller" feature and the loop printing would interfere with it.
