### ISSUE TITLE
Job doesn't fail if exception is thrown from mapUsingIMap stage

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2511]
In case when `mapUsingIMap` stage throws exception then job stops to process another items but it is not finished (it is still in a running state). This means users cannot detect that something went wrong. In correct behavior it should fail.

Use following pipeline to reproduce the issue:
```
Pipeline p = Pipeline.create();
p.readFrom(TestSources.itemStream(10))
        .withIngestionTimestamps()
        .mapUsingIMap("map", item -> "key", (item, value) -> {
            if (item.sequence() == 3) {
                throw new RuntimeException();
            }
            return item;
        }).setLocalParallelism(1)
        .writeTo(Sinks.logger());
```

**Comment by olukas** [comment]
Actually, it seems that it works correctly for Jet OS and fail only for Jet EE. Should this issue be moved to EE?

**Comment by viliam-durina** [comment]
It fails also in OS, the same way.

**Comment by viliam-durina** [comment]
This is the cause:
```java
        map.getAsync("k")
           .thenApply(v -> {throw new RuntimeException("foo");})
           .toCompletableFuture()
           .get();
```
It blocks in the `get` call.

The `CompletionStage` returned from `getAsync` improperly handles exceptions: if one is thrown, the returned future never completes. Will file an issue in IMDG.

**Comment by viliam-durina** [comment]
Filed an issue in imdg: hazelcast/hazelcast#17515
Will work on a workaround in Jet.
