### ISSUE TITLE
Register Potrable's ClassDefinition via SQL

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet#2613]
When I want to `INSERT` data into IMap I need to create a `MAPPING` first. However when I want to use Portable objects then I have to register a PortableClassDefinition first and I cannot do that via SQL. This renders SQL Insert unusable (for Portable objects)

**Comment by gierlachg** [comment]
It's unusable in the same way `java` serialization is unusable if you don't have class on the classpath.
You can use `json` if you are after no-prerequisite serialization format.

In theory we don't need `ClassDefinition` at all to write a record and infer it based on given columns. But I'm not sure if that's the best thing to do as `ClassDefinition`s are cached and we could easily end up with polluted and inconsistent cache across members.

**Comment by viliam-durina** [comment]
I think unless the user creates two mappings with the same `{factoryId, classId, version}` and different columns, it should be ok to derive the `ClassDefinition` from the DDL column list.

**Comment by jerrinot** [comment]
I believe (IMDG) SQL query does not work with JSON at all. 
So when you have an empty map then you can: 
1. Insert JSON, but then you cannot query it.
2. Query Portable, but we cannot insert it. 

![image](https://user-images.githubusercontent.com/158619/97187625-ea6bb480-17a2-11eb-9928-e1e424607262.png)

**Comment by viliam-durina** [comment]
You can insert portable. But if the map is empty (or possibly empty), you have to create it using DDL first.

**Comment by jerrinot** [comment]
how?

**Comment by viliam-durina** [comment]
how to issue ddl? See [here](https://github.com/hazelcast/hazelcast-jet/blob/ebe7391443ba66f826e57772040e7e60c4a6d6c2/hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlPortableTest.java#L155-L168), for example.
