### ISSUE TITLE
Hazelcast-jet job cannot be executed in parallel on multiple machines

### ISSUE THREAD

**Issue by xiaoqubb** [hazelcast/hazelcast-jet#2621]
I deployed a cluster with two machines and set the local parallelism, such as
```java
SinkBuilder.sinkBuilder ( tmpTarget.getName (), x -> new JdbcSinkContext(x, tmpTarget, tmpComContext))
    .<JsonObject>receiveFn(JdbcSinkContext::receive)
    .destroyFn(JdbcSinkContext::destroy)
    .preferredLocalParallelism(4)
    .build();
```
The system log is as follows
```
digraph DAG {
        "bs_result" [localParallelism=1];
        "bs_result_target" [localParallelism=4];
        "bs_result" -> "bs_result_target" [queueSize=1024];
}
```

It is expected that there will be 4 threads running in parallel on each machine, with a total of 8 threads running; however, in the real situation, only four threads will run in parallel on one machine, and the other will not run

Note: in the local test environment, it is expected that two machines each run four local threads, but in the production environment, as mentioned above, only four threads are running on one machine, and the other is not running. However, the cluster finds that there is no problem

**Comment by viliam-durina** [comment]
The number of threads will be 4 for each Jet instance, no matter whether they run on a single physical machine, or even inside a single JVM.

**Comment by xiaoqubb** [comment]
> The number of threads will be 4 for each Jet instance, no matter whether they run on a single physical machine, or even inside a single JVM.

However, it is actually allocated to one jet instance, and other jet instances are not running

**Comment by viliam-durina** [comment]
What do you mean by "other jet instances are not running"? Every member of the cluster will run 4 threads, regardless the members are on different hardware or a different JVM.

**Comment by xiaoqubb** [comment]
> What do you mean by "other jet instances are not running"? Every member of the cluster will run 4 threads, regardless the members are on different hardware or a different JVM.

digraph DAG {
        "bs_result" [localParallelism=1];
        "bs_result_target" [localParallelism=4];
        "bs_result" -> "bs_result_target" [queueSize=1024];
}
I have a cluster of three jet instances. "Other jet instances are not running" means that I submit tasks only run in one jet instance, but not in other jet instances synchronously.
As shown in the DAG diagram above, there should be 3 * 4 threads running synchronously. However, four threads are actually running in one jet instance, and other jet instances are idle and do not run the task.
When a jet instance is manually killed, one of the remaining two jet instances is randomly assigned to run the task again (4 threads), and the other jet instance is idle;
That is to say, only one task can be run on one jet instance at a time, and other jet instances can't use it

I don't know if you clear my expression, thank you!

**Comment by viliam-durina** [comment]
You have no distributed edge in your DAG. Maybe your source is non-distributed. That means that there are no data sent between members and two of the three members complete the execution immediately after starting and one member runs the job. You can use `rebalance()` operation to rebalance the data from the non-distribute source to all members.
