### ISSUE TITLE
Make the OR REPLACE option in the CREATE SNAPSHOT statement mandatory

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#2635]
The option is currently optional, but we always overwrite the snapshot if it already exists. It might seem too verbose, but this is how people expect the CREATE statements to work: to fail should they overwrite something. The error message must be specific and suggest that OR REPLACE must be used.

![image](https://user-images.githubusercontent.com/9109877/97732998-8c5b0c00-1ad7-11eb-9865-23c3727340a6.png)

Also check that the `DROP SNAPSHOT` statement throws if the snapshot doesn't exist or make that mandatory too.

**Comment by gierlachg** [comment]
I believe this one is already implemented. Can we close it @viliam-durina ?
