### ISSUE TITLE
Jet installs a custom logging handler that closes System.out from a shutdown hook

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast-jet#2649]
If we run this code:

```java
public class ShutdownTest {
    public static void main(String[] args) throws Exception {
        Runtime.getRuntime().addShutdownHook(new Thread("Shutdown") {
            public void run() {
                try {
                    for (int i = 0; i < 1_000_000; i++) {
                        System.out.println("Shutting down " + i);
                    }
                } catch (Throwable t) {
                    System.out.println("Error");
                }
            }
        });
        Jet.newJetInstance();
        System.out.println("Running");
    }
}
```

and then kill it gracefully (`SIGINT` or `SIGTERM`), it appears that the loop in the shutdown hook doesn't finish. Also, we can see that Jet's own shutdown hooks don't finish.

If we add this code after `Jet.newJetInstance()`:

```java
Field hooksField = Class.forName("java.lang.ApplicationShutdownHooks").getDeclaredField("hooks");
hooksField.setAccessible(true);
Map<Thread, Thread> hooks = (Map<Thread, Thread>)hooksField.get(null);
hooks.entrySet().removeIf(entry -> entry.getKey().getName().equals("Logging-Cleaner"));
```

then the problem disappears. This code forcibly removes the shutdown hook that `LogManager` added.

**Comment by gurbuzali** [comment]
btw if you replace `Jet.newJetInstance();` with `LogManager logManager = LogManager.getLogManager();` the issue disappears, although the log manager adds its shutdown hook. Somehow creating a Jet instance is triggering the issue.

**Comment by mtopolnik** [comment]
Yes, my guess would be some custom logger code we register with the log manager, but I couldn't find the cause.
