### ISSUE TITLE
OPTIONS in CREATE JOB does not support addClass

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2658]
Option `addClass` is not supported by `OPTIONS` for `CREATE JOB`. It means Jet server needs to have all used classes on classpath. I would expect that something like following should work:
```
CREATE JOB trades_ingestion
OPTIONS (
    addClass 'org.apache.kafka.connect.json.JsonDeserializer'
) AS ...
```

**Comment by gierlachg** [comment]
I think the decision to omit that option was deliberate - currently statements are parsed on the server and i don't think it will ever change. I would mark it as an inherent SQL limitation, unless @viliam-durina has another opinion on that.

**Comment by viliam-durina** [comment]
No, it's not inherent. In the future you'll be able to submit a custom SQL connector or maybe a user-defined function that you can use in SQL. But today it can't probably be used for anything - there's no SQL query that would need a custom class. Maybe the file sink - if you don't add the hadoop libs to members but want to submit them from the client. But it seems weird.

Also the future API for SQL will be JDBC (or ODBC or drivers for other languages). It would feel weird to submit java classes with JDBC...

Conclusion: it's not useful now, in the future we can rethink it.

**Comment by olukas** [comment]
Does it mean that if anyone want to use own deserializer (like `org.apache.kafka.connect.json.JsonDeserializer`) then they need to put them on Jet classpath (i.e. they need to know it and put it there in the time when Jet cluster is started)?

**Comment by viliam-durina** [comment]
Yes. I was actually thinking that it would be no harm to support it, but we technically can't: The statement isn't parsed on the client, it's sent as a String to the member. So the client doesn't know which classes to send along with the statement.

**Comment by olukas** [comment]
It seems like inconvenient limitation. Can we at least document it somewhere?

Moreover our current documentation uses `org.apache.kafka.connect.json.JsonDeserializer`. Since it's not part of `hazelcast-jet-kafka` jar we should also add an information to the example here (https://github.com/hazelcast/hazelcast-jet/blob/master/site/docs/sql/00-intro.md) about which library needs to be added on classpath.

**Comment by viliam-durina** [comment]
I documented it: https://github.com/hazelcast/hazelcast-jet/pull/2665/files#diff-91d5111ad8a6bdfb32640b5ad7110965e4c53d95582f7ff32ef24c8ffd1aca39R50-R52

#2679 removes the need for `JsonDeserializer`.
