### ISSUE TITLE
[javadoc] default local parallelism for Kafka sources is ambiguous

### ISSUE THREAD

**Issue by hhromic** [hazelcast/hazelcast-jet#2663]
Hi, first of all thanks for Hazelcast Jet. It is a really well-engineered product, kudos!

Currently, the official javadoc for the Kafka sources states two different default local parallelism values.

First time:

https://github.com/hazelcast/hazelcast-jet/blob/90d17d6be91cf4e7332059b47e5a9cadefd8ee3b/extensions/kafka/src/main/java/com/hazelcast/jet/kafka/KafkaSources.java#L65-L66

Second time further down below at the end:

https://github.com/hazelcast/hazelcast-jet/blob/90d17d6be91cf4e7332059b47e5a9cadefd8ee3b/extensions/kafka/src/main/java/com/hazelcast/jet/kafka/KafkaSources.java#L115-L116

I went to the source code to find out what is the actual default local parallelism being used, which is `4`:

https://github.com/hazelcast/hazelcast-jet/blob/90d17d6be91cf4e7332059b47e5a9cadefd8ee3b/extensions/kafka/src/main/java/com/hazelcast/jet/kafka/KafkaProcessors.java#L40

Following the example of the Kafka sink (see below), and for consistency, I suggest to drop the sentence mentioning the wrong default local parallelism of `2` in the first instance at the Kafka source documentation and only mention the default in the last paragraph as it is done for the sink documentation.

---

https://github.com/hazelcast/hazelcast-jet/blob/90d17d6be91cf4e7332059b47e5a9cadefd8ee3b/extensions/kafka/src/main/java/com/hazelcast/jet/kafka/KafkaSinks.java#L45-L99

**Comment by viliam-durina** [comment]
Thanks for the report, we will fix it. Or submit a PR yourself if you feel so.
Btw, the actual local parallelism is logged, see the `localParallelism=1` (that's for the sink):
```
digraph DAG {
	"mapSource(my-map)" [localParallelism=1];
	"writeKafka(my-topic)" [localParallelism=1];
	"mapSource(my-map)" -> "writeKafka(my-kafka)" [queueSize=1024];
}
```

**Comment by hhromic** [comment]
> Thanks for the report, we will fix it. Or submit a PR yourself if you feel so.

If you agree with my suggested fix then I can submit a PR myself, no problem!

> Btw, the actual local parallelism is logged (..)

Yes I am aware of that indeed, however I was in a discussion with a colleague and didn't have our cluster logs at hand (and I couldn't remember the default). Therefore I wanted to quickly reference the documentation during the discussion and thus discovered this little inconsistency (and where the default is set in the source code).

In general we consider the documentation of Hazelcast really good so, happy to help!
