### ISSUE TITLE
Enhancement: hazelcast-jet-sql, unclear IllegalStateException

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#2690]
Using Jet 4.4-SNAPSHOT, if I submit SQL such as `CREATE EXTERNAL MAPPING ...`
and try to access the iterator on the returned `SqlResult` you get this exception

```
java.lang.IllegalStateException: This result contains only update count
	at com.hazelcast.sql.impl.client.SqlClientResult.checkIsRowsResult(SqlClientResult.java:127)
	at com.hazelcast.sql.impl.client.SqlClientResult.iterator(SqlClientResult.java:94)
```

While it's not valid to access the iterator, the error message could be more helpful, and there doesn't seem to be a way to access the quoted update count.

**Comment by neilstevenson** [comment]
The stacktrace suggests this might be an IMDG issue, but "`CREATE EXTERNAL MAPPING`" would only be valid for Jet

**Comment by viliam-durina** [comment]
There's an `updateCount()` method on the result object. To me this seems clear enough.
