### ISSUE TITLE
Enhancement, hazelcast-jet-sql, inconsistent use of equals on internal/external mappings

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#2705]
For Kafka options, no "`=`" is defined between option name and option value.
```
                + " TYPE Kafka "
                + " OPTIONS ( "
                + " keyFormat 'json',"
```

For IMap, "`=`" is defined between option name and option value
```
                + " TYPE IMap "
                + " OPTIONS ( "
                + " 'keyFormat' = 'java',"
```

The "`=`" should be consistent, required for both, or not required.

**Comment by gierlachg** [comment]
Both should need `=`. Are you sure you are on the latest version?

**Comment by neilstevenson** [comment]
@gierlachg I was using yesterday's build, (`<updatePolicy>interval:720</updatePolicy>`). Tried `mvn -U`, problem gone away :-)
