### ISSUE TITLE
Searching for Javadoc(s) in the search bar doesn't return any meaningful result

### ISSUE THREAD

**Issue by nfrankel** [hazelcast/hazelcast-jet#2726]
## Expected behavior

Searching for `Javadoc` or `Javadocs` should return at least the [versions page](https://jet-start.sh/versions).

## Current behavior

<img width="652" alt="Current behavior when searching for Javadocs" src="https://user-images.githubusercontent.com/752258/100995696-69999880-3558-11eb-955c-d7a1daacc4a5.png">

**Comment by mtopolnik** [comment]
Everything about the search is outside our control, a [3rd party](https://docusaurus.io/docs/en/search) crawls our content and provides the results. Customizing any aspect means we first have to [run our own](https://docsearch.algolia.com/docs/run-your-own) indexer.

**Comment by mtopolnik** [comment]
Duplicates #2700.
