### ISSUE TITLE
OOM: Log4j2 loggers for job are not deregistered when job finished

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2730]
This is consecutive issue for https://github.com/hazelcast/hazelcast-jet/issues/2703.

If log4j2 is used then `org.apache.logging.log4j.core.LoggerContext` holds all registered loggers (and doesn't clean them). If jobs with different names are executed then couple of loggers is registered for each of them. It can lead to OOM error.

Some details:
- `org.apache.logging.log4j.core.LoggerContext` holds `org.apache.logging.log4j.spi.LoggerRegistry` which holds map `map` with all registered loggers.
- We register new logger in `com.hazelcast.logging.Log4j2Factory.createLogger`
- It seems there is no direct method to deregister them but it can be probably done by obtaining registered loggers by `LoggerContext.getLoggers()`

Steps to reproduce are similar as in https://github.com/hazelcast/hazelcast-jet/issues/2703 - just run the code on Jet server which uses log4j2 and check size of map which is stored in `org.apache.logging.log4j.spi.LoggerRegistry.map`

**Comment by viliam-durina** [comment]
Essentially a `Logger` must be treated as a resource. We normally don't because they are used for the lifetime of the JVM. But if they have limited lifespan, they must be released. Maybe we should document this in IMDG documentation.

**Comment by viliam-durina** [comment]
Was fixed in #2737
