### ISSUE TITLE
Not requiring columns not required for JSON format

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#2758]
This command should fail, but it succeeds:
```sql
CREATE MAPPING latest_trades
TYPE IMap
OPTIONS (
    'keyFormat' = 'java',
    'keyJavaClass' = 'java.lang.String',
    'valueFormat' = 'json'
);
```
For JSON we can't resolve the columns. If the `keyFormat` was also `json`, the command will fail with "The resolved field list is empty".

**Comment by gierlachg** [comment]
Addressed with #2776
