### ISSUE TITLE
SQL Docs Improvements

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#2761]
The SQL intro doc could use some improvement in explaining the concepts. Consider splitting it into "get started", "concepts" and "reference" parts.

* I think we need an intro section that explains all the concepts behind Jet SQL
   - What does a query do? What is its lifecycle? How does it relate to Jobs?
   - What is a `mapping`? Where does it get stored? What is its lifecycle? - sidenote: The name `mapping` can be confused with IMap did we consider other names?
  
Some other notes:

* Would it make sense to add a test source, so you can try SQL without having Kafka?
*  I didn't see any docs for SHOW MAPPINGS or SHOW JOBS

**Comment by codeboy5** [comment]
Can i take this up ?

**Comment by cangencer** [comment]
@codeboy5 please go ahead! feel free to get in touch with the team at our slack on the #jet channel (https://slack.hazelcast.com)

**Comment by jerrinot** [comment]
+1 to this.

Also please consider including a full-blown Kafka -> IMap via SQL tutorial.

**Comment by vladoschreiner** [comment]
> Also please consider including a full-blown Kafka -> IMap via SQL tutorial.
The full-blown Kafka->IMap tutorial is already available in the working branch: https://github.com/hazelcast/hazelcast-jet/blob/sql-join/site/docs/sql/intro.md

**Comment by jerrinot** [comment]
ok, somehow I didnt expect this in the Intro section. Consider turning it into an explicit guide.

**Comment by mtopolnik** [comment]
I'm currently writing the Get Started section and revising the rest, we should coordinate.
