### ISSUE TITLE
Missing EXTERNAL NAME for MAPPING NAME

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2781]
When the name different from Kafka topic name should be used then there's a possibility to do it by `objectName` option. However it's not much visible. Provide `EXTERNAL NAME` for `MAPPING NAME` makes it more visible.

If topic `trades` should have name `trades2` in Jet then currently following has to be used:
```
CREATE EXTERNAL MAPPING trades2 (
    ...)
TYPE Kafka
OPTIONS (
    'objectName' = 'trades',
    ...
);
```
This seems to be more clear and visible:
```
CREATE EXTERNAL MAPPING trades EXTERNAL NAME trades (
    ...)
TYPE Kafka
OPTIONS (
    ...
);
```

**Comment by gierlachg** [comment]
Addressed with #2791
