### ISSUE TITLE
Location options for file connector in SQL should include link to Source and Sinks section

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2784]
Location options (https://jet-start.sh/docs/next/sql/file-connector#location-options) includes info about supported schemes. Since there are also cloud services which needs to have additional configuration (e.g. credentials) we should have the link into Supported Storage Systems section there (https://jet-start.sh/docs/next/api/sources-sinks#supported-storage-systems).

**Comment by gierlachg** [comment]
Addressed with #2794
