### ISSUE TITLE
Using Apache mahout in Hazelcast Jet

### ISSUE THREAD

**Issue by 0utman1** [hazelcast/hazelcast-jet#2826]
I want using Jet cluster & Aapache mahout to calculate item cf or user cf, but i don't know how to start it which my English is poor.. Does anybody know how to do this?

My data in IMap looks like this:

`
public class RecUserInfoDto implements Serializable {
    
   private static final long serialVersionUID = 1L;
    private String userId ;
    /** user cf needed */
    private List<String> userTags ;
    /** item cf needed */
    private List<String> userPreferItemTags ;
    /** cf result */
    private Map<String,List<String>> cfPreferMap;
}
`

Thank you very much!

**Comment by vladoschreiner** [comment]
Running Jet as a backed engine for Apache Mahout would require implementing a Jet binding for Mahout such as the [community engines](https://github.com/apache/mahout/tree/trunk/community/community-engines). Please refer to the Mahout community for a guidance.

**Comment by 0utman1** [comment]
> Running Jet as a backed engine for Apache Mahout would require implementing a Jet binding for Mahout such as the [community engines](https://github.com/apache/mahout/tree/trunk/community/community-engines). Please refer to the Mahout community for a guidance.

Thank you.
