### ISSUE TITLE
IOUtil unzip doesn't handle correctly file paths

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2852]
`com.hazelcast.jet.impl.util.IOUtil.unzip` (https://github.com/hazelcast/hazelcast-jet/blob/master/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/IOUtil.java#L122) doesn't sanitize paths within unzipped archive which can lead to creating files outside of target directory.

**Comment by viliam-durina** [comment]
See https://snyk.io/research/zip-slip-vulnerability
