### ISSUE TITLE
DAG printing does not reflect real queue size

### ISSUE THREAD

**Issue by hhromic** [hazelcast/hazelcast-jet#2878]
Hello, I just stumbled into this little annoyance in Jet.

When you change the default queue size for the edges in the Jet configuration, the printed DAG of a pipeline does not reflect the new value, however the pipeline indeed does use the newly configured `queue_size`.

Consider this simple example for configuring an instance of Jet with a non default `queue_size`:

```java
// prepare Jet configuration
final JetConfig config = JetConfig.loadDefault();
config.getDefaultEdgeConfig().setQueueSize(4096);

// obtain a new Hazelcast Jet instance
final JetInstance jet = Jet.newJetInstance(config);
```

When starting a pipeline, the printed DAG still reports the default `queue_size` value. For example:
```
digraph DAG {
        "kafkaSource(some-topic)" [localParallelism=4];
        "jdbcSink" [localParallelism=1];
        "kafkaSource(some-topic)" -> "jdbcSink" [queueSize=1024];
}
```

Note that I confirmed that the configured `queue_size` is **indeed applied correctly**, just not printed correctly above.

The relevant code in Jet seems to be this:
https://github.com/hazelcast/hazelcast-jet/blob/84d30f20ed4167238de7f783720a38c731ca547f/hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/DAG.java#L490-L492

Looks like that the correct thing to do is that, when `e.getConfig() == null`, the right thing to do is to pick the value from the `EdgeConfigDefault` and not directly from the default constant. If the default value is not changed in `EdgeConfigDefault`, it should contain anyway the value of the constant.

Or perhaps the bug is that `e.getConfig()` is not getting set at that point yet.

**Comment by hhromic** [comment]
After further investigation, it looks like indeed `e.getConfig()` is expected to be `null` if there is no explicit change in edge config regardless if the defaults are changed:

https://github.com/hazelcast/hazelcast-jet/blob/e467d928867a077dea6e96e269c6aaf96a2e8013/hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Edge.java#L521-L529

So probably this previous comment is correct to assume?

> (...), when e.getConfig() == null, the right thing to do is to pick the value from the EdgeConfigDefault and not directly from the default value constant. If the default value is not changed in EdgeConfigDefault, it should contain anyway the value of that constant.

**Comment by viliam-durina** [comment]
Thanks for the report. I had a quick look and the reason seems to be that in `DAG` or `Edge` classes we don't have access to `JetConfig`. You can create a `DAG` or `Pipeline` without a `JetInstance` and submit it later. 

Instead of `1024` we could print `DEFAULT`. Or instead of the `defaultParallelism` we can pass `JetConfig` to the method as it contains all the default values the method needs.

**Comment by hhromic** [comment]
Thanks for looking into this.

> Or instead of the defaultParallelism we can pass JetConfig to the method as it contains all the default values the method needs.

That sounds like the ideal solution to me. Reporting `DEFAULT` is not very informative unfortunately. The DAG printing is really useful to us, specially if it shows actual values used. Also passing a `JetConfig` object could open the door for printing other relevant information in the future as well.
