### ISSUE TITLE
Configurable `BATCH_LIMIT` size in JDBC connector (sink)

### ISSUE THREAD

**Issue by hhromic** [hazelcast/hazelcast-jet#2879]
At the moment, the batch limit size is hard-coded in the JDBC connector (sink):

https://github.com/hazelcast/hazelcast-jet/blob/84d30f20ed4167238de7f783720a38c731ca547f/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJdbcP.java#L61

For our requirements (dumping high throughput data from Kafka into a Vertica database) we require to raise this value to much higher values than the hard-coded one. At the moment we are just using a locally modified version of this class with a higher number hard-coded but we would like to implement a configurable approach instead so we don't have to "hack" the class locally and everyone can fine-tune depending on their needs.

I already have some ideas on how to implement this feature request, and would be happy to contribute it to upstream Jet if you agree with it. Let me know if this is the case so we can briefly discuss the implementation details.

Thanks!

**Comment by viliam-durina** [comment]
Hi, your request makes sense and might be useful for others too. I think you can add a method to `JdbcSinkBuilder`, should be easy to do. If you have any questions, ask here or you can use our community Slack channel here: https://slack.hazelcast.com/. If you'd like to contribute your Vertica connector, we might accept it into the https://github.com/hazelcast/hazelcast-jet-contrib/ repo.

**Comment by hhromic** [comment]
>  I think you can add a method to JdbcSinkBuilder, should be easy to do.

Great to read that, it was precisely the way I was thinking on implementing this 👍.

>  If you'd like to contribute your Vertica connector, (...)

We don't have a specialised Vertica connector, we are just using the built-in JDBC connector from Jet itself, it works really well with a larger `BATCH_LIMIT` value, hence the need to make it configurable. The Vertica JDBC driver does not support XA transactions unfortunately, but apart from that all works great.

I will prepare a prototype and submit a PR as soon as possible. Thanks!
