### ISSUE TITLE
Jet SQL allows incompatible pairings

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#2918]
This is accepted by Jet SQL 4.4 without exception

```
'CREATE OR REPLACE MAPPING IF NOT EXISTS neil TYPE IMap  OPTIONS (  'keyFormat' = 'java', 'keyJavaClass' = 'java.lang.String', 'valueFormat' = 'java', 'valueJavaClass' = 'java.lang.String' )'
```

It's incompatible and is unclear what it will do if the mapping exists

`REPLACE` would require it to be written
`CREATE .. IF NOT EXISTS` would required it not to be written

**Comment by gierlachg** [comment]
You could read it as `CREATE OR REPLACE only IF NOT EXISTS`. If `IF NOT EXISTS` is present `OR REPLACE` is redundant and does not change the semantics. However, that's true that usually DBs provide just one or the other.

**Comment by viliam-durina** [comment]
But we should probably disallow it...
