### ISSUE TITLE
Job that reads from Hazelcast IMDG IMap source can cause JVM OOM when member heap is small

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast-jet#2926]
Given the following pipeline code:

```
pipeline
    .readFrom(Sources.remoteMap(mapName, clientConfig))
    .map(entry -> entry.getKey())
    .writeTo(Sinks.logger());
```

where the remote map is configured for NATIVE format, and the JVM heap is small (i.e. 1 GB), the IMDG members can experience OOM errors when preparing to send the data for the Jet client.

Attached is a reproducer project that demonstrates this behavior (thanks @neilstevenson). You may need to increase the `valueSize` to `4000` to trigger the OOM when running in 4.x and later. Also, attaching a heap dump that was generated from running this project with `-XX:+HeapDumpOnOutOfMemoryError` specified on the IMDG members.

reproducer: [zen7099.zip](https://github.com/hazelcast/hazelcast-jet/files/6037765/zen7099.zip)
heap dump: [hz_4_dump.tar.gz](https://github.com/hazelcast/hazelcast-jet/files/6037775/hz_4_dump.tar.gz)

In the dump you can see that `NioOutboundPipeline.writeQueue` is full.

In a related Slack thread, @viliam-durina made two suggestions for remediating this issue that I wanted to capture here:

1. Currently we limit data transfer based on item count rather than bytes which can be a problem in cases like this with large values. The suggestion was to limit based on bytes, but this would require changes on both Jet and IMDG sides.
2. Reduce the number of parallel requests sent, and reduce the number of items fetched, which would only require changes on the Jet side.

**Comment by sertugkaya** [comment]
ZD 7099
