### ISSUE TITLE
Type coercion for UDFs should not implicitly convert VARCHAR to INT

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#2930]
This query works, but should throw something like `Cannot apply VARCHAR to INT argument`:
```sql
SELECT * FROM TABLE(generate_series('0', '5'))
```

**Comment by gierlachg** [comment]
It does not for me. I'm getting `com.hazelcast.sql.HazelcastSqlException: Invalid argument of a call to function GENERATE_SERIES - #0 (start). Expected: INTEGER, actual: CAST`

**Comment by viliam-durina** [comment]
That's because of #2929. When that's fixed, it will pass, but it should not.
