### ISSUE TITLE
com.hazelcast.jet.benchmark.WordCountTest intermittently gets stuck

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2959]
_master_ (commit 7977d5eef8368fa09bdbb13dd8d99c53a50706d2)

Failed on nightly run with Zulu JDK 15: http://jenkins.hazelcast.com/job/jet-oss-master-nightly-zulu-jdk15/47/console
It happened also with Oracle JDK 8: http://jenkins.hazelcast.com/job/jet-oss-master-nightly-oracle-jdk8/424/console

Standard output:
```
03:20:08 [INFO] Running com.hazelcast.jet.benchmark.WordCountTest
03:20:08 Build timed out (after 60 minutes). Marking the build as aborted.
03:42:21 Stopping Docker container after build completion
03:42:21 Build was aborted
```

There is failing `com.hazelcast.jet.MulticastDiscoveryTest` (https://github.com/hazelcast/hazelcast-jet/issues/2904) before the test which can maybe affect it somehow.

**Comment by gierlachg** [comment]
That could be because of #2904. If so, should be fixed with hazelcast/hazelcast#18393. Let's reopen or create new one if happens again.
