### ISSUE TITLE
Vulnerabilities in parquet-jackson used by Jet master

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2982]
Jet which uses `parquet-jackson` in version `1.11.1` which has shaded `com.fasterxml.jackson.core:jackson-databind:2.9.10` which includes couple of vulnerabilities, see https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Afasterxml&cpe_product=cpe%3A%2F%3Afasterxml%3Ajackson-databind&cpe_version=cpe%3A%2F%3Afasterxml%3Ajackson-databind%3A2.9.10

**Comment by gierlachg** [comment]
1.11.1 is the latest, as of today, version of parquet.

**Comment by frant-hartm** [comment]
parquet-jackson seems to be just relocated jackson - see https://github.com/apache/parquet-mr/tree/master/parquet-jackson
We could create such artifact with up-to-date version of jackson ourselves.

Alternatively we can wait - it seems that there is an ongoing release of next version of parquet (1.12.0), which contains jackson 2.11.4.

**Comment by frant-hartm** [comment]
We should really wait for 1.12.0:

https://lists.apache.org/x/thread.html/rb21784e118cff6cf2ce064eff60dbe01caafe460559f85e4bd4607d2@%3Cdev.parquet.apache.org%3E
