### ISSUE TITLE
Missing code sample results in the SQL documentation

### ISSUE THREAD

**Issue by vladoschreiner** [hazelcast/hazelcast-jet#2996]
The SQL Getting Started website article misses the expected values the code should print:

<img width="880" alt="Snímek obrazovky 2021-03-19 v 10 15 38" src="https://user-images.githubusercontent.com/16268021/111758136-670b4680-889c-11eb-9a8f-fbe7d3214c87.png">

**Comment by ufukyilmaz** [comment]
Since the series from 1 to 5 printed is already the expected output of this query, I closed the issue.

**Comment by vladoschreiner** [comment]
I thought it was line numbers and empty lines :facepalm:

**Comment by viliam-durina** [comment]
@vladoschreiner I thought you gave the image as an example how it should be and that the output is missing elsewhere :)
