### ISSUE TITLE
com.hazelcast.jet.JetException: Failed to connect to database: Failed to authenticate to the MySQL database

### ISSUE THREAD

**Issue by danishxav** [hazelcast/hazelcast-jet#3072]
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{mysql-monitor/source#0}: com.hazelcast.jet.JetException: Failed to connect to database: Failed to authenticate to the MySQL database at 172.0.0.1:3306 with user 'mysql_user': Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Comment by frant-hartm** [comment]
hi,
you are probably using MySQL 8
we are using a client, which doesn't support the latest default authentication mechanism,
you can switch to a supported authentication mechanism by following this guide
https://jet-start.sh/docs/operations/cdc#database-user

Closing as this is a configuration issue of mysql.
