### ISSUE TITLE
Does hazelcast-jet will go on?

### ISSUE THREAD

**Issue by googlefan** [hazelcast/hazelcast-jet#3148]
hallo, author:
      I noticed that most of the code in hazelcast-jet hasn't been updated for the past two years. The current version of hazelcast being used is 4.2, while the latest version on GitHub has already been updated to 5.4. I'm wondering if there are any plans to continue updating hazelcast-jet in the future. Will the feature changes in hazelcast have an impact on the functionality of hazelcast-jet?

**Comment by TomaszGaweda** [comment]
Hi @googlefan, Jet is now a part of Hazelcast Platform - see github.com/hazelcast/hazelcast.
