### ISSUE TITLE
Can jet sink to IQueue ?

### ISSUE THREAD

**Issue by googlefan** [hazelcast/hazelcast-jet#3150]
I notice that hazelcast jet  has many types of sources and sinks. In IMDG , it support IMap、 IList and some jms also support.
But I can't find the support of IQueue. I found a test class "SourceSinkBuilderTest". Its code is very strange. It use SinkContext  to restore the IQueue, but I can't get the IQueue by jet.getQueue like jet.getMap.Why ? can somebody tell me ?

**Comment by TomaszGaweda** [comment]
@googlefan would be best to use our Community Slack for such questions ;) In Hazelcast Platform (5.x) you have an access to whole instance, including `getQueue`

**Comment by googlefan** [comment]
> @googlefan would be best to use our Community Slack for such questions ;) In Hazelcast Platform (5.x) you have an access to whole instance, including `getQueue`

Thank you for your response. 
By the way , the lastest hazelcast-jet-spring-boot-starter's version is "2.0.1" ,and it use  4.3 of the  hazelcast-jet  and  4.0.3 of hazelcast dependency .  Would the hazelcast-jet-spring-boot-starter been updated in the future?
Or  can I use 5.x of Hazelcast instead of 4.0.3 in the  hazelcast-jet-spring-boot-starter dependency?
Can you help me with these question?

**Comment by googlefan** [comment]
> 

Maybe I confused this question.What I want is  "use Jet instance.getQueue  as source or sink like IMap".And I find hazelcast instance of  server or client  has getQueue method , but it is not what I wants. I was confuse of them .

**Comment by TomaszGaweda** [comment]
>instance of server or client has getQueue method , but it is not what I wants

It returns IQueue, `JetInstance.getQueue` is deprecated and you should now use IQueue instead.

For further questions it'd be great if you. join our community slack: https://hazelcastcommunity.slack.com/ Will be easier to talk than on GH issue

**Comment by TomaszGaweda** [comment]
Currently there's no spring boot jet starter for Hz >= 5.x. We may reintroduce it, but so far there's only starter for core Hz

**Comment by googlefan** [comment]
> > instance of server or client has getQueue method , but it is not what I wants
> 
> It returns IQueue, `JetInstance.getQueue` is deprecated and you should now use IQueue instead.
> 
> For further questions it'd be great if you. join our community slack: https://hazelcastcommunity.slack.com/ Will be easier to talk than on GH issue

Very pleasure  to join the slack. But when I sign in ,it shows "doesn’t have an account on this workspace."  pzzhuhui@gmail.com is my email .Need you invite me ?
