### ISSUE TITLE
Checkstyle differences on Hazelcast modules

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#356]
The file `checkstyle/checkstyle.xml` differs from project to project. Stylistic checks should be unified. This caused https://github.com/hazelcast/hazelcast-jet-code-samples/issues/9

For example:
(1) `hazelcast` has
```
    <module name="NewlineAtEndOfFile">
        <property name="lineSeparator" value="lf" />
    </module>
   <module name="EmptyBlock"/>
```
(2) `hazelcast-jet` has
```
    <module name="NewlineAtEndOfFile">
        <property name="lineSeparator" value="lf" />
    </module>
    <module name="EmptyBlock">
        <property name="option" value="text"/>
        <property name="tokens" value="LITERAL_CATCH"/>
    </module>   
```

(3) `hazelcast-jet-code-samples` has
```
    <module name="NewlineAtEndOfFile"/>
    <module name="EmptyBlock"/>
```

Three modules, no two the same

**Comment by viliam-durina** [comment]
Now, all three have

```
    <module name="NewlineAtEndOfFile">
        <property name="lineSeparator" value="lf" />
    </module>```

**Comment by neilstevenson** [comment]
@viliam-durina  Perhaps we need a common build dependency for all projects ?

**Comment by cangencer** [comment]
The one from hazelcast-jet should be used in all projects. Since we only have two repositories right now, we can fix this manually. If the number of repos grows eventually, then yes we should find a way to centralize the checkstyle.xml.

**Comment by neilstevenson** [comment]
@cangencer Should checkstyle for Jet differ from Imdg though ?

**Comment by cangencer** [comment]
I don't think that's required. We use a different version of Checkstyle due to Java 8, and also have relaxed some of the rules as agreed by the team.
