### ISSUE TITLE
Remote IMDG access fails silently for JetClient

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#364]
Use of `com.hazelcast.jet.impl.connector.ReadWithPartitionIteratorP.readMap(String mapName, ClientConfig clientConfig)` fails silently for a DAG submitted by a JetClient. Works from JetInstance that is a server.

Looks like a problem with `RemoteClusterMetaSupplier` and the `iteratorSupplier` instance lambda.

Currently tried on _0.3.2-SNAPSHOT_

**Comment by gurbuzali** [comment]
it works for me, can you please share a reproducer?

**Comment by neilstevenson** [comment]
Try https://github.com/hazelcast/hazelcast-jet-training/tree/essentials/essentials/j-e-lab3
Same issue on _0.3.1_

**Comment by gAmUssA** [comment]
tested.

- start IMDG
- start listener client
- started jet instance with job submission code
- saw output in listener
- started jet client
- saw no new messages in listener

**Comment by gAmUssA** [comment]
tested

- start IMDG
- start listener client
- started jet instance with commented job submission code
- saw no output in listener
- started jet client
- saw no new messages in listener

confirm @neilstevenson behavior.

```
java 8 jdk1.8.0_60.jdk
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E192b
```

**Comment by neilstevenson** [comment]
I'm on jdk1.8.0_121, OXS 10.12.3

**Comment by gAmUssA** [comment]
same behavior with 0.3.2-SNAPSHOT

**Comment by gurbuzali** [comment]
I think I've found the problem, `jetClient.newJob(new Issue364DAG()).execute()` this is async.
just after starting the job you shutdown the client, when you add `.get` to the end of line it works

**Comment by gAmUssA** [comment]
@gurbuzali 👍 good one!

**Comment by neilstevenson** [comment]
@gurbuzali  user error 👍
