### ISSUE TITLE
Dumping Stream data into hazelcast map using JET

### ISSUE THREAD

**Issue by mukul4u2005** [hazelcast/hazelcast-jet#386]
Hi 

I am trying to implement one sample application and write a processor as:

    private static class StockReader extends AbstractProcessor
    	{
		private final FlatMapper<Entry<Long, String>, Stock> flatMapper;

		
		

		public StockReader() {
			super();
			this.flatMapper = flatMapper(e -> traverseStream(readStock(e.getValue())));
		}

		@Override
		protected boolean tryProcess(int ordinal, Object item) throws Exception {
			// TODO Auto-generated method stub
			return flatMapper.tryProcess((Entry<Long, String>) item);
		}
		
		private static Stream<Stock> readStock(String fileName){
			 try {
	                return  Files.lines(Paths.get(new URI("file:///C://Backup/stocks.csv"))).map(stock -> new Stock(stock));
	            } catch (IOException | URISyntaxException e) {
	                throw new RuntimeException(e);
	            }
		}
	}
    }

Now I created a DAG implementation but it is not allowing to add the object as Map value, please suggest what I am doing wrong.

    DAG dag = new DAG();
		 Vertex source = dag.newVertex("source", readMap("stockMap")).localParallelism(1);
		 Vertex docLines = dag.newVertex("doc-lines", StockReader::new).localParallelism(1);
		 Vertex combiner = dag.newVertex("combiner", collect(Collectors.toMap(random.nextInt(50),Function.identity())));
		 Vertex sink = dag.newVertex("sink", writeMap("counts"));
		 dag.edge(between(source, docLines)).edge(between(docLines,sink));

I am getting compilation error at:

   Vertex combiner = dag.newVertex("combiner", collect(Collectors.toMap(random.nextInt(50),Function.identity())));

Error is showing as : The method toMap(Function<? super T,? extends K>, Function<? super T,? extends U>) in the type Collectors is not applicable for the arguments (int, Function<Object,Object>)

**Comment by mukul4u2005** [comment]
It seems like I have to define the object like , I have a pojo class Stock.class,

Vertex combiner = dag.newVertex("combiner", collect(Collectors.toMap(x -> x.getStockId, x -> x)));

First of all in DAG implementation it is not recognizing the Stock and giving compilation error. Could you suggest how can I define with DAG implementation . Just assume , Stock is my pojo class and I am trying to achieve a Map<Integer,Stock> in hazelcast.

**Comment by mukul4u2005** [comment]
Could you suggest about this , Please ?

**Comment by cangencer** [comment]
Could you tell us about what you're trying to achieve in your Jet job? Are you trying to write the Stocks inside a map?

Your code doesn't compile because `Processors.collect` doesn't take a `Collector` as a parameter. Please examine the method's javadocs here: https://github.com/hazelcast/hazelcast-jet/blob/v0.3.1/hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java#L427

**Comment by mukul4u2005** [comment]
Yes I am trying to dump 10 million records in Hazelcast using Jet and finding that which stock value increased by 5% of their previous value . 

I am doing some benchmarking on how Jet make it fast to dump the object on cache as compare to written code by Java 8 stream.

 Jet is  using Java 8 stream and DAG implementation so I am trying to do both implementation for this usecase
