### ISSUE TITLE
Running in gradle

### ISSUE THREAD

**Issue by djKooks** [hazelcast/hazelcast-jet#399]
Hello~
Is there a way to use this by gradle build system?

**Comment by cangencer** [comment]
You can add it as a dependency as follows:

```
compile 'com.hazelcast.jet:hazelcast-jet:0.3.1
```

If you want to build hazelcast-jet itself, you'll have to use Maven.

**Comment by djKooks** [comment]
@cangencer Thanks for quick answer~
