### ISSUE TITLE
Kafka connector may miss heartbeat/session timeout interval

### ISSUE THREAD

**Issue by sandeepmalik** [hazelcast/hazelcast-jet#428]
Hi All,

In the complete() method of ReadKafkaP, we emitCooperatively() the last polled batch and do not poll until the batch is done. If the downstream vertices are slow, it is possible that the emitting takes longer than session timeout for kafka in which case, kafka will assume the node to be dead and issue a rebalance, which is an expensive operation. We should ensure that processing time has no/minimal impact on the timeouts by:

1. pausing the partitions once data is fetched
2. Doing (empty) poll more frequently to stay within heartbeat/session timeout range
3. resuming the partitions once emitCooperatively() returns true.

**Comment by gurbuzali** [comment]
Hi,
Thank you for reporting the issue. We've changed the processor logic a bit, we don't use `emitCooperatively` anymore but the issue is same. We call the `poll` only after emitting the batch.

I've reproduced the case you've described by simply putting some sleep between `poll` calls. The simplest solution would be that the user configure some high session timeout while creating the processor.However I'm currently building a prototype to see how we can fix the issue even with some low session timeout configuration. Let's see how it will turn out.

**Comment by sandeepmalik** [comment]
HI Ali, 

Thanks. You're right. However, the higher timeout has an issue of late detection by broker if a node is really dead. Also, the timeout can't be set beyond broker's max session time out. 

We solved this issue by pausing the partitions (consumer.pause(...)) and then issuing heartbeat polls at ~ 1/3 of session time out value even if the batch is not completely processed. Never saw a rebalance after that. Hope that can help.

**Comment by cangencer** [comment]
It seems like since Kafka 0.10.1.0, there is always a background heartbeat thread created.

In change log for 0.10.1.0:

```The new Java Consumer now supports heartbeating from a background thread. There is a new configuration max.poll.interval.ms which controls the maximum time between poll invocations before the consumer will proactively leave the group (5 minutes by default). The value of the configuration request.timeout.ms must always be larger than max.poll.interval.ms because this is the maximum time that a JoinGroup request can block on the server while the consumer is rebalancing, so we have changed its default value to just above 5 minutes. Finally, the default value of session.timeout.ms has been adjusted down to 10 seconds, and the default value of max.poll.records has been changed to 500.```

Also see the discussion here: https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread

**Comment by viliam-durina** [comment]
In PR #500 we've implemented manual partition assignment where the heartbeat is not used. It should resolve this issue.

**Comment by bipulkarnani** [comment]
> HI Ali,
> 
> Thanks. You're right. However, the higher timeout has an issue of late detection by broker if a node is really dead. Also, the timeout can't be set beyond broker's max session time out.
> 
> We solved this issue by pausing the partitions (consumer.pause(...)) and then issuing heartbeat polls at ~ 1/3 of session time out value even if the batch is not completely processed. Never saw a rebalance after that. Hope that can help.

When `CommitFailedException` occurs, consumer closes and processing stops. We tried to use high session timeout but still our message processing is a bit complex which takes lot of time. 

I am waiting for 0.5 where we assign partition manually. 

@sandeepmalik Can you please share your piece of code where you used `consumer.pause()` to solve this issue?
