### ISSUE TITLE
Merging Sink for Cache/Map entry

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#486]
In `com.hazelcast.jet.processor.Sinks`, the `writeCache()` and `writeMap()` methods create or replace the entry.

There isn't a partition-efficient and concurrent-safe mechanism for a sink to update an existing entry. For example, to update the balance on a bank account as a result of processing a stream of transactions.

Currently the sink would have to read the old value, merge and write. This read is via IMDG so may not be partition optimised. The `emit()` can be partition optimised, but in the mean time the entry may have been updated by another thread.

**Comment by cangencer** [comment]
This is being fixed in #621

**Comment by cangencer** [comment]
Fixed by #621
