### ISSUE TITLE
Kafka connector support for JSON deserializer

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#495]
In `StreamKafkaP`, JSON deserializer classes cannot be used.

For the properties list, you can do
```
properties.put("value.deserializer", LongDeserializer.class.getCanonicalName());
```
but not
```
properties.put("value.deserializer", JsonDeserializer.class.getCanonicalName());
```
as the JSON deserializer needs instantiated with the class it reads.

You can workaround by implementing your own deserializer specifically for the class you need to deserialize via JSON but that's just boilerplate code.

Being able to use something similar to `new DefaultKafkaConsumerFactory<>(consumerConfigs, keyDeserializer, valueDeserializer);` would be helpful.

**Comment by mtopolnik** [comment]
Shouldn't this be handled in a mapping stage after the source?

**Comment by viliam-durina** [comment]
As a workaround you can do this:
```java
public class ConsumerJsonDeserializer extends JsonDeserializer {
    public ConsumerJsonDeserializer () {
        super(Consumer.class);
    }
}
```
and then add this:

```java
properties.put("value.deserializer", ConsumerJsonDeserializer.class.getName());
```

I did not test it, because the `JsonDeserializer` class is not standard part of Kafka and I don't know which implementation you used.

**Comment by cangencer** [comment]
As this seems like a quite common use case we should provide some convenience for reading JSON from Kafka.

**Comment by viliam-durina** [comment]
I tested, this should work with `org.springframework.kafka.support.serializer.JsonDeserializer`:
```
    properties.setProperty("key.deserializer", StringDeserializer.class.getName());
    properties.setProperty("value.deserializer", JsonDeserializer.class.getName());
    properties.setProperty(JsonDeserializer.DEFAULT_VALUE_TYPE, MyObject.class.getName());
```
Since there is no response from OP I close this.

**Comment by neilstevenson** [comment]
@viliam-durina Took me a while to get around to testing this, but it works for me! Thanks
