### ISSUE TITLE
Awkward API for aggregations

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet#597]
Aggregations are modeled as grouping on a constant key. Example: `computeStage.groupBy(constantKey(), averagingLong(String::length))`. 

This could be simplified to e.g. `computeStage.aggregate(averagingLong(String::length))`. 

I was struggling with this whilst converting the word-count code sample to calculate average word length. It took me a while to realize I have to use grouping by a constant key. I was looking at the `ComputeStage` API for something like `aggregate()`

**Comment by viliam-durina** [comment]
It's fixed in pipeline-windows: https://github.com/hazelcast/hazelcast-jet/blob/pipeline-window/hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStage.java#L90-L92
