### ISSUE TITLE
Create samples showing how to use each built-in aggregation

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet#599]
It took me a while to figure out how to use the built-in aggregations. We have code-samples for e.g. `counting`  but:
1. There is too much noise. I don't want to deal with Shakespeare, splitting words and lines. All I want to see how to use `averaging()`. As simple example as possible. With minimum noisy. 
2. We do not have any example showing how to use an aggregation which does not use key-based classification. e.g. `averaging()` (as opposed to counting()`

I am not sure if we need to have this as a code-sample. The current samples tries to create something resembling a real-word use-case. Even a simple junit integration test in the Jet project itself would help me a lot.

**Comment by mtopolnik** [comment]
This issue was moved to hazelcast/hazelcast-jet-code-samples#76
