### ISSUE TITLE
Persistent messages in edge outbox

### ISSUE THREAD

**Issue by dinakarreddy** [hazelcast/hazelcast-jet#603]
Jet version 0.4
We have created a DAG with two vertices, KafkaConsumer as source and a sink vertex which stores events received in a database. Sink vertex is a little slow in consuming messages and hence the edge queue will be filled with messages. When we restart the process Kafka would have already committed the offsets of the messages that were present in the edge queue and as jet stores data in memory we are losing these messages.
Can anyone please suggest me how I can implement jet DAG which persists data in edge outbox when restarted? Thank you.

**Comment by cangencer** [comment]
In version 0.4, this would be the case. You'd need to upgrade to the version released yesterday (0.5) which has snapshotting support. See here: http://docs.hazelcast.org/docs/jet/0.5/manual/Work_with_Jet/Infinite_Stream_Processing.html#page_Fault+Tolerance+and+Processing+Guarantees
If you choose processing guarantee at least once or exactly once, your offsets to Kafka will only be committed when they have been written to the sink.
