### ISSUE TITLE
Simplify Event Journal Source

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast-jet#615]
The simple signature of `Sources.mapJournal(name)` and equivalents should get you a source that delivers not `EventJournalMapEvent` but `entry(event.getKey(), event.getNewValue())`. This is probably the 99% choice for the user.

**Comment by gurbuzali** [comment]
and should it deliver only the `EntryEventType.ADDED` events as default ?

**Comment by mtopolnik** [comment]
It should filter out all the eviction and similar event types, but it should cover both `ADDED` and `UPDATED`.

**Comment by cangencer** [comment]
`newValue` as `null` could also supports removals.

**Comment by viliam-durina** [comment]
>newValue as null could also supports removals.
Not really, it doesn't cover the CLEAR_ALL event. That could be `entry(null, nul)` but it's a bit far-fetched. I prefer it simpler: only ADDED and UPDATED.

**Comment by cangencer** [comment]
Fixed by #650
