### ISSUE TITLE
Issue with TryEmit Method in abstract processor.

### ISSUE THREAD

**Issue by parthdwe** [hazelcast/hazelcast-jet#620]
I create simple processor which is generate the 0 to 10000 number and emit to the next vertex.
While i received at the next vertex it will only give the 9983 number.
My processor code is like below:

```
import javax.annotation.Nonnull;
import com.hazelcast.jet.core.AbstractProcessor;
public class Randomnumber extends AbstractProcessor {
	public Randomnumber() {

	}

	@Override
	protected void init(@Nonnull Context context) throws Exception {
		super.init(context);
	}

	@Override
	public boolean complete() {
		Generatenumber.getnumber().stream().limit(64).forEach(msg -> {
			System.out.println("Start Streaming::"+msg);
			tryEmit(msg);
		});
		return false;
	}
}
```
number generation code is like below:
```
import com.aol.simple.react.async.Queue;
public class Generatenumber extends Thread {
	static Queue<Integer> numberQueueIn = new Queue<Integer>();

	public static Queue<Integer> getnumber() {
		return numberQueueIn;
	}

	public void run() {
		for (int i = 0; i <= 10000; i++) {
			numberQueueIn.add(i);
		}
	}
}
```

i get the whole data in this processor but at the next vertex i got only 9983 number.
My receiving processor just print the data which is got in tryProcess method.

so how i am losing the data to the next vertex?
If i remove the limit in above code the there is only 2048 data is transfer from source node to next node.
if i set the minimum limit in streaming so that it will process all the data count.

**Comment by viliam-durina** [comment]
Your random number processor is an infinite source: you return `false` from `complete()` method all the time. 

Also you don't check the return value of `tryEmit`: if it returns `false`, you should call it again later with the same item.

For an example of distributed number sequence generator, see here: http://docs.hazelcast.org/docs/jet/0.5/manual/The_Core_API/Implement_a_Custom_Source_or_Sink.html#page_Example+-+Distributed+Integer+Generator

I wonder what the `Queue` is, because it's interface in java (`java.util.Queue`).

**Comment by parthdwe** [comment]
I Checked it with your suggestion But the method is not return false at any point and still getting less data.
is there any limitation with data emit to the next vertex?

import javax.annotation.Nonnull;

import com.hazelcast.jet.core.AbstractProcessor;

public class Randomnumber extends AbstractProcessor {

	public Randomnumber() {

	}

	@Override
	protected void init(@Nonnull Context context) throws Exception {
		super.init(context);
	}

	@Override
	public boolean complete() {

		Generatenumber.getnumber().stream().forEach(msg -> {
			System.out.println("Start Streaming::" + msg);
			boolean emit = tryEmit(msg);
			if (!emit) {
				System.out.println("Not sucessfully sent");
				tryEmit(msg);
			}
		});
		return false;
	}
}
from above code it will only sent the 2048 data count and others are not sent in next vertex.

**Comment by viliam-durina** [comment]
If `tryEmit` returns false, you should try again when `complete` is called next time, not immediately: the next call is like to return `false` again.

Try something like this (code not checked):
```
public class Randomnumber extends AbstractProcessor {
    private Traverser<Object> t;

    @Override
    protected void init(@Nonnull Context context) throws Exception {
        t = Traversers.traverseStream(Generatenumber.getnumber().stream());
    }

    @Override
    public boolean complete() {
        return emitFromTraverser(t);
    }
}
```

**Comment by parthdwe** [comment]
I Checked it with your suggestion code but there is a same result.
 is there  emitFromTraverser() emit the data in batch?(the out box collect the data at it's limit and than emit all the data at a time).
and same with the tryemit()  method?
can you please explain the emit process?
I debug it and found that when the Travers  reaches it's final data count than the execution is stuck in this for loop.
this method is in AbstractProcessor class.

 protected final <E> boolean emitFromTraverser(
            int ordinal, @Nonnull Traverser<E> traverser, @Nullable Consumer<? super E> onEmit
    ) {
        E item;
        if (pendingItem != null) {
            item = (E) pendingItem;
            pendingItem = null;
        } else {
            item = traverser.next();
        }
        for (; item != null; item = traverser.next()) {
            if (tryEmit(ordinal, item)) {
                if (onEmit != null) {
                    onEmit.accept(item);
                }
            } else {
                pendingItem = item;
                return false;
            }
        }
        return true;
    }

**Comment by viliam-durina** [comment]
I'm not familiar with `com.aol.simple.react.async.Queue`. Its javadoc says that it's blocking - you should mark your processor as non-cooperative (call `setCooperative(false)` from constructor). You probably should use the `poll(time, unit)` like this:

```
    private static final class StreamQueueP extends AbstractProcessor {
        Queue q = Generatenumber.getnumber();
        Object pendingItem;

        public StreamQueueP() {
            setCooperative(false);
        }

        @Override
        public boolean complete() {
            for (; ; ) {
                if (pendingItem == null) {
                    pendingItem = q.poll(50, TimeUnit.MILLISECONDS);
                }
                if (pendingItem == null || !tryEmit(pendingItem)) {
                    return false;
                }
                pendingItem = null;
            }
        }
    }
```

**Comment by parthdwe** [comment]
Thank you for your suggestion.
