### ISSUE TITLE
StreamFilesPTest failure while running mvn clean install 

### ISSUE THREAD

**Issue by hiteshpanchani** [hazelcast/hazelcast-jet#632]
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.034 sec - in com.hazelcast.jet.stream.SkipTest
Running com.hazelcast.jet.stream.ToArrayTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.633 sec - in com.hazelcast.jet.stream.SortTest
Running com.hazelcast.jet.TraversersTest
Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.076 sec - in com.hazelcast.jet.TraversersTest
Running com.hazelcast.jet.UtilTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec - in com.hazelcast.jet.UtilTest
Running com.hazelcast.jet.stream.UnorderedTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.965 sec - in com.hazelcast.jet.stream.ToArrayTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.472 sec - in com.hazelcast.jet.stream.UnorderedTest
Tests run: 42, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 308.255 sec - in com.hazelcast.jet.core.TopologyChangeTest

Results :

Failed tests:
  StreamFilesPTest.when_preExistingFile_then_seeAppendedLines:174->assertEmittedCountEventually:265->JetTestSupport.assertTrueEventually:102->HazelcastTestSupport.assertTrueEventually:1129->lambda$assertEmittedCountEventually$3:265 emittedCount=0, expected=999

Tests run: 1713, Failures: 1, Errors: 0, Skipped: 5

![image](https://user-images.githubusercontent.com/8516821/33460376-8448ad78-d5f3-11e7-9dc9-81718256c1d4.png)

**Comment by viliam-durina** [comment]
Hi, thanks for reporting this. This test fails on Windows (as do some others). We'll try to address that.

**Comment by hiteshpanchani** [comment]
Thanks, Viliam.
