### ISSUE TITLE
Cause: clusters part of different cluster-groups

### ISSUE THREAD

**Issue by haresh-moradiya** [hazelcast/hazelcast-jet#659]
I am working on setup Jet Cluster using hazelcast-0.5 with three different node. I have set hazelcast.xml configuration with 192.168.1.165(node1), 192.168.1.107(node2) and 192.168.1.102(node3). 
When I was started node1 and node2, it could not establish clustering with each other.
I have attached hazelcast configuration files and node1 & node2 log message screens.
How can i fixed it?
Thanks!

![node2](https://user-images.githubusercontent.com/34533818/34244224-52fa16aa-e64a-11e7-97ea-4c4d0a3bb575.PNG)
![node1](https://user-images.githubusercontent.com/34533818/34244226-535d67d2-e64a-11e7-9dc5-6f6c4f6d71e9.PNG)
[config.zip](https://github.com/hazelcast/hazelcast-jet/files/1578202/config.zip)

**Comment by gurbuzali** [comment]
looks like one of the nodes started is not picking up config xml thus having different group-names. If you check the beginning of the logs there should be a line which indicates the selected xml file like this :
```
Dec 21, 2017 10:45:30 AM com.hazelcast.jet.impl.config.XmlJetConfigLocator
INFO: Loading hazelcast-jet-default.xml from classpath.
Dec 21, 2017 10:45:30 AM com.hazelcast.jet.impl.config.XmlJetConfigLocator
INFO: Loading configuration hazelcast-test.xml from property hazelcast.config
Dec 21, 2017 10:45:30 AM com.hazelcast.jet.impl.config.XmlJetConfigLocator
INFO: Using configuration file at /java/workspace/hazelcast-jet/hazelcast-test.xml
```
Here instead of picking the default config xml (hazelcast-jet-member-default.xml) which is located in the jar I've selected a different xml (hazelcast-test.xml) by setting `hazelcast.config` system property.

**Comment by gurbuzali** [comment]
Yes, both node's configurations seem fine. They have loaded correct configuration. I assume both configuration files in servers (192.168.1.107 and 192.168.1.165) are same, as they should be.

Can you share the rest of the logging ? you can just copy/paste it here, no need to take a screen-shot. This way you can share whole logging.

**Comment by haresh-moradiya** [comment]
Yes, both node's configurations same. There is one node on window and one node on CentOs. But its not an issue. I have also try with same CentOs environment. But its not working.

I have attach logs for node1(192.168.1.165) and node2(192.168.1.107). Let me know if you required more for investigation.

[node1.log](https://github.com/hazelcast/hazelcast-jet/files/1582071/node1.log)
[node2.log](https://github.com/hazelcast/hazelcast-jet/files/1582072/node2.log)

**Comment by gurbuzali** [comment]
well this piece of log shows the problem:
```
INFO: [192.168.1.107]:5701 [node2] [0.5] Connection[id=1, /192.168.1.107:42202->/192.168.1.165:5701, endpoint=[192.168.1.165]:5701, alive=false, type=MEMBER] closed. Reason: Node could not join cluster at node: [192.168.1.165]:5701 Cause: the target cluster has a different group-name
Dec 22, 2017 2:51:19 PM com.hazelcast.cluster
WARNING: [192.168.1.107]:5701 [node2] [0.5] Node could not join cluster at node: [192.168.1.165]:5701 Cause: the target cluster has a different group-name
```
You have different group-name for each node somehow.

**Comment by haresh-moradiya** [comment]
Yes, I have change different group name with same one its working. 
Thank you so much Gurbuzali.
