### ISSUE TITLE
Map/Cache journal as finite source

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#662]
`Sources.map` and `Sources.cache` give finite sources of entries.
`Sources.mapJournal` and `Sources.cacheJournal` give stream sources of changes.

It would be useful if there was a primitive to provide a finite source of journal content, to extract the contents of the journal's ringbuffer from current start point to current end point and then finish.

This would allow a job to analyse recent history (and for example, aggregate) rather than continuous history.

**Comment by neilstevenson** [comment]
As an example use-case, an online shop may use a journal on orders and the need might be to
produce a grouping of the most popular recent purchases

**Comment by viliam-durina** [comment]
This use case can be easily and more elegantly implemented as a streaming job with sliding window. You can read the journal and aggregate the data for the last hour and slide every 5 minutes, for example. What you've described is effectively a count-based window: the amount of time that you accumulated will be dependent on the number of purchases.
