### ISSUE TITLE
Cause: Distributed Edge not working properly with multiple JetInstance in one cluster.

### ISSUE THREAD

**Issue by haresh-moradiya** [hazelcast/hazelcast-jet#665]
I am creating clustering with two nodes. I am trying to distribute Edge data from node1 to node2 using Edge distributed(). Its not working properly with hazelcast-0.5. I have tested below scenario with two nodes.

Steps:
1. Start two node using start-jet.sh in same machine.
2. Set all the Edge without isolated and add accumulate to combine as distributed & partition. 
3. Submit generator-0.1.jar using submit-job.sh. 
Outcome:
It show me two member register in hazelcast-jet screen. Sometime its working & sometime its not.

Steps:
1. Start two node using start-jet.sh in same machine.
2. Set all the Edge without isolated and add accumulate to combine as distributed & partition. 
3. Submit generator-0.1.jar using submit-job.sh.
4. Stop node1 it is moving all backup & partition key & value to node2
5. Start  one node using start-jet.sh in same machine.
6. Registration of node1 with node2 is done but partition not happen. 
Outcome:
It show me two member register in hazelcast-jet screen. Its not working all the time when restart node1 and give below warning logs:
![node1_warning](https://user-images.githubusercontent.com/34533818/34597343-1506e60c-f20c-11e7-8808-f67ac140b013.PNG)

Steps:
1. Start two node using start-jet.sh in same machine.
2. Set all the Edge with first node as isolated and add accumulate to combine as distributed & partition. 
3. Submit generator-0.1.jar using submit-job.sh.
Outcome:
It show me two member register in hazelcast-jet screen. First isolated vertex process always started with the both nodes.

I have attached random generator java project & generator-jar zip & hazelcast.xml, hazelcast-client.xml, and hazelcast-jet.xml configuration files.
How can i fixed isolated & distributed issue?
Thanks!

[generator-jar.zip](https://github.com/hazelcast/hazelcast-jet/files/1605797/generator-jar.zip)
[generator-project.zip](https://github.com/hazelcast/hazelcast-jet/files/1605799/generator-project.zip)
[config.zip](https://github.com/hazelcast/hazelcast-jet/files/1603723/config.zip)

**Comment by mtopolnik** [comment]
If this is your problem statement:

> I am trying to distribute Edge data from node1 to node2 using Edge distributed()

Then a general reply, without a detailed inspection of your code, is this:

Hazelcast Jet is not a tool to transfer data from node to node. In all Jet jobs the whole DAG runs on each node and the purpose of a distributed-partitioned edge is to deliver all items with a given grouping key to the same processor instance in the cluster. There is a [chapter in Jet's reference manual](http://docs.hazelcast.org/docs/jet/0.5.1/manual/Under_the_Hood/How_Distributed_Computing_Works_in_Jet.html) that explains this.

**Comment by haresh-moradiya** [comment]
Thanks for your valuable response.
Yes, I have take simple example which i attached. I have used hazelcast core functionality within sample sliding windowing, accumulate, combine, isolated, partitioning, distribute.
My concern with i want to distinguished and processing within cluster with multiple members. But its fail via the above mention aspect.
Can you please help me here?
Thanks!!!

**Comment by mtopolnik** [comment]
Can you please elaborate on what you mean by

> Its not working properly with hazelcast-0.5.

You presented a lot of testing scenarios, but I don't see what are your success criteria and how Jet failed to meet them.

In scenario 1 you said:

> Sometime its working & sometime its not.

What exactly is sometimes not working? 

In scenario 2 you presumably stop a member while the job is in progress, and then when you start another instance, you sometimes get the error message from your screenshot. This is something we can investigate further.

In scenario 3 you say:

> First isolated vertex process always started with the both nodes.

This sounds like you're misinterpreting the meaning of an `isolated` edge. It is a variation on the default, _local_ edge with a slightly different routing policy. The type of edge does not control where vertex processors are started. Processors for all vertices are always started on all members. Maybe studying our [reference manual](http://docs.hazelcast.org/docs/jet/0.5/manual/The_Core_API/DAG.html) page can further help you with understanding.

I also notice you conflate the concern of cluster formation with job execution. The cluster should be formed as soon as you start the Jet instances and you should see that in the logs you submit your job.

**Comment by haresh-moradiya** [comment]
Thanks for immediate reply.
> You presented a lot of testing scenarios, but I don't see what are your success criteria and how Jet failed to meet them.

Success:
I have checked with two jet members and i am submit job. I see partition & distribute items is working . 
Fail:
I have checked with more than two jet members and when i am submit the job with generated items from source more than three keys . Items are not distribute equally to all the jet member. (Only distributed on two jet members)

> This sounds like you're misinterpreting the meaning of an isolated edge.

Thank you now i am understood. I have one question over here what if i want to add restriction for edge? like edge is only process on coordinate member.

> This is something we can investigate further.

Let me know if you required more information.

**Comment by mtopolnik** [comment]
> what if i want to add restriction for edge? like edge is only process on coordinate member.

What you actually want (I guess) is a distributed `allToOne` edge, where all the processors deliver their data to a single processor. We do have that, but you can't choose the target member, Jet chooses it at random each time you run a job.

**Comment by mtopolnik** [comment]
The warning you saw in your log about a stale master version is not an issue. Sometimes a member receives a stale partition table during cluster reconfiguration. This is a legitimate situation that can sometimes happen in a distributed system and it is handled without error. It would only become a problem if you saw the same line repeated many times.

**Comment by haresh-moradiya** [comment]
Thank you Marko,

> What you actually want (I guess) is a distributed allToOne edge, where all the upstream processors deliver their data to a single downstream processor.

I want to use opposite feature of allToOne. In simple way i want to start single upstream to multiple downstream with multiple member. Single upstream edge choose random member inside Jet Cluster. Right now is it possible or not with hazelcast-jet?

Thanks!!!

**Comment by haresh-moradiya** [comment]
> This is a legitimate situation that can sometimes happen in a distributed system and it is handled without error. It would only become a problem if you saw the same line repeated many times.

I am facing this problem every time when i am restarting a jet member. It's not reconfigure automatically. Is it any problem?
Thanks!!!

**Comment by cangencer** [comment]
If you have a distributed edge between two vertices, then the data will be distributed to all the nodes.

If your DAG is A --> B where A is only emitting items on one node, if the edge to B is distributed then all nodes will be receiving the items. How this happens depends on the edge type. If it's unicast then it will be round robin, if partitioned, then it will be based on key. See the javadoc for edge:

http://docs.hazelcast.org/docs/jet/0.5.1/javadoc/com/hazelcast/jet/core/Edge.html#distributed--

Regarding restarting a member, a running job will not automatically restart on the restarted member after it rejoins the cluster, it will only be running in the remaining members. You have to cancel and resubmit the job.

**Comment by haresh-moradiya** [comment]
Can Gencer & Marko Topolnik. Thanks for great support....
