### ISSUE TITLE
Add run time jet instance in jet cluster.

### ISSUE THREAD

**Issue by parthdwe** [hazelcast/hazelcast-jet#668]
I have to add jet instance in cluster without restarting all other cluster nodes.

Scenario is:
I have two node members in my configuration file and both are running in the cluster now i want to add new node in this cluster at runtime without updating the configuration file of both node, is it be possible to add in cluster?
if it is possible than how?

Thanks in advance!!!!!

**Comment by gurbuzali** [comment]
Yes it is possible. If you are using multicast join, then the new node will automatically join to the cluster. 
If you are using tcp-ip join, then list all ip addresses of the nodes (first 2 nodes and the new node) in your tcp-ip config. 
PS: Adding only one of the ip addresses of the currently clustered nodes is enough to join the cluster but best practice is listing all of them.
