### ISSUE TITLE
Create stateful mapper

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#686]
Normally, mapper needs to be stateless. Create a mapper using:

    statefulMapP(Supplier<S> init, BiFunction<S, T, R> map, Consumer<S> cleanup)

Related question: https://stackoverflow.com/questions/48486511/creating-a-new-jet-custom-partitioner
Related issue: #678

**Comment by viliam-durina** [comment]
This is not feasible: we are unable to correctly save the state to snapshot. It would be possible if we make the state keyed:
```
    public static <K, S, T, R> DistributedSupplier<Processor> statefulMapP(
            @Nonnull DistributedFunction<T, K> extractKeyFn,
            @Nonnull DistributedFunction<K, S> createStateForKeyFn,
            @Nonnull DistributedBiFunction<S, T, R> mapUsingStateFn
    )
```

But this makes the mapper more complex and we lack use case. The edge to it will also need to be distributed&partitioned. So I'm closing this.

**Comment by cangencer** [comment]
I think it could still be useful if the mapper was reliant on some context, i.e. on an object which isn't serializable and would need a unique instance per processor. Currently this requires creating a custom processor.
