### ISSUE TITLE
DistributedCollectors.toSet fails when objects aren't java serializeable

### ISSUE THREAD

**Issue by pschmeltzer** [hazelcast/hazelcast-jet#690]
When map content is serialized via custom or portable, `DistributedCollectors.toSet()` attempts to serialize the `HashSet` via java serialization and fails to serialize the contents. `DistributedCollectors.toList()` works because hazelcast has an `ArrayList` serializer `ArrayListStreamSerializer` which serializes contents using the serializer of the contents object type.

It seems to me hazelcast should have a default serializer for HashSet as streams supports collecting to a Set in the same way it has a ArrayList

A work around is registering a serializer in the config.

```
private static final class HashSetStreamSerializer implements StreamSerializer<HashSet> {

        public void write(ObjectDataOutput out, HashSet set) throws IOException {
            int size = set == null ? -1 : set.size();
            out.writeInt(size);
            if(set != null) {
                Iterator iterator = set.iterator();
                while (iterator.hasNext()) {
                    out.writeObject(iterator.next());
                }
            }
        }

        public HashSet read(ObjectDataInput in) throws IOException {
            int size = in.readInt();
            HashSet result = null;
            if(size > -1) {
                result = new HashSet();
                for (int i = 0; i < size; ++i) {
                    result.add(in.readObject());
                }
            }
            return result;
        }

        public int getTypeId() {
            return <HASHSETID>;
        }

        public void destroy() {}
		
    }
```

**Comment by cangencer** [comment]
This is added for 0.6: https://github.com/hazelcast/hazelcast-jet/blob/master/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/HashSetHook.java

You can use a workaround with 0.5.1 for now by registering a custom serializer. You also don't need null checks since the `write` method will never give you a null object.

**Comment by pschmeltzer** [comment]
Fantastic. Thanks for the quick reply.
