### ISSUE TITLE
Kafka scaling exception

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#709]
If I have a Kafka topic partitioned into 3, and a cluster of 3 it works. If I scale the cluster up to 4, I get this exception (IMDG 3.9.2, Jet 0.5.1):

```
 com.hazelcast.jet.JetException: Total number of Kafka topic partitions (3) is less than the global parallelism (8) for this vertex.  The partition counts for individual Kafka topics are {precious=3}
```

Scaling the grid shouldn't cause an exception if there are more nodes than Kafka partitions

**Comment by viliam-durina** [comment]
Fixed in #660
