### ISSUE TITLE
Clarify JavaDoc in the WatermarkPolicies

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet#712]
Please see [this](https://github.com/jerrinot/hazelcast-jet/blob/cf6a3297d09ae56931414450c95e73de4634eaed/hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/WatermarkPolicies.java#L38-L41):
```
    /**
     * Maintains a watermark that lags behind the top observed timestamp by the
     * given amount. In the case of a stream lull the watermark does not
     * advance towards the top observed timestamp and remains behind it
     * indefinitely.
     *
     * @param lag the desired difference between the top observed timestamp
     *            and the watermark
     */
```

I have no idea what does it mean. I would like to see some guidance here. e.g. when this is a good choice, when it's not, etc.. 

Also I am not sure if "lull" is a typo or a real word:) We should use simple English.

**Comment by cangencer** [comment]
We will reevaluate these policies for 0.6.1. Currently only one is used.

**Comment by cangencer** [comment]
We'll remove WatermarkPolicies completely since it does not really capture the concerns of event lag  by itself. Since this is a breaking change, we'll do it for 0.7.
