### ISSUE TITLE
StreamKafkaP should take ConsumerRecord for projectionFn rather than key and value

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#721]
Currently StreamKafkaP does give the user access to timestamp and header fields. The `projectionFn` should be changed to take a `ConsumerRecord` as source rather than key and value.

Also see:
https://stackoverflow.com/questions/48843770/streamkafkap-with-projectionfn-kafka-timestamp-extractor

**Comment by cangencer** [comment]
This was added as part of the work in the pipeline branch.

**Comment by kleysonr** [comment]
@cangencer not possible to use streamKafkaP passing only properties/projectionFn/topics as in 0.5.1 ?

public static <K, V, T> ProcessorMetaSupplier streamKafkaP(
            @Nonnull Properties properties,
            @Nonnull DistributedBiFunction<K, V, T> projectionFn,
            @Nonnull String... topics
)

**Comment by cangencer** [comment]
You can use `WatermarkGenerationParams.noWatermarks()` as the last parameter if you aren't interested in generating Watermarks at the source.
