### ISSUE TITLE
Spark Connector

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast-jet#727]
Hi All,

Spark was supported by Hazelcast, however currently Spark Hazelcast addon repository is no longer supported. In fact, sometimes users wants to use Spark to process data from Hazelcast IMDG and for some reasons they don't want or are not able to integrate easily with Jet - for example, they may have additional processes in Spark and it would be hard to migrate everything to Jet, like Streaming + batch jobs with some ML algorithms.

Jet connector to Spark, that supports partition pruning, column pruning and streaming source will be a good addition. Currently integration can be done only by using not  supported plugin or by sending content with HDFS or Kafka, which slows down whole processing.

Connector should contain:
 - source and sink for Jet
 - source and sink for Spark

Maybe it would be a good idea to launch support for previous repository, but with more focus on Jet. 

Note that whole integration may be done via old connector with some additional features included, but there is an information in the connector repository, that Spark Connector is no longer supported. However, docs on the website still do not have such information, so this ticket may be created only by confusion made by information in old repository. Integration via IMaps is good enough for Spark and Jet users

**Comment by cangencer** [comment]
@TomaszGaweda that's an interesting thought. The old connector worked by allowing Spark RDDs to be written to and read from Hazelcast IMap. How do you see the Jet integration working?

**Comment by TomaszGaweda** [comment]
Thanks for you response, @cangencer! The simplest way is to implement IMap integration on Spark side, with predicate pushdown, on top of current old connector. I think it's the simplest way to implement and to maintain it, however it's hard to say if I should proceed with PR if the repository is not maintained - it would be a waste of time to implement this feature if it will not be merged. I personally can't maintain it after hours ;) 

If the decision change and connector can be still maintained, I  will try to implement Dataset-based Spark connector, just like Ignite/GridGain guys did - ok, maybe much simpler, but if I will be able to implement predicate pushdown, there will be a huge performance boost :)

For the future, we can also implement reading from Hazelcast Queue from Structured Streaming.

After reading your comment I realized that both Jet and Spark are processing engines, so direct integration would be quite difficult. It could be done only by implementing sink in Spark, that creates Jet's in-memory source or in Jet, as Sink that creates Spark Dataset instance. Both solutions have one big minus: are totally in memory and will be hard to parallelize it correctly. Given that, I would recommend re-launching old connector with implementation of newer Spark API, so that Jet will be able to integrate with Spark directly with IMap and IQueues. What do you think about it?
