### ISSUE TITLE
Multiple "clientConfig" required for Jet client of Jet compute cluster

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#730]
A Jet client JVM that wishes to submit a DAG/Pipeline to a Jet compute cluster with a remote IMDG as source/sink needs to manage multiple `clientConfig` objects.
- the `clientConfig` for the Jet compute cluster it connects to
- the `clientConfig` for each IMDG cluster the DAG/Pipeline connects to

This will be cumbersome and error prone, especially if secure connections are considered.

Would it be possible to somehow register each IMDG `clientConfig` with the Jet compute cluster ?

If the remote source/sink could take the group name string as a parameter instead, this would simplify submission.

**Comment by cangencer** [comment]
I think this can be easily built outside of Jet. Unfortunately `ClientConfig` isn't `Serializable` but you can easily store the config information for each remote cluster in a map for example or a config file? I see very limited use for this right now as of today.
