### ISSUE TITLE
Password in group section obsolete

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#734]
Group password is being dropped (https://github.com/hazelcast/hazelcast/issues/11667) so should be removed from Jet's IMDG XML.

Affects
https://github.com/hazelcast/hazelcast-jet/blob/master/hazelcast-jet-core/src/main/resources/hazelcast-jet-member-default.xml#L23
and
https://github.com/hazelcast/hazelcast-jet/blob/master/hazelcast-jet-core/src/main/resources/hazelcast-jet-client-default.xml#L23

**Comment by cangencer** [comment]
There's also several other references to password, both in main repo and code samples. They should all be removed.

**Comment by cangencer** [comment]
This is still not merged from HZ side, should only be merged after (if) it is merged into 3.11 and Jet updated to 3.11

**Comment by cangencer** [comment]
This will be fixed in 3.11, so moving it to 0.8

**Comment by viliam-durina** [comment]
Password is still there in 3.12-BETA-1. Is it ever going to be removed?

**Comment by cangencer** [comment]
Closing this as password field is still used in EE LoginModule

**Comment by cangencer** [comment]
Reopening, as the password should be removed from default xml files.
