### ISSUE TITLE
getContext() from a custom Kafka projectionFn

### ISSUE THREAD

**Issue by kleysonr** [hazelcast/hazelcast-jet#745]
Hi,

As a developer, I would like to access the processor context from a custom kafka projectionFn in order to enrich my data with some metadata, such as ctx.vertexName(), ctx.globalProcessorIndex() and ctx.jetInstance().getCluster().getLocalMember().getAddress().getHost().

Kleyson Rios.

**Comment by cangencer** [comment]
You can do this by adding another vertex after Kafka with isolated edge between them and same parallelism. The processor indices and the host will be the same and you can enrich the record using these values.

**Comment by kleysonr** [comment]
Yes, it would be one solution, but I'm afraid that I didn't formulate my initial question in the best way.

I'm trying to generate some statistics in each Vertex/processor and send them via async logger to an external system, such as the time to parse my JSON message + some additional processing performed inside the projectionFn, those information need be indexed by host/processorId/messageId. 

Creating a new downstream vertex would make me lose some information from the previous vertex.

Passing the Context as a new parameter to the projectionFn (or some get function) would allow us to access the processor's information without the need to write a wrapper or custom processor, saving some CPU cycles and increasing the performance of the job.

**Comment by cangencer** [comment]
It costs very little in performance to add a simple mapping processor, so you won't necessarily be losing performance attaching this information to your message in projectionFn, and then filter them out later on. In the future we will be adding further optimisations where subsequent mapping stages run inside the same vertex and processor.
