### ISSUE TITLE
com.hazelcast.jet.core.SnapshotFailureTest.when_snapshotFails_then_jobShouldNotFail

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast-jet#759]
https://hazelcast-l337.ci.cloudbees.com/job/Jet-pr-builder/com.hazelcast.jet$hazelcast-jet-core/2484/testReport/junit/com.hazelcast.jet.core/SnapshotFailureTest/when_snapshotFails_then_jobShouldNotFail/

```
Error Message

no failed snapshot appeared in snapshotsMap

Stacktrace

java.lang.AssertionError: no failed snapshot appeared in snapshotsMap
	at com.hazelcast.jet.core.SnapshotFailureTest.when_snapshotFails_then_jobShouldNotFail(SnapshotFailureTest.java:121)
```

**Comment by viliam-durina** [comment]
The test is racy, records for failed snapshots are deleted right after the snapshot is marked as `FAILED`. I'll rewrite to check it using map journal.
