### ISSUE TITLE
Add support for decreasing partition count in WatermarkSourceUtil

### ISSUE THREAD

**Issue by ncherkas** [hazelcast/hazelcast-jet#763]
API of [WatermarkSourceUtil](https://github.com/hazelcast/hazelcast-jet/blob/9e69af82aa25a77f33352689fc3f1926bb9ac4c8/hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/WatermarkSourceUtil.java#L220) doesn't allow to decrease the partition count but this would be useful for Amazon Kinesis or other cloud services, where it's possible to scale down at runtime. It's important since it can hinder the implementation of custom sources.

**Comment by cangencer** [comment]
We currently don't support any sources where partition count can decrease. Closing this for now.
