### ISSUE TITLE
Add first-class support for `Processor.close`

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#764]
Currently we use `ProcessorSupplier.complete()` to clean-up processor instances. There is a utility class `CloseableProcessorSupplier`. It might be easier and useful to add a `close()` directly to `Processor`.

**Comment by lukasherman** [comment]
I would make good use of that. We are calling  `close()` on `Processor` to cleanup JMS resources. However it is not  clear in which stage is `close()` called, whether it is safe to interrupt blocking call in `complete()`, or it can be assumed that no items will come to  `process()` call, so it is safe to close any open connections. 
Is `close()` blocking? Is job marked as `COMPLETED` only after all `close()` calls have returned? What about runtime exceptions thrown inside `close()`? So many open questions..

**Comment by viliam-durina** [comment]
@lukasherman there is currently no `Processor.close()`, only `ProcessorSupplier.complete()`, which has answers for most of your questions documented (current version [here](https://github.com/hazelcast/hazelcast-jet/blob/f5f84f68dbce024c671730d311c638e369f6028c/hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java#L52-L66)). The `Processor.close()` behavior will be the same, once added. It will only be a simplification: you won't be required to use ProcessorSupplier if you only need it for clean-up.

Basically it's called after execution of any `Processor` method is completed on all members. So `Processor.complete` is not called in parallel to any other method in `Processor` on any member and any other `Processor` method won't be called after it. There's no need to cancel blocking calls there: if you cancel the job, Jet calls `interrupt()`. `ProcessorSupplier.complete()` method itself can be blocking. Runtime exceptions in it are logged and ignored, they are not reported as job failures. Job is marked as `COMPLETED` or `FAILED` after `PS.complete` methods on all members complete, `Job.join()` also returns after that.

There is special case: when a member left the cluster we don't know what happened there. It might have shut down, but there might also be a network split and that member could be doing some work after we cancelled.

**Comment by lukasherman** [comment]
Thanks for detailed explanation.
So `Job.cancel()` results in `interrupt()` called on blocking `complete()`, followed by `close()`? Does it mean the code inside `complete()` must be interruptible?

**Comment by viliam-durina** [comment]
`Processor.complete()` doesn't technically have to be interruptible, more is required (quoted from `Processor.completed` javadoc):
```
     * Non-cooperative processors are required to return from this method from
     * time to time to give the system a chance to check for snapshot requests
     * and job cancellation. The time the processor spends in this method affects
     * the latency of snapshots and job cancellations.
```
If it responds to `interrupt`, it will cancel faster. But it's enough to return from time to time, the cancellation status is also checked by the caller.
