### ISSUE TITLE
Prevent Jet and Hazelcast instances joining same cluster

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#767]
Currently both Jet and Hazelcast use different default group name and multicast port, but it's possible to override these, resulting in a Jet and Hazelcast instance joining the same cluster. This must be prevented even if configurations are same.

**Comment by vladoschreiner** [comment]
Can wouldn’t it be better to create such an improvements as PRDs?

**Comment by cangencer** [comment]
Yes we can make it a PRD, I think it mainly includes changes in Hazelcast. We should probably aim for 0.6.1?

**Comment by cangencer** [comment]
This can be enforced using `ConfigCheck` class.

**Comment by cangencer** [comment]
Covered by PRD, closing the issue.
