### ISSUE TITLE
NonCooperative processors - high idle CPU consumption

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast-jet#775]
Hello Jet Team,
I have observed high cpu consumption when lots of nonCooperative processors are used in DAG. Example given below takes 40% CPU, with `VERTEX_COUNT = 200` it takes 100% CPU on dev laptop. 

```INFO: [127.0.0.1]:5001 [dev] [0.6-SNAPSHOT] processors=4, physical.memory.total=15,9G, physical.memory.free=7,5G, swap.space.total=16,9G, swap.space.free=6,5G, heap.memory.used=137,4M, heap.memory.free=144,1M, heap.memory.total=281,5M, heap.memory.max=3,5G, heap.memory.used/total=48,82%, heap.memory.used/max=3,81%, minor.gc.count=12, minor.gc.time=93ms, major.gc.count=1, major.gc.time=40ms, load.process=10,10%, load.system=76,52%, load.systemAverage=n/a thread.count=436, thread.peakCount=439, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1177, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0,00%, operations.pending.invocations.count=273, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0```

See test below:
```java
import com.hazelcast.config.Config;
import com.hazelcast.jet.config.JetConfig;
import com.hazelcast.jet.core.*;
import com.hazelcast.jet.core.processor.Processors;
import com.hazelcast.jet.core.processor.SourceProcessors;
import com.hazelcast.jet.pipeline.JournalInitialPosition;
import org.junit.Test;

public class NonCooperativePerformanceTest extends JetTestSupport {
    private static final int VERTEX_COUNT = 100;
    
    @Test
    public void test() {
        DAG dag = buildDAG();
        JetConfig jetConfig = new JetConfig();
        Config hazelcastConfig = new Config();
        hazelcastConfig.getMapEventJournalConfig("test*").setEnabled(true);
        jetConfig.setHazelcastConfig(hazelcastConfig);
        createJetMember(jetConfig).newJob(dag).join();
    }

    private DAG buildDAG() {
        DAG dag = new DAG();
        Vertex source = dag.newVertex("source", SourceProcessors.streamMapP("testmap", JournalInitialPosition.START_FROM_CURRENT, WatermarkGenerationParams.noWatermarks()));
        for (int i = 0; i < VERTEX_COUNT; i++) {
            // OK: Vertex v = dag.newVertex("vertex" + i, Processors.mapP(o -> o));
            Vertex v = dag.newVertex("ncvertex" + i, Processors.nonCooperativeP(Processors.mapP(o -> o)));
            dag.edge(Edge.from(source).to(v));
            source = v;
        }
        return dag;
    }
}
```
I have observed a similar behavior on the deployed application during idle period.
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 5097 root      20   0 40.369g 3.854g  17344 S 869.4  3.5   1834:44 java -Djava.security.egd=file:/dev/./urandom -Dhazelcast.jmx=true -Dspring.profiles.active=...
```

**Comment by lukasherman** [comment]
Is it something which can be tuned or resolved easily? The example above is just a simple reproducer, in real scenario there are lots of non-cooperative processors used especially for systems integration (JMS/JDBC/REST) or basically more complex custom processors reading/writing from/to different maps to update/enrich data as a part of business logic (as recommended by dev guide that access to map entry should be performed in non-cooperative processor due to possible blocking IO).

**Comment by cangencer** [comment]
Keeping parallelism to 1 or 2 maximum for non-cooperative vertices can be a good practice unless you really need higher throughput, but I will discuss it with the team this internally and get back to you. We can probably tweak the idle backoff to be a little more friendly for context switches.

**Comment by lukasherman** [comment]
Ok, I would be happy with max 5-10% overhead.

**Comment by viliam-durina** [comment]
Default parallelism for `streamMapP` is 2, unless you set something else.

**Comment by viliam-durina** [comment]
@lukasherman Are you doing enrichment of stream items based on IMap? It could be done in cooperative way if you used `getAsync` or `getAll`.

**Comment by lukasherman** [comment]
@viliam-durina do you have an example?

**Comment by viliam-durina** [comment]
Here it is: https://gist.github.com/viliam-durina/889d003f0dc608de42d713274bb57ba8
It's lightly tested :)

**Comment by lukasherman** [comment]
Thanks, I got the idea. You are delegating inbox/outbox queue management into the processor. 
Btw do you plan to remove support for nonCooperative processors completely from Jet? Our use case for nonCooperative processors is basically revolving around integration capabilities - JMS RequestResponse vertex, REST API outbound call vertex, and stream-to-batch transition vertex. And some complex transformations where multiple maps are used to derive the outcome. The major and extremely useful benefit provided by nonCooperative processor in those use cases is implicit thread safety, easy to use programming model, plus configurable parallelism on the vertex level.

**Comment by viliam-durina** [comment]
We don't plan to remove support for non-cooperative processors. Probably all processors can be converted to cooperative if the target system provides a truly async API. But as you say, writing non-cooperative processors is simpler.

**Comment by lukasherman** [comment]
Sounds good. Can you please estimate impact of this change on CPU usage? Will the CPU load be reduced significantly, or it just pushes the limits a bit higher?

**Comment by viliam-durina** [comment]
This will just push the limit higher. Green threads switch faster than OS threads, but there's still some little work for each processor to do each time it gets its time. 

Internally we've benchmarked how many parallel jobs can we run in single cluster. Results are not directly comparable to your case, but we've been able to run more jobs and more throughput with cooperative processors.

**Comment by viliam-durina** [comment]
24 NC vertices with LP=1 shouldn't be a bottleneck. I guess most of the idle CPU usage is from cooperative processors doing little work. Idle CPU usage for cooperative vertices shouldn't bother you (except for saving electricity): it doesn't limit throughput. The `CooperativeWorker` spins cooperative processors and only idles if none of them makes progress (takes nothing from inbox and puts nothing to outbox). If just one processor makes some progress, it won't idle at all and start a new spin.

If there is a lot of events to handle, each processor will do more work in one run. In our parallel jobs benchmark i had 3000 jobs (each with 6 cooperative vertices) and had 60% cpu with 12k events/s and 100% cpu for 200k events/s, but i still was able to process 10m events/s.

I recommend you to use LP=1 for _all_ vertices, even for cooperative ones. This will reduce the number of tasklets for cooperative worker. I think splitting large DAG into multiple smaller ones won't help.

**Comment by lukasherman** [comment]
Yes, I have noticed that throughput is not limited. I will investigate the option to limit LP. Thanks for your valuable input. 

So now I understand why I was unable to find out where most of the idle time was spent, because the CooperativeWorker/BlockingWorker threads are spinning, here at 75/22 ratio. 

![image](https://user-images.githubusercontent.com/6349334/38305902-e951b19c-380e-11e8-98e9-f18e0efd8f9e.png)

**Comment by lukasherman** [comment]
One more question, is there a difference between running 3000 jobs with 6 vertices versus 6 jobs with 3000 vertices?

**Comment by viliam-durina** [comment]
Depends on the shape of the DAG. Is it 
```
A -> B -> C -> D
```
or
```
A ┬-> B
  ├-> C
  ┗-> D
```
or even
```
A -> B
C -> D
E -> F
```
I believe the third case is no different to three separate jobs. I would choose separate jobs due to less interdependence: they can fail independently at least.

Second case should be faster because it shares source. It can also share the sink.

First case is convertible to multiple jobs only by using external queue for storing intermediate results, which will induce overhead.

What's your DAG shape?

**Comment by lukasherman** [comment]
DAG resembles a decision tree, on OK continue, on ERROR perform state change and terminate.
```
A ---> B ------> C ------> D ---->E
       |         |         |
       B(err)    C(err)    D(err)
       ┗---------┗ --------┗--->F
```
So the number of edges is roughly 2x number of vertices. 
We are currently discussing an option to split the DAG into multiple smaller ones and use Map/EventJournal to connect the parts.

**Comment by lukasherman** [comment]
I have followed your recommendation to _use LP=1 for all vertices, even for cooperative ones_, made it a tunable parameter. It reduced idle CPU usage significantly, down to 0.8 core from 4, per Jet instance.

**Comment by cangencer** [comment]
@lukasherman are you happy with the current state? If so I'll close the issue? We've also made some improvements to idle CPU usage for blocking processors as per Viliam's PR.

**Comment by lukasherman** [comment]
@cangencer yes, you can close the issue. Thank you.
