### ISSUE TITLE
Add shell scripts to list running jobs and control them

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#801]
From shell we currently can:
- start & stop jet members
- submit job

We need scripts to:
- list jobs and print their status
- filter them by name, status
- print the failure reason
- cancel the job

Possibly also:
- specify job name when submitting with `jet-submit.sh`
- specify other `JobConfig` options

All the APIs are available in Java (new in 0.6), we miss the scripts.

**Comment by cangencer** [comment]
Covered by PRD
