### ISSUE TITLE
DAG with unused vertices

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#818]
Jet 0.6 allows you to create a DAG with vertices that aren't connected edges. This should generate a warning at least, maybe an error, as the DAG is misconfigured.

eg.
```
dag
    .vertex("kafkaSource").localParallelism(1)
    .vertex("logSink1").localParallelism(1)
    .vertex("unused").localParallelism(1)
    .edge(between("kafkaSource", "logSink1"))
```

**Comment by cangencer** [comment]
There might be some value in validating this, as it's more than likely a mistake so it's quite useful if it would fail fast. You're not likely to create a single vertex DAG which has a Processor which only has some side effect and you want to use Jet as just a distributed executor. You can still recreate this scenario by adding a second vertex with a noop processor.

I don't also see a problem having multiple independent graphs in the same DAG, but we shouldn't allow "dangling" vertices.

**Comment by cangencer** [comment]
Closing this for now. We decided to allow dangling vertices as they might still be used for some purpose.
