### ISSUE TITLE
Jet 0.6 release embeds IMDG non-release

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#819]
Jet 0.6 release has a dependency on IMDG version "3.10-BETA-2". Release software shouldn't depend on non-release software (snapshot, beta, etc)

```
$ mvn dependency:tree | grep com.hazelcast
[INFO] ----------------< com.hazelcast.jet:hazelcast-jet-root >----------------
[INFO] com.hazelcast.jet:hazelcast-jet-root:pom:0.6
[INFO] +- com.hazelcast:hazelcast:jar:tests:3.10-BETA-2:test
```

**Comment by viliam-durina** [comment]
AFAIK this was intentional, to not hinder the 0.6 release. 0.6.1 will be released with GA version.

**Comment by cangencer** [comment]
Yes, this was intentional and it's also mentioned in the blog post. Next Jet release after 3.10 will include the final version.
