### ISSUE TITLE
Detect partition migration when reading an IMap

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#830]
Currently the iteration can silently miss or duplicate some events in case a partition migration takes place while iterating. If a member is added, the job will continue to run, but is likely to produce incorrect output silently. We need to interrupt and restart the job in this case (IMap reading is also used for snapshot restore).

**Comment by cangencer** [comment]
Also related to stable iteration of IMap: https://github.com/hazelcast/hazelcast/issues/11106
