### ISSUE TITLE
TestSupport ordinal control

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#831]
In `TestSupport` you can do multiple ordinal input
with

    TestSupport
    .inputs(Arrays.asList(ordinal0, ordinal1, ordinal2))

However, you can't control the sequence of items from each ordinal. 0 is exhausted first, rather than any interleaving.

So if ordinal 0 has `item1` and `item3` and ordinal 1 has `item2`, you can't test `item2` arriving before `item3`.

Would be useful if input could be

    .inputs([0,item1],[1,item2],[0,item3])

some sort of array prefixing each item by the ordinal, so can force certain sequences of input

**Comment by neilstevenson** [comment]
Ok, here's the test that I'd like to pass

	@Test
	public void a_a_b_b_a_a() {
        TestSupport.verifyProcessor(Processors.mapP(DistributedFunction.identity()))
        .inputs(Arrays.asList(
                Arrays.asList("A", "A", "A", "A"),
                Arrays.asList("B", "B")
        ))
        .expectOutput(Arrays.asList("A", "A", "B", "B", "A", "A"));
	}

Two inputs from 0, two from 1, then two more from 0

**Comment by cangencer** [comment]
We could probably have a `InputBuilder` which offers precise control over input sequence.

Keep in mind though in a real execution, there's no guarantees as to which ordinal will be processed first and you can get items from different ordinals in any order.

**Comment by mtopolnik** [comment]
Closing for low relevance.
