### ISSUE TITLE
 com.hazelcast.jet.core.JobRestartWithSnapshotTest.when_nodeDown_then_jobRestartsFromSnapshot_singleStage

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#834]
https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet-maintenance/com.hazelcast.jet$hazelcast-jet-core/17/testReport/junit/com.hazelcast.jet.core/JobRestartWithSnapshotTest/when_nodeDown_then_jobRestartsFromSnapshot_singleStage/

**Comment by viliam-durina** [comment]
Resolved by #840
