### ISSUE TITLE
Consistent behaviour of `mapToOutputFn` in aggregation operations

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#837]
`mapToOutputFn` in aggregations should support returning `null` to filter out certain keys and values to make it consistent with other `map` and `flatMap` operations.

This will allow the user to filter out empty results and prevent having to create a temporary item just to filter it out later.

See related question: https://stackoverflow.com/questions/50013276/hazelcast-jet-discard-empty-aggregation-results

**Comment by viliam-durina** [comment]
We should probably support the `AggregateOperation.finishFn()` to return `null` as well.
