### ISSUE TITLE
Incorrect validation when adding Edge to DAG

### ISSUE THREAD

**Issue by mirkoluchi** [hazelcast/hazelcast-jet#844]
Hi,

I see that method **DAG.edge(Edge)** method throws an **IllegalArgumentException** if there already is an edge between the same vertices of the Edge being added.

I have this case however, that makes me think that this kind of edge validation is incorrect:

- a **source** that emits objects of type **A** and **B**
- a **custom router processor**, that routes input objects to **edge 0** if they are of **type A**, to **edge 1** if they are of **type B**
- a **custom calculator processor** that **expects** inputs of **type A on edge 0** and inputs of **type B on edge 1**.
- a **sink**

My DAG therefore has these edges:
- source -> router
- router(0) -> calculator(0)
- router(1) -> calculator(1)
- calculator -> sink

As you can see, there are 2 edges between router and calculator, but they are not an error...they are meant to be like that.

**Comment by cangencer** [comment]
Our DAG currently doesn't support multi-graph (multiple edges between two vertices), so the validation is correct. However you can work around it by adding a simple forwarding node so your DAG looks like this:

```
source --> router (0) --------------------> (0) calculator
                  (1)-------forwarder ----> (1)
```
