### ISSUE TITLE
XSDs out of date 

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#852]
https://github.com/hazelcast/hazelcast-jet/blob/master/hazelcast-jet-core/src/main/resources/hazelcast-jet-client-default.xml
references `hazelcast-client-config-3.9.xsd` but embedded IMDG is 3.10

Same for https://github.com/hazelcast/hazelcast-jet/blob/master/hazelcast-jet-core/src/main/resources/hazelcast-jet-member-default.xml

**Comment by cangencer** [comment]
Fixed
