### ISSUE TITLE
Processor cleanup should be done eagerly

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#867]
Currently `Processor` instances are cleaned up only on job completion. The cleanup involves calling `Processor.close()` and also deregistering the metrics from `MetricsRegistry`. This should instead be done after each individual processor is completed, so that they don't unnecessarily hold on to resources.

**Comment by viliam-durina** [comment]
With this, the metrics will disappear for completed vertices, as if they never existed. You'll see the DAG in the MC, and when you click on the completed vertex, you'll see nothing.
