### ISSUE TITLE
Hazelcast Jet for Data Transfer

### ISSUE THREAD

**Issue by sachinwalia2k8** [hazelcast/hazelcast-jet#869]
I am wondering if Jet is a good framework to create data transfer pipeline. We have a legacy Database that contains multiple 30+ million record tables that need to be migrated and split across multiple tables in RDS. Due to need for Migration + transformation from MS SQL to Postgres RDS, straight forklifting via AWS DMS isn't possible. I am wondering if this is something Jet based pipeline will be suitable for. 

Any help is highly appreciated.

**Comment by cangencer** [comment]
Yes this should be possible. We currently don't have a JDBC source or sink but are working on one for the next release, or you can choose to build a custom source and sink yourself.

Main things to think about are how the source data will be distributed across the cluster and what processing steps you'll need to make before writing it to the target database. I'm guessing you'll probably need to read each record via a query and then map it to some intermediary Java class, and then write it out to your target sink.
