### ISSUE TITLE
 java.lang.IllegalArgumentException: PortableFactory[-10] is already registered! 

### ISSUE THREAD

**Issue by praveenraturi94** [hazelcast/hazelcast-jet#953]
while integrating Hazelcast jet 0.6.1 with spring boots version 1.4.0 i m facing an issue that says -
```
 java.lang.IllegalArgumentException: PortableFactory[-10] is already registered! com.hazelcast.map.impl.client.MapPortableHook$MapPortableFactory@671f545b -> com.hazelcast.map.impl.MapPortableHook$1@c335b9
```
how can i fix this issue.

**Comment by neilstevenson** [comment]
Can you attach something that demonstrates the issue ? See https://stackoverflow.com/help/mcve for instance

Sometimes the error message is enough to deduce the problem, this doesn't look like one of those times

**Comment by amitsgithubid** [comment]
HI,


Could get around this issue by making changes for Hazelcast Jet's dependency definition  -

This is what did try earlier and it did not work -

 
<dependency>
   <groupId>com.hazelcast.jet</groupId>
   <artifactId>hazelcast-jet-spring</artifactId>
   <version>0.6.1</version>
</dependency>

When I change it to following ,it works -

<dependency>
   <groupId>com.hazelcast.jet</groupId>
   <artifactId>hazelcast-jet</artifactId>
   <version>0.6.1</version>
</dependency>

Issue is fixed now.
