### ISSUE TITLE
com.hazelcast.jet.impl.util.AsyncMapWriterTest.when_writeErrorOnlyOnce_then_retrySuccess

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#975]
```
Error Message
expected:<0> but was:<null>
Stacktrace
java.lang.AssertionError: expected:<0> but was:<null>
	at com.hazelcast.jet.impl.util.AsyncMapWriterTest.when_writeErrorOnlyOnce_then_retrySuccess(AsyncMapWriterTest.java:260)
```

https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet/com.hazelcast.jet$hazelcast-jet-core/825/testReport/junit/com.hazelcast.jet.impl.util/AsyncMapWriterTest/when_writeErrorOnlyOnce_then_retrySuccess/

**Comment by viliam-durina** [comment]
Cannot reproduce the failure locally. The test output is interleaved with other tests in the class, hard to tell which lines pertain to this test. There's no exception in the output.

[com.hazelcast.jet.impl.util.AsyncMapWriterTest-output[1].txt](https://github.com/hazelcast/hazelcast-jet/files/2286997/com.hazelcast.jet.impl.util.AsyncMapWriterTest-output.1.txt)

**Comment by viliam-durina** [comment]
The failure reproduced locally in about 0.1% of cases.

**Comment by cangencer** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/jet/com.hazelcast.jet$hazelcast-jet-core/954/testReport/junit/com.hazelcast.jet.impl.util/AsyncMapWriterTest/when_writeErrorOnlyOnce_then_retrySuccess/

```
Error Message
expected:<2> but was:<null>
Stacktrace
java.lang.AssertionError: expected:<2> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.jet.impl.util.AsyncMapWriterTest.when_writeErrorOnlyOnce_then_retrySuccess(AsyncMapWriterTest.java:261)
```
