### ISSUE TITLE
EntryProcessor gets a null as value of entry.

### ISSUE THREAD

**Issue by Ultar** [hazelcast/hazelcast-jet#981]
hazelcast-jet 0.6.1
hazelcast 3.10.3

When I use method Sinks.mapWithEntryProcessor in my pipeline, I can't fetch the entry's value because it is a null.
**Pipeline:**
```
        streamStage.drainTo(Sinks.mapWithEntryProcessor(Constants.IMAP_NOTIFICATIONS,
                Map.Entry::getKey,
                entry -> new CustomProcessor()
        ));
```
**Processor:**
```
public class CustomProcessorimplements EntryProcessor<String, List<TagPosition>> {
    @Override
    public Object process(Map.Entry<String, List<TagPosition>> entry)
```

The entry.getKey has a proper value, the entry.getValue is null. The source map is filled correctly.

**Comment by eminn** [comment]
Hi @Ultar,

```
        streamStage.peek().drainTo(Sinks.mapWithEntryProcessor(Constants.IMAP_NOTIFICATIONS,
                Map.Entry::getKey,
                entry -> new CustomProcessor()
        ));
```
Can you peek into the stream before the sink to verify that entries received by the sink has a non-null value fields ? 

Also if you have a reproducer application it would be better for us to help you with the issue.

**Comment by eminn** [comment]
Hi @Ultar,

It might also be the case that the key that is coming from the stream does not exist in the `Constants.IMAP_NOTIFICATIONS ` map so that the value might be null. In that case, to insert a value for that key you can call `entry.setValue(NEW_VALUE)`.

**Comment by Ultar** [comment]
Hi @eminn, thanks for your reply!

The method peek() shows me output like this:

`08-03-2018 16:10:55 [hz._hzInstance_1_dev.jet.cooperative.thread-0] c.h.j.i.p.P.map#0[INFO] - [192.168.56.1]:5701 [dev] [0.6.1-SNAPSHOT] Output to ordinal 0: b9440858-145a-4cf1-b0db-c9c24bc08206=[smartgis.bean.positioning.TagPosition@6dbda56f, smartgis.bean.positioning.TagPosition@7f396638....`

and it means that values are non-null.

Could you please clarify why key from stream should exist in output map `Constants.IMAP_NOTIFICATIONS`? The stream and output map should be synchronized by keys?

**Comment by eminn** [comment]
HI @Ultar,

Entry processor returns you the actual entry in the map, so if the key that you are executing an entry processor against is not exists in the map, you'll get an entry with a `null` value.

Imagine a the following cases;

Case 1 :  
map contents [key=value] -> `1=istanbul`
If I execute an entry processor on key 1 , the entry I'll get as a parameter in the entry processor will  be `1=istanbul`

Case 2:  
map contents [key,value] ->empty map
If I execute an entry processor on key 1 , the entry I'll get as a parameter in the entry processor will be `1=null `since the key is non existing in the map, so the value, and I can store the key in the map by calling `entry.setValue(NEW_VALUE).` 

Does that makes it clear ?

**Comment by cangencer** [comment]
Also, you need to pass the `entry` object to your CustomProcessor in the constructor so that you can use it. It might be more convenient to use `mapWithUpdating` or `mapWithMerging` sinks instead.

**Comment by eminn** [comment]
So in order for you to store values of the entries in the stream that you'll need to pass them as values into CustomProcessor whilst you create them like below : 

```
        streamStage.drainTo(Sinks.mapWithEntryProcessor(Constants.IMAP_NOTIFICATIONS,
                Map.Entry::getKey,
                entry -> new CustomProcessor(entry.getValue())
        ));
```
And your entry processor will be something like this:
```
public class CustomProcessor implements EntryProcessor<String, List<TagPosition>> {
  List<TagPosition> valueFromStream;
   public CustomProcessor(List<TagPosition> valueFromStream){
    this.valueFromStream = valueFromStream;
    }
    @Override
    public Object process(Map.Entry<String, List<TagPosition>> entry){
    entry.setValue(valueFromStream);
}

```

**Comment by Ultar** [comment]
Thanks all for the comments! It was my misunderstanding of the manual. Now we can close this ticket.
